// Generated by jextract

package com.dx12;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import jdk.incubator.foreign.*;
import jdk.incubator.foreign.MemoryLayout.PathElement;
import static jdk.incubator.foreign.CSupport.Win64.*;

public class d3d12_h$constants$12 extends d3d12_h$constants$11 {
    d3d12_h$constants$12() {}
    public static int D3D12_DEFAULT_RENDER_TARGET_ARRAY_INDEX() { return (int)0L; }

    public static int D3D12_DEFAULT_RESOURCE_PLACEMENT_ALIGNMENT() { return (int)65536L; }

    public static int D3D12_DEFAULT_SAMPLE_MASK() { return (int)4294967295L; }

    public static int D3D12_DEFAULT_SCISSOR_ENDX() { return (int)0L; }

    public static int D3D12_DEFAULT_SCISSOR_ENDY() { return (int)0L; }

    public static int D3D12_DEFAULT_SCISSOR_STARTX() { return (int)0L; }

    public static int D3D12_DEFAULT_SCISSOR_STARTY() { return (int)0L; }

    public static float D3D12_DEFAULT_SLOPE_SCALED_DEPTH_BIAS() { return 0.0f; }

    public static int D3D12_DEFAULT_STENCIL_READ_MASK() { return (int)255L; }

    public static int D3D12_DEFAULT_STENCIL_REFERENCE() { return (int)0L; }

    public static int D3D12_DEFAULT_STENCIL_WRITE_MASK() { return (int)255L; }

    public static int D3D12_DEFAULT_VIEWPORT_AND_SCISSORRECT_INDEX() { return (int)0L; }

    public static int D3D12_DEFAULT_VIEWPORT_HEIGHT() { return (int)0L; }

    public static float D3D12_DEFAULT_VIEWPORT_MAX_DEPTH() { return 0.0f; }

    public static float D3D12_DEFAULT_VIEWPORT_MIN_DEPTH() { return 0.0f; }

    public static int D3D12_DEFAULT_VIEWPORT_TOPLEFTX() { return (int)0L; }

    public static int D3D12_DEFAULT_VIEWPORT_TOPLEFTY() { return (int)0L; }

    public static int D3D12_DEFAULT_VIEWPORT_WIDTH() { return (int)0L; }

    public static int D3D12_DESCRIPTOR_RANGE_OFFSET_APPEND() { return (int)4294967295L; }

    public static int D3D12_DRIVER_RESERVED_REGISTER_SPACE_VALUES_END() { return (int)4294967287L; }

    public static int D3D12_DRIVER_RESERVED_REGISTER_SPACE_VALUES_START() { return (int)4294967280L; }

    public static int D3D12_DS_INPUT_CONTROL_POINTS_MAX_TOTAL_SCALARS() { return (int)3968L; }

    public static int D3D12_DS_INPUT_CONTROL_POINT_REGISTER_COMPONENTS() { return (int)4L; }

    public static int D3D12_DS_INPUT_CONTROL_POINT_REGISTER_COMPONENT_BIT_COUNT() { return (int)32L; }

    public static int D3D12_DS_INPUT_CONTROL_POINT_REGISTER_COUNT() { return (int)32L; }

    public static int D3D12_DS_INPUT_CONTROL_POINT_REGISTER_READS_PER_INST() { return (int)2L; }

    public static int D3D12_DS_INPUT_CONTROL_POINT_REGISTER_READ_PORTS() { return (int)1L; }

    public static int D3D12_DS_INPUT_DOMAIN_POINT_REGISTER_COMPONENTS() { return (int)3L; }

    public static int D3D12_DS_INPUT_DOMAIN_POINT_REGISTER_COMPONENT_BIT_COUNT() { return (int)32L; }

    public static int D3D12_DS_INPUT_DOMAIN_POINT_REGISTER_COUNT() { return (int)1L; }

    public static int D3D12_DS_INPUT_DOMAIN_POINT_REGISTER_READS_PER_INST() { return (int)2L; }

    public static int D3D12_DS_INPUT_DOMAIN_POINT_REGISTER_READ_PORTS() { return (int)1L; }

    public static int D3D12_DS_INPUT_PATCH_CONSTANT_REGISTER_COMPONENTS() { return (int)4L; }

    public static int D3D12_DS_INPUT_PATCH_CONSTANT_REGISTER_COMPONENT_BIT_COUNT() { return (int)32L; }

    public static int D3D12_DS_INPUT_PATCH_CONSTANT_REGISTER_COUNT() { return (int)32L; }

    public static int D3D12_DS_INPUT_PATCH_CONSTANT_REGISTER_READS_PER_INST() { return (int)2L; }

    public static int D3D12_DS_INPUT_PATCH_CONSTANT_REGISTER_READ_PORTS() { return (int)1L; }

    public static int D3D12_DS_INPUT_PRIMITIVE_ID_REGISTER_COMPONENTS() { return (int)1L; }

    public static int D3D12_DS_INPUT_PRIMITIVE_ID_REGISTER_COMPONENT_BIT_COUNT() { return (int)32L; }

    public static int D3D12_DS_INPUT_PRIMITIVE_ID_REGISTER_COUNT() { return (int)1L; }

    public static int D3D12_DS_INPUT_PRIMITIVE_ID_REGISTER_READS_PER_INST() { return (int)2L; }

    public static int D3D12_DS_INPUT_PRIMITIVE_ID_REGISTER_READ_PORTS() { return (int)1L; }

    public static int D3D12_DS_OUTPUT_REGISTER_COMPONENTS() { return (int)4L; }

    public static int D3D12_DS_OUTPUT_REGISTER_COMPONENT_BIT_COUNT() { return (int)32L; }

    public static int D3D12_DS_OUTPUT_REGISTER_COUNT() { return (int)32L; }

    public static double D3D12_FLOAT16_FUSED_TOLERANCE_IN_ULP() { return 0.6d; }

    public static float D3D12_FLOAT32_MAX() { return 3.4028234663852886E38f; }

    public static float D3D12_FLOAT32_TO_INTEGER_TOLERANCE_IN_ULP() { return 0.6000000238418579f; }

    public static float D3D12_FLOAT_TO_SRGB_EXPONENT_DENOMINATOR() { return 2.4000000953674316f; }

    public static float D3D12_FLOAT_TO_SRGB_EXPONENT_NUMERATOR() { return 1.0f; }

    public static float D3D12_FLOAT_TO_SRGB_OFFSET() { return 0.054999999701976776f; }

    public static float D3D12_FLOAT_TO_SRGB_SCALE_1() { return 12.920000076293945f; }

    public static float D3D12_FLOAT_TO_SRGB_SCALE_2() { return 1.0549999475479126f; }

    public static float D3D12_FLOAT_TO_SRGB_THRESHOLD() { return 0.0031308000907301903f; }

    public static float D3D12_FTOI_INSTRUCTION_MAX_INPUT() { return 2.147483648E9f; }

    public static float D3D12_FTOI_INSTRUCTION_MIN_INPUT() { return -2.147483648E9f; }

    public static float D3D12_FTOU_INSTRUCTION_MAX_INPUT() { return 4.294967296E9f; }

    public static float D3D12_FTOU_INSTRUCTION_MIN_INPUT() { return 0.0f; }

    public static int D3D12_GS_INPUT_INSTANCE_ID_READS_PER_INST() { return (int)2L; }

    public static int D3D12_GS_INPUT_INSTANCE_ID_READ_PORTS() { return (int)1L; }

    public static int D3D12_GS_INPUT_INSTANCE_ID_REGISTER_COMPONENTS() { return (int)1L; }

    public static int D3D12_GS_INPUT_INSTANCE_ID_REGISTER_COMPONENT_BIT_COUNT() { return (int)32L; }

    public static int D3D12_GS_INPUT_INSTANCE_ID_REGISTER_COUNT() { return (int)1L; }

    public static int D3D12_GS_INPUT_PRIM_CONST_REGISTER_COMPONENTS() { return (int)1L; }

    public static int D3D12_GS_INPUT_PRIM_CONST_REGISTER_COMPONENT_BIT_COUNT() { return (int)32L; }

    public static int D3D12_GS_INPUT_PRIM_CONST_REGISTER_COUNT() { return (int)1L; }

    public static int D3D12_GS_INPUT_PRIM_CONST_REGISTER_READS_PER_INST() { return (int)2L; }

    public static int D3D12_GS_INPUT_PRIM_CONST_REGISTER_READ_PORTS() { return (int)1L; }

    public static int D3D12_GS_INPUT_REGISTER_COMPONENTS() { return (int)4L; }

    public static int D3D12_GS_INPUT_REGISTER_COMPONENT_BIT_COUNT() { return (int)32L; }

    public static int D3D12_GS_INPUT_REGISTER_COUNT() { return (int)32L; }

    public static int D3D12_GS_INPUT_REGISTER_READS_PER_INST() { return (int)2L; }

    public static int D3D12_GS_INPUT_REGISTER_READ_PORTS() { return (int)1L; }

    public static int D3D12_GS_INPUT_REGISTER_VERTICES() { return (int)32L; }

    public static int D3D12_GS_MAX_INSTANCE_COUNT() { return (int)32L; }

    public static int D3D12_GS_MAX_OUTPUT_VERTEX_COUNT_ACROSS_INSTANCES() { return (int)1024L; }

    public static int D3D12_GS_OUTPUT_ELEMENTS() { return (int)32L; }

    public static int D3D12_GS_OUTPUT_REGISTER_COMPONENTS() { return (int)4L; }

    public static int D3D12_GS_OUTPUT_REGISTER_COMPONENT_BIT_COUNT() { return (int)32L; }

    public static int D3D12_GS_OUTPUT_REGISTER_COUNT() { return (int)32L; }

    public static int D3D12_HS_CONTROL_POINT_PHASE_INPUT_REGISTER_COUNT() { return (int)32L; }

    public static int D3D12_HS_CONTROL_POINT_PHASE_OUTPUT_REGISTER_COUNT() { return (int)32L; }

    public static int D3D12_HS_CONTROL_POINT_REGISTER_COMPONENTS() { return (int)4L; }

    public static int D3D12_HS_CONTROL_POINT_REGISTER_COMPONENT_BIT_COUNT() { return (int)32L; }

    public static int D3D12_HS_CONTROL_POINT_REGISTER_READS_PER_INST() { return (int)2L; }

    public static int D3D12_HS_CONTROL_POINT_REGISTER_READ_PORTS() { return (int)1L; }

    public static int D3D12_HS_FORK_PHASE_INSTANCE_COUNT_UPPER_BOUND() { return (int)4294967295L; }

    public static int D3D12_HS_INPUT_FORK_INSTANCE_ID_REGISTER_COMPONENTS() { return (int)1L; }

    public static int D3D12_HS_INPUT_FORK_INSTANCE_ID_REGISTER_COMPONENT_BIT_COUNT() { return (int)32L; }

    public static int D3D12_HS_INPUT_FORK_INSTANCE_ID_REGISTER_COUNT() { return (int)1L; }

    public static int D3D12_HS_INPUT_FORK_INSTANCE_ID_REGISTER_READS_PER_INST() { return (int)2L; }

    public static int D3D12_HS_INPUT_FORK_INSTANCE_ID_REGISTER_READ_PORTS() { return (int)1L; }

    public static int D3D12_HS_INPUT_JOIN_INSTANCE_ID_REGISTER_COMPONENTS() { return (int)1L; }

    public static int D3D12_HS_INPUT_JOIN_INSTANCE_ID_REGISTER_COMPONENT_BIT_COUNT() { return (int)32L; }

    public static int D3D12_HS_INPUT_JOIN_INSTANCE_ID_REGISTER_COUNT() { return (int)1L; }

    public static int D3D12_HS_INPUT_JOIN_INSTANCE_ID_REGISTER_READS_PER_INST() { return (int)2L; }

    public static int D3D12_HS_INPUT_JOIN_INSTANCE_ID_REGISTER_READ_PORTS() { return (int)1L; }

    public static int D3D12_HS_INPUT_PRIMITIVE_ID_REGISTER_COMPONENTS() { return (int)1L; }

    public static int D3D12_HS_INPUT_PRIMITIVE_ID_REGISTER_COMPONENT_BIT_COUNT() { return (int)32L; }

    public static int D3D12_HS_INPUT_PRIMITIVE_ID_REGISTER_COUNT() { return (int)1L; }

    public static int D3D12_HS_INPUT_PRIMITIVE_ID_REGISTER_READS_PER_INST() { return (int)2L; }

    public static int D3D12_HS_INPUT_PRIMITIVE_ID_REGISTER_READ_PORTS() { return (int)1L; }

    public static int D3D12_HS_JOIN_PHASE_INSTANCE_COUNT_UPPER_BOUND() { return (int)4294967295L; }

    public static float D3D12_HS_MAXTESSFACTOR_LOWER_BOUND() { return 1.0f; }

    public static float D3D12_HS_MAXTESSFACTOR_UPPER_BOUND() { return 64.0f; }

    public static int D3D12_HS_OUTPUT_CONTROL_POINTS_MAX_TOTAL_SCALARS() { return (int)3968L; }

    public static int D3D12_HS_OUTPUT_CONTROL_POINT_ID_REGISTER_COMPONENTS() { return (int)1L; }

    public static int D3D12_HS_OUTPUT_CONTROL_POINT_ID_REGISTER_COMPONENT_BIT_COUNT() { return (int)32L; }

    public static int D3D12_HS_OUTPUT_CONTROL_POINT_ID_REGISTER_COUNT() { return (int)1L; }

    public static int D3D12_HS_OUTPUT_CONTROL_POINT_ID_REGISTER_READS_PER_INST() { return (int)2L; }

    public static int D3D12_HS_OUTPUT_CONTROL_POINT_ID_REGISTER_READ_PORTS() { return (int)1L; }

    public static int D3D12_HS_OUTPUT_PATCH_CONSTANT_REGISTER_COMPONENTS() { return (int)4L; }

    public static int D3D12_HS_OUTPUT_PATCH_CONSTANT_REGISTER_COMPONENT_BIT_COUNT() { return (int)32L; }

    public static int D3D12_HS_OUTPUT_PATCH_CONSTANT_REGISTER_COUNT() { return (int)32L; }

    public static int D3D12_HS_OUTPUT_PATCH_CONSTANT_REGISTER_READS_PER_INST() { return (int)2L; }

    public static int D3D12_HS_OUTPUT_PATCH_CONSTANT_REGISTER_READ_PORTS() { return (int)1L; }

    public static int D3D12_HS_OUTPUT_PATCH_CONSTANT_REGISTER_SCALAR_COMPONENTS() { return (int)128L; }

    public static int D3D12_IA_DEFAULT_INDEX_BUFFER_OFFSET_IN_BYTES() { return (int)0L; }

    public static int D3D12_IA_DEFAULT_PRIMITIVE_TOPOLOGY() { return (int)0L; }

    public static int D3D12_IA_DEFAULT_VERTEX_BUFFER_OFFSET_IN_BYTES() { return (int)0L; }

    public static int D3D12_IA_INDEX_INPUT_RESOURCE_SLOT_COUNT() { return (int)1L; }

    public static int D3D12_IA_INSTANCE_ID_BIT_COUNT() { return (int)32L; }

    public static int D3D12_IA_INTEGER_ARITHMETIC_BIT_COUNT() { return (int)32L; }

    public static int D3D12_IA_PATCH_MAX_CONTROL_POINT_COUNT() { return (int)32L; }

    public static int D3D12_IA_PRIMITIVE_ID_BIT_COUNT() { return (int)32L; }

    public static int D3D12_IA_VERTEX_ID_BIT_COUNT() { return (int)32L; }

    public static int D3D12_IA_VERTEX_INPUT_RESOURCE_SLOT_COUNT() { return (int)32L; }

    public static int D3D12_IA_VERTEX_INPUT_STRUCTURE_ELEMENTS_COMPONENTS() { return (int)128L; }

    public static int D3D12_IA_VERTEX_INPUT_STRUCTURE_ELEMENT_COUNT() { return (int)32L; }

    public static int D3D12_INTEGER_DIVIDE_BY_ZERO_QUOTIENT() { return (int)4294967295L; }

    public static int D3D12_INTEGER_DIVIDE_BY_ZERO_REMAINDER() { return (int)4294967295L; }

    public static int D3D12_KEEP_RENDER_TARGETS_AND_DEPTH_STENCIL() { return (int)4294967295L; }

    public static int D3D12_KEEP_UNORDERED_ACCESS_VIEWS() { return (int)4294967295L; }

    public static float D3D12_LINEAR_GAMMA() { return 1.0f; }

    public static int D3D12_MAJOR_VERSION() { return (int)12L; }

    public static float D3D12_MAX_BORDER_COLOR_COMPONENT() { return 1.0f; }

    public static float D3D12_MAX_DEPTH() { return 1.0f; }

    public static int D3D12_MAX_LIVE_STATIC_SAMPLERS() { return (int)2032L; }

    public static int D3D12_MAX_MAXANISOTROPY() { return (int)16L; }

    public static int D3D12_MAX_MULTISAMPLE_SAMPLE_COUNT() { return (int)32L; }

    public static float D3D12_MAX_POSITION_VALUE() { return 3.4028235832468283E34f; }

    public static int D3D12_MAX_ROOT_COST() { return (int)64L; }

    public static int D3D12_MAX_SHADER_VISIBLE_DESCRIPTOR_HEAP_SIZE_TIER_1() { return (int)1000000L; }

    public static int D3D12_MAX_SHADER_VISIBLE_DESCRIPTOR_HEAP_SIZE_TIER_2() { return (int)1000000L; }

    public static int D3D12_MAX_SHADER_VISIBLE_SAMPLER_HEAP_SIZE() { return (int)2048L; }

    public static int D3D12_MAX_TEXTURE_DIMENSION_2_TO_EXP() { return (int)17L; }

    public static int D3D12_MAX_VIEW_INSTANCE_COUNT() { return (int)4L; }

    public static int D3D12_MINOR_VERSION() { return (int)0L; }

    public static float D3D12_MIN_BORDER_COLOR_COMPONENT() { return 0.0f; }

    public static float D3D12_MIN_DEPTH() { return 0.0f; }

    public static int D3D12_MIN_MAXANISOTROPY() { return (int)0L; }

    public static float D3D12_MIP_LOD_BIAS_MAX() { return 15.989999771118164f; }

    public static float D3D12_MIP_LOD_BIAS_MIN() { return -16.0f; }

    public static int D3D12_MIP_LOD_FRACTIONAL_BIT_COUNT() { return (int)8L; }

    public static int D3D12_MIP_LOD_RANGE_BIT_COUNT() { return (int)8L; }

    public static float D3D12_MULTISAMPLE_ANTIALIAS_LINE_WIDTH() { return 1.399999976158142f; }

    public static int D3D12_NONSAMPLE_FETCH_OUT_OF_RANGE_ACCESS_RESULT() { return (int)0L; }

    public static int D3D12_OS_RESERVED_REGISTER_SPACE_VALUES_END() { return (int)4294967295L; }

    public static int D3D12_OS_RESERVED_REGISTER_SPACE_VALUES_START() { return (int)4294967288L; }

    public static int D3D12_PACKED_TILE() { return (int)4294967295L; }

    public static int D3D12_PIXEL_ADDRESS_RANGE_BIT_COUNT() { return (int)15L; }

    public static int D3D12_PRE_SCISSOR_PIXEL_ADDRESS_RANGE_BIT_COUNT() { return (int)16L; }

    public static int D3D12_PS_CS_UAV_REGISTER_COMPONENTS() { return (int)1L; }

    public static int D3D12_PS_CS_UAV_REGISTER_COUNT() { return (int)8L; }

    public static int D3D12_PS_CS_UAV_REGISTER_READS_PER_INST() { return (int)1L; }

    public static int D3D12_PS_CS_UAV_REGISTER_READ_PORTS() { return (int)1L; }

    public static int D3D12_PS_FRONTFACING_DEFAULT_VALUE() { return (int)4294967295L; }

    public static int D3D12_PS_FRONTFACING_FALSE_VALUE() { return (int)0L; }

    public static int D3D12_PS_FRONTFACING_TRUE_VALUE() { return (int)4294967295L; }

    public static int D3D12_PS_INPUT_REGISTER_COMPONENTS() { return (int)4L; }

    public static int D3D12_PS_INPUT_REGISTER_COMPONENT_BIT_COUNT() { return (int)32L; }

    public static int D3D12_PS_INPUT_REGISTER_COUNT() { return (int)32L; }

    public static int D3D12_PS_INPUT_REGISTER_READS_PER_INST() { return (int)2L; }

    public static int D3D12_PS_INPUT_REGISTER_READ_PORTS() { return (int)1L; }

    public static float D3D12_PS_LEGACY_PIXEL_CENTER_FRACTIONAL_COMPONENT() { return 0.0f; }

    public static int D3D12_PS_OUTPUT_DEPTH_REGISTER_COMPONENTS() { return (int)1L; }

    public static int D3D12_PS_OUTPUT_DEPTH_REGISTER_COMPONENT_BIT_COUNT() { return (int)32L; }

    public static int D3D12_PS_OUTPUT_DEPTH_REGISTER_COUNT() { return (int)1L; }

    public static int D3D12_PS_OUTPUT_MASK_REGISTER_COMPONENTS() { return (int)1L; }

    public static int D3D12_PS_OUTPUT_MASK_REGISTER_COMPONENT_BIT_COUNT() { return (int)32L; }

    public static int D3D12_PS_OUTPUT_MASK_REGISTER_COUNT() { return (int)1L; }

    public static int D3D12_PS_OUTPUT_REGISTER_COMPONENTS() { return (int)4L; }

    public static int D3D12_PS_OUTPUT_REGISTER_COMPONENT_BIT_COUNT() { return (int)32L; }

    public static int D3D12_PS_OUTPUT_REGISTER_COUNT() { return (int)8L; }

    public static float D3D12_PS_PIXEL_CENTER_FRACTIONAL_COMPONENT() { return 0.5f; }

    public static int D3D12_RAW_UAV_SRV_BYTE_ALIGNMENT() { return (int)16L; }

    public static int D3D12_RAYTRACING_AABB_BYTE_ALIGNMENT() { return (int)8L; }

    public static int D3D12_RAYTRACING_ACCELERATION_STRUCTURE_BYTE_ALIGNMENT() { return (int)256L; }

    public static int D3D12_RAYTRACING_INSTANCE_DESCS_BYTE_ALIGNMENT() { return (int)16L; }

    public static int D3D12_RAYTRACING_MAX_ATTRIBUTE_SIZE_IN_BYTES() { return (int)32L; }

    public static int D3D12_RAYTRACING_MAX_DECLARABLE_TRACE_RECURSION_DEPTH() { return (int)31L; }

    public static int D3D12_RAYTRACING_MAX_GEOMETRIES_PER_BOTTOM_LEVEL_ACCELERATION_STRUCTURE() { return (int)16777216L; }

    public static int D3D12_RAYTRACING_MAX_INSTANCES_PER_TOP_LEVEL_ACCELERATION_STRUCTURE() { return (int)16777216L; }

    public static int D3D12_RAYTRACING_MAX_PRIMITIVES_PER_BOTTOM_LEVEL_ACCELERATION_STRUCTURE() { return (int)536870912L; }

    public static int D3D12_RAYTRACING_MAX_RAY_GENERATION_SHADER_THREADS() { return (int)1073741824L; }

    public static int D3D12_RAYTRACING_MAX_SHADER_RECORD_STRIDE() { return (int)4096L; }

    public static int D3D12_RAYTRACING_SHADER_RECORD_BYTE_ALIGNMENT() { return (int)32L; }

    public static int D3D12_RAYTRACING_SHADER_TABLE_BYTE_ALIGNMENT() { return (int)64L; }

    public static int D3D12_RAYTRACING_TRANSFORM3X4_BYTE_ALIGNMENT() { return (int)16L; }

    public static int D3D12_REQ_BLEND_OBJECT_COUNT_PER_DEVICE() { return (int)4096L; }

    public static int D3D12_REQ_BUFFER_RESOURCE_TEXEL_COUNT_2_TO_EXP() { return (int)27L; }

    public static int D3D12_REQ_CONSTANT_BUFFER_ELEMENT_COUNT() { return (int)4096L; }

    public static int D3D12_REQ_DEPTH_STENCIL_OBJECT_COUNT_PER_DEVICE() { return (int)4096L; }

    public static int D3D12_REQ_DRAWINDEXED_INDEX_COUNT_2_TO_EXP() { return (int)32L; }

    public static int D3D12_REQ_DRAW_VERTEX_COUNT_2_TO_EXP() { return (int)32L; }

    public static int D3D12_REQ_FILTERING_HW_ADDRESSABLE_RESOURCE_DIMENSION() { return (int)16384L; }

    public static int D3D12_REQ_GS_INVOCATION_32BIT_OUTPUT_COMPONENT_LIMIT() { return (int)1024L; }

    public static int D3D12_REQ_IMMEDIATE_CONSTANT_BUFFER_ELEMENT_COUNT() { return (int)4096L; }

    public static int D3D12_REQ_MAXANISOTROPY() { return (int)16L; }

    public static int D3D12_REQ_MIP_LEVELS() { return (int)15L; }

    public static int D3D12_REQ_MULTI_ELEMENT_STRUCTURE_SIZE_IN_BYTES() { return (int)2048L; }

    public static int D3D12_REQ_RASTERIZER_OBJECT_COUNT_PER_DEVICE() { return (int)4096L; }

    public static int D3D12_REQ_RENDER_TO_BUFFER_WINDOW_WIDTH() { return (int)16384L; }

    public static int D3D12_REQ_RESOURCE_SIZE_IN_MEGABYTES_EXPRESSION_A_TERM() { return (int)128L; }

    public static float D3D12_REQ_RESOURCE_SIZE_IN_MEGABYTES_EXPRESSION_B_TERM() { return 0.25f; }

    public static int D3D12_REQ_RESOURCE_SIZE_IN_MEGABYTES_EXPRESSION_C_TERM() { return (int)2048L; }

    public static int D3D12_REQ_RESOURCE_VIEW_COUNT_PER_DEVICE_2_TO_EXP() { return (int)20L; }

    public static int D3D12_REQ_SAMPLER_OBJECT_COUNT_PER_DEVICE() { return (int)4096L; }

    public static int D3D12_REQ_SUBRESOURCES() { return (int)30720L; }

    public static int D3D12_REQ_TEXTURE1D_ARRAY_AXIS_DIMENSION() { return (int)2048L; }

    public static int D3D12_REQ_TEXTURE1D_U_DIMENSION() { return (int)16384L; }

    public static int D3D12_REQ_TEXTURE2D_ARRAY_AXIS_DIMENSION() { return (int)2048L; }

    public static int D3D12_REQ_TEXTURE2D_U_OR_V_DIMENSION() { return (int)16384L; }

    public static int D3D12_REQ_TEXTURE3D_U_V_OR_W_DIMENSION() { return (int)2048L; }

    public static int D3D12_REQ_TEXTURECUBE_DIMENSION() { return (int)16384L; }

    public static int D3D12_RESINFO_INSTRUCTION_MISSING_COMPONENT_RETVAL() { return (int)0L; }

    public static int D3D12_RESOURCE_BARRIER_ALL_SUBRESOURCES() { return (int)4294967295L; }

    public static int D3D12_RS_SET_SHADING_RATE_COMBINER_COUNT() { return (int)2L; }

    public static int D3D12_SHADER_IDENTIFIER_SIZE_IN_BYTES() { return (int)32L; }

    public static int D3D12_SHADER_MAJOR_VERSION() { return (int)5L; }

    public static int D3D12_SHADER_MAX_INSTANCES() { return (int)65535L; }

    public static int D3D12_SHADER_MAX_INTERFACES() { return (int)253L; }

    public static int D3D12_SHADER_MAX_INTERFACE_CALL_SITES() { return (int)4096L; }

    public static int D3D12_SHADER_MAX_TYPES() { return (int)65535L; }

    public static int D3D12_SHADER_MINOR_VERSION() { return (int)1L; }

    public static int D3D12_SHIFT_INSTRUCTION_PAD_VALUE() { return (int)0L; }

    public static int D3D12_SHIFT_INSTRUCTION_SHIFT_VALUE_BIT_COUNT() { return (int)5L; }

    public static int D3D12_SIMULTANEOUS_RENDER_TARGET_COUNT() { return (int)8L; }

    public static int D3D12_SMALL_MSAA_RESOURCE_PLACEMENT_ALIGNMENT() { return (int)65536L; }

    public static int D3D12_SMALL_RESOURCE_PLACEMENT_ALIGNMENT() { return (int)4096L; }

    public static int D3D12_SO_BUFFER_MAX_STRIDE_IN_BYTES() { return (int)2048L; }

    public static int D3D12_SO_BUFFER_MAX_WRITE_WINDOW_IN_BYTES() { return (int)512L; }

    public static int D3D12_SO_BUFFER_SLOT_COUNT() { return (int)4L; }

    public static int D3D12_SO_DDI_REGISTER_INDEX_DENOTING_GAP() { return (int)4294967295L; }

    public static int D3D12_SO_NO_RASTERIZED_STREAM() { return (int)4294967295L; }

    public static int D3D12_SO_OUTPUT_COMPONENT_COUNT() { return (int)128L; }

    public static int D3D12_SO_STREAM_COUNT() { return (int)4L; }

    public static int D3D12_SPEC_DATE_DAY() { return (int)14L; }

    public static int D3D12_SPEC_DATE_MONTH() { return (int)11L; }

    public static int D3D12_SPEC_DATE_YEAR() { return (int)2014L; }

    public static double D3D12_SPEC_VERSION() { return 1.16d; }

    public static float D3D12_SRGB_GAMMA() { return 2.200000047683716f; }

    public static float D3D12_SRGB_TO_FLOAT_DENOMINATOR_1() { return 12.920000076293945f; }

    public static float D3D12_SRGB_TO_FLOAT_DENOMINATOR_2() { return 1.0549999475479126f; }

    public static float D3D12_SRGB_TO_FLOAT_EXPONENT() { return 2.4000000953674316f; }

    public static float D3D12_SRGB_TO_FLOAT_OFFSET() { return 0.054999999701976776f; }

    public static float D3D12_SRGB_TO_FLOAT_THRESHOLD() { return 0.040449999272823334f; }

    public static float D3D12_SRGB_TO_FLOAT_TOLERANCE_IN_ULP() { return 0.5f; }

    public static int D3D12_STANDARD_COMPONENT_BIT_COUNT() { return (int)32L; }

    public static int D3D12_STANDARD_COMPONENT_BIT_COUNT_DOUBLED() { return (int)64L; }

    public static int D3D12_STANDARD_MAXIMUM_ELEMENT_ALIGNMENT_BYTE_MULTIPLE() { return (int)4L; }

    public static int D3D12_STANDARD_PIXEL_COMPONENT_COUNT() { return (int)128L; }

    public static int D3D12_STANDARD_PIXEL_ELEMENT_COUNT() { return (int)32L; }

    public static int D3D12_STANDARD_VECTOR_SIZE() { return (int)4L; }

    public static int D3D12_STANDARD_VERTEX_ELEMENT_COUNT() { return (int)32L; }

    public static int D3D12_STANDARD_VERTEX_TOTAL_COMPONENT_COUNT() { return (int)64L; }

    public static int D3D12_SUBPIXEL_FRACTIONAL_BIT_COUNT() { return (int)8L; }

    public static int D3D12_SUBTEXEL_FRACTIONAL_BIT_COUNT() { return (int)8L; }

    public static int D3D12_SYSTEM_RESERVED_REGISTER_SPACE_VALUES_END() { return (int)4294967295L; }

    public static int D3D12_SYSTEM_RESERVED_REGISTER_SPACE_VALUES_START() { return (int)4294967280L; }

    public static int D3D12_TESSELLATOR_MAX_EVEN_TESSELLATION_FACTOR() { return (int)64L; }

    public static int D3D12_TESSELLATOR_MAX_ISOLINE_DENSITY_TESSELLATION_FACTOR() { return (int)64L; }

    public static int D3D12_TESSELLATOR_MAX_ODD_TESSELLATION_FACTOR() { return (int)63L; }

    public static int D3D12_TESSELLATOR_MAX_TESSELLATION_FACTOR() { return (int)64L; }

    public static int D3D12_TESSELLATOR_MIN_EVEN_TESSELLATION_FACTOR() { return (int)2L; }

    public static int D3D12_TESSELLATOR_MIN_ISOLINE_DENSITY_TESSELLATION_FACTOR() { return (int)1L; }

    public static int D3D12_TESSELLATOR_MIN_ODD_TESSELLATION_FACTOR() { return (int)1L; }

    public static int D3D12_TEXEL_ADDRESS_RANGE_BIT_COUNT() { return (int)16L; }

    public static int D3D12_TEXTURE_DATA_PITCH_ALIGNMENT() { return (int)256L; }

    public static int D3D12_TEXTURE_DATA_PLACEMENT_ALIGNMENT() { return (int)512L; }

    public static int D3D12_TILED_RESOURCE_TILE_SIZE_IN_BYTES() { return (int)65536L; }

    public static int D3D12_TRACKED_WORKLOAD_MAX_INSTANCES() { return (int)32L; }

    public static int D3D12_UAV_COUNTER_PLACEMENT_ALIGNMENT() { return (int)4096L; }

    public static int D3D12_UAV_SLOT_COUNT() { return (int)64L; }

    public static int D3D12_UNBOUND_MEMORY_ACCESS_RESULT() { return (int)0L; }

    public static int D3D12_VIDEO_DECODE_MAX_ARGUMENTS() { return (int)10L; }

    public static int D3D12_VIDEO_DECODE_MAX_HISTOGRAM_COMPONENTS() { return (int)4L; }

    public static int D3D12_VIDEO_DECODE_MIN_BITSTREAM_OFFSET_ALIGNMENT() { return (int)256L; }

    public static int D3D12_VIDEO_DECODE_MIN_HISTOGRAM_OFFSET_ALIGNMENT() { return (int)256L; }

    public static int D3D12_VIDEO_DECODE_STATUS_MACROBLOCKS_AFFECTED_UNKNOWN() { return (int)4294967295L; }

    public static int D3D12_VIDEO_PROCESS_MAX_FILTERS() { return (int)32L; }

    public static int D3D12_VIDEO_PROCESS_STEREO_VIEWS() { return (int)2L; }

    public static int D3D12_VIEWPORT_AND_SCISSORRECT_MAX_INDEX() { return (int)15L; }

    public static int D3D12_VIEWPORT_AND_SCISSORRECT_OBJECT_COUNT_PER_PIPELINE() { return (int)16L; }

    public static int D3D12_VIEWPORT_BOUNDS_MAX() { return (int)32767L; }

    public static int D3D12_VIEWPORT_BOUNDS_MIN() { return (int)-32768L; }

    public static int D3D12_VS_INPUT_REGISTER_COMPONENTS() { return (int)4L; }

    public static int D3D12_VS_INPUT_REGISTER_COMPONENT_BIT_COUNT() { return (int)32L; }

    public static int D3D12_VS_INPUT_REGISTER_COUNT() { return (int)32L; }

    public static int D3D12_VS_INPUT_REGISTER_READS_PER_INST() { return (int)2L; }

    public static int D3D12_VS_INPUT_REGISTER_READ_PORTS() { return (int)1L; }

    public static int D3D12_VS_OUTPUT_REGISTER_COMPONENTS() { return (int)4L; }

    public static int D3D12_VS_OUTPUT_REGISTER_COMPONENT_BIT_COUNT() { return (int)32L; }

    public static int D3D12_VS_OUTPUT_REGISTER_COUNT() { return (int)32L; }

    public static int D3D12_WHQL_CONTEXT_COUNT_FOR_RESOURCE_LIMIT() { return (int)10L; }

    public static int D3D12_WHQL_DRAWINDEXED_INDEX_COUNT_2_TO_EXP() { return (int)25L; }

    public static int D3D12_WHQL_DRAW_VERTEX_COUNT_2_TO_EXP() { return (int)25L; }

    public static int D3D12_SHADER_COMPONENT_MAPPING_ALWAYS_SET_BIT_AVOIDING_ZEROMEM_MISTAKES() { return (int)4096L; }

    public static int D3D12_DEFAULT_SHADER_4_COMPONENT_MAPPING() { return (int)5768L; }

    public static int D3D12_FILTER_REDUCTION_TYPE_MASK() { return (int)3L; }

    public static int D3D12_FILTER_REDUCTION_TYPE_SHIFT() { return (int)7L; }

    public static int D3D12_FILTER_TYPE_MASK() { return (int)3L; }

    public static int D3D12_MIN_FILTER_SHIFT() { return (int)4L; }

    public static int D3D12_MAG_FILTER_SHIFT() { return (int)2L; }

    public static int D3D12_MIP_FILTER_SHIFT() { return (int)0L; }

    public static int D3D12_ANISOTROPIC_FILTERING_BIT() { return (int)64L; }

}

