// Generated by jextract

package com.dx12;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import jdk.incubator.foreign.*;
import jdk.incubator.foreign.MemoryLayout.PathElement;
import static jdk.incubator.foreign.CSupport.Win64.*;

public class Windows_h$constants$44 extends Windows_h$constants$43 {
    Windows_h$constants$44() {}
    public static int SCARD_E_UNKNOWN_CARD() { return (int)-2146435059L; }

    public static int SCARD_E_CANT_DISPOSE() { return (int)-2146435058L; }

    public static int SCARD_E_PROTO_MISMATCH() { return (int)-2146435057L; }

    public static int SCARD_E_NOT_READY() { return (int)-2146435056L; }

    public static int SCARD_E_INVALID_VALUE() { return (int)-2146435055L; }

    public static int SCARD_E_SYSTEM_CANCELLED() { return (int)-2146435054L; }

    public static int SCARD_F_COMM_ERROR() { return (int)-2146435053L; }

    public static int SCARD_F_UNKNOWN_ERROR() { return (int)-2146435052L; }

    public static int SCARD_E_INVALID_ATR() { return (int)-2146435051L; }

    public static int SCARD_E_NOT_TRANSACTED() { return (int)-2146435050L; }

    public static int SCARD_E_READER_UNAVAILABLE() { return (int)-2146435049L; }

    public static int SCARD_P_SHUTDOWN() { return (int)-2146435048L; }

    public static int SCARD_E_PCI_TOO_SMALL() { return (int)-2146435047L; }

    public static int SCARD_E_READER_UNSUPPORTED() { return (int)-2146435046L; }

    public static int SCARD_E_DUPLICATE_READER() { return (int)-2146435045L; }

    public static int SCARD_E_CARD_UNSUPPORTED() { return (int)-2146435044L; }

    public static int SCARD_E_NO_SERVICE() { return (int)-2146435043L; }

    public static int SCARD_E_SERVICE_STOPPED() { return (int)-2146435042L; }

    public static int SCARD_E_UNEXPECTED() { return (int)-2146435041L; }

    public static int SCARD_E_ICC_INSTALLATION() { return (int)-2146435040L; }

    public static int SCARD_E_ICC_CREATEORDER() { return (int)-2146435039L; }

    public static int SCARD_E_UNSUPPORTED_FEATURE() { return (int)-2146435038L; }

    public static int SCARD_E_DIR_NOT_FOUND() { return (int)-2146435037L; }

    public static int SCARD_E_FILE_NOT_FOUND() { return (int)-2146435036L; }

    public static int SCARD_E_NO_DIR() { return (int)-2146435035L; }

    public static int SCARD_E_NO_FILE() { return (int)-2146435034L; }

    public static int SCARD_E_NO_ACCESS() { return (int)-2146435033L; }

    public static int SCARD_E_WRITE_TOO_MANY() { return (int)-2146435032L; }

    public static int SCARD_E_BAD_SEEK() { return (int)-2146435031L; }

    public static int SCARD_E_INVALID_CHV() { return (int)-2146435030L; }

    public static int SCARD_E_UNKNOWN_RES_MNG() { return (int)-2146435029L; }

    public static int SCARD_E_NO_SUCH_CERTIFICATE() { return (int)-2146435028L; }

    public static int SCARD_E_CERTIFICATE_UNAVAILABLE() { return (int)-2146435027L; }

    public static int SCARD_E_NO_READERS_AVAILABLE() { return (int)-2146435026L; }

    public static int SCARD_E_COMM_DATA_LOST() { return (int)-2146435025L; }

    public static int SCARD_E_NO_KEY_CONTAINER() { return (int)-2146435024L; }

    public static int SCARD_E_SERVER_TOO_BUSY() { return (int)-2146435023L; }

    public static int SCARD_E_PIN_CACHE_EXPIRED() { return (int)-2146435022L; }

    public static int SCARD_E_NO_PIN_CACHE() { return (int)-2146435021L; }

    public static int SCARD_E_READ_ONLY_CARD() { return (int)-2146435020L; }

    public static int SCARD_W_UNSUPPORTED_CARD() { return (int)-2146434971L; }

    public static int SCARD_W_UNRESPONSIVE_CARD() { return (int)-2146434970L; }

    public static int SCARD_W_UNPOWERED_CARD() { return (int)-2146434969L; }

    public static int SCARD_W_RESET_CARD() { return (int)-2146434968L; }

    public static int SCARD_W_REMOVED_CARD() { return (int)-2146434967L; }

    public static int SCARD_W_SECURITY_VIOLATION() { return (int)-2146434966L; }

    public static int SCARD_W_WRONG_CHV() { return (int)-2146434965L; }

    public static int SCARD_W_CHV_BLOCKED() { return (int)-2146434964L; }

    public static int SCARD_W_EOF() { return (int)-2146434963L; }

    public static int SCARD_W_CANCELLED_BY_USER() { return (int)-2146434962L; }

    public static int SCARD_W_CARD_NOT_AUTHENTICATED() { return (int)-2146434961L; }

    public static int SCARD_W_CACHE_ITEM_NOT_FOUND() { return (int)-2146434960L; }

    public static int SCARD_W_CACHE_ITEM_STALE() { return (int)-2146434959L; }

    public static int SCARD_W_CACHE_ITEM_TOO_BIG() { return (int)-2146434958L; }

    public static int COMADMIN_E_OBJECTERRORS() { return (int)-2146368511L; }

    public static int COMADMIN_E_OBJECTINVALID() { return (int)-2146368510L; }

    public static int COMADMIN_E_KEYMISSING() { return (int)-2146368509L; }

    public static int COMADMIN_E_ALREADYINSTALLED() { return (int)-2146368508L; }

    public static int COMADMIN_E_APP_FILE_WRITEFAIL() { return (int)-2146368505L; }

    public static int COMADMIN_E_APP_FILE_READFAIL() { return (int)-2146368504L; }

    public static int COMADMIN_E_APP_FILE_VERSION() { return (int)-2146368503L; }

    public static int COMADMIN_E_BADPATH() { return (int)-2146368502L; }

    public static int COMADMIN_E_APPLICATIONEXISTS() { return (int)-2146368501L; }

    public static int COMADMIN_E_ROLEEXISTS() { return (int)-2146368500L; }

    public static int COMADMIN_E_CANTCOPYFILE() { return (int)-2146368499L; }

    public static int COMADMIN_E_NOUSER() { return (int)-2146368497L; }

    public static int COMADMIN_E_INVALIDUSERIDS() { return (int)-2146368496L; }

    public static int COMADMIN_E_NOREGISTRYCLSID() { return (int)-2146368495L; }

    public static int COMADMIN_E_BADREGISTRYPROGID() { return (int)-2146368494L; }

    public static int COMADMIN_E_AUTHENTICATIONLEVEL() { return (int)-2146368493L; }

    public static int COMADMIN_E_USERPASSWDNOTVALID() { return (int)-2146368492L; }

    public static int COMADMIN_E_CLSIDORIIDMISMATCH() { return (int)-2146368488L; }

    public static int COMADMIN_E_REMOTEINTERFACE() { return (int)-2146368487L; }

    public static int COMADMIN_E_DLLREGISTERSERVER() { return (int)-2146368486L; }

    public static int COMADMIN_E_NOSERVERSHARE() { return (int)-2146368485L; }

    public static int COMADMIN_E_DLLLOADFAILED() { return (int)-2146368483L; }

    public static int COMADMIN_E_BADREGISTRYLIBID() { return (int)-2146368482L; }

    public static int COMADMIN_E_APPDIRNOTFOUND() { return (int)-2146368481L; }

    public static int COMADMIN_E_REGISTRARFAILED() { return (int)-2146368477L; }

    public static int COMADMIN_E_COMPFILE_DOESNOTEXIST() { return (int)-2146368476L; }

    public static int COMADMIN_E_COMPFILE_LOADDLLFAIL() { return (int)-2146368475L; }

    public static int COMADMIN_E_COMPFILE_GETCLASSOBJ() { return (int)-2146368474L; }

    public static int COMADMIN_E_COMPFILE_CLASSNOTAVAIL() { return (int)-2146368473L; }

    public static int COMADMIN_E_COMPFILE_BADTLB() { return (int)-2146368472L; }

    public static int COMADMIN_E_COMPFILE_NOTINSTALLABLE() { return (int)-2146368471L; }

    public static int COMADMIN_E_NOTCHANGEABLE() { return (int)-2146368470L; }

    public static int COMADMIN_E_NOTDELETEABLE() { return (int)-2146368469L; }

    public static int COMADMIN_E_SESSION() { return (int)-2146368468L; }

    public static int COMADMIN_E_COMP_MOVE_LOCKED() { return (int)-2146368467L; }

    public static int COMADMIN_E_COMP_MOVE_BAD_DEST() { return (int)-2146368466L; }

    public static int COMADMIN_E_REGISTERTLB() { return (int)-2146368464L; }

    public static int COMADMIN_E_SYSTEMAPP() { return (int)-2146368461L; }

    public static int COMADMIN_E_COMPFILE_NOREGISTRAR() { return (int)-2146368460L; }

    public static int COMADMIN_E_COREQCOMPINSTALLED() { return (int)-2146368459L; }

    public static int COMADMIN_E_SERVICENOTINSTALLED() { return (int)-2146368458L; }

    public static int COMADMIN_E_PROPERTYSAVEFAILED() { return (int)-2146368457L; }

    public static int COMADMIN_E_OBJECTEXISTS() { return (int)-2146368456L; }

    public static int COMADMIN_E_COMPONENTEXISTS() { return (int)-2146368455L; }

    public static int COMADMIN_E_REGFILE_CORRUPT() { return (int)-2146368453L; }

    public static int COMADMIN_E_PROPERTY_OVERFLOW() { return (int)-2146368452L; }

    public static int COMADMIN_E_NOTINREGISTRY() { return (int)-2146368450L; }

    public static int COMADMIN_E_OBJECTNOTPOOLABLE() { return (int)-2146368449L; }

    public static int COMADMIN_E_APPLID_MATCHES_CLSID() { return (int)-2146368442L; }

    public static int COMADMIN_E_ROLE_DOES_NOT_EXIST() { return (int)-2146368441L; }

    public static int COMADMIN_E_START_APP_NEEDS_COMPONENTS() { return (int)-2146368440L; }

    public static int COMADMIN_E_REQUIRES_DIFFERENT_PLATFORM() { return (int)-2146368439L; }

    public static int COMADMIN_E_CAN_NOT_EXPORT_APP_PROXY() { return (int)-2146368438L; }

    public static int COMADMIN_E_CAN_NOT_START_APP() { return (int)-2146368437L; }

    public static int COMADMIN_E_CAN_NOT_EXPORT_SYS_APP() { return (int)-2146368436L; }

    public static int COMADMIN_E_CANT_SUBSCRIBE_TO_COMPONENT() { return (int)-2146368435L; }

    public static int COMADMIN_E_EVENTCLASS_CANT_BE_SUBSCRIBER() { return (int)-2146368434L; }

    public static int COMADMIN_E_LIB_APP_PROXY_INCOMPATIBLE() { return (int)-2146368433L; }

    public static int COMADMIN_E_BASE_PARTITION_ONLY() { return (int)-2146368432L; }

    public static int COMADMIN_E_START_APP_DISABLED() { return (int)-2146368431L; }

    public static int COMADMIN_E_CAT_DUPLICATE_PARTITION_NAME() { return (int)-2146368425L; }

    public static int COMADMIN_E_CAT_INVALID_PARTITION_NAME() { return (int)-2146368424L; }

    public static int COMADMIN_E_CAT_PARTITION_IN_USE() { return (int)-2146368423L; }

    public static int COMADMIN_E_FILE_PARTITION_DUPLICATE_FILES() { return (int)-2146368422L; }

    public static int COMADMIN_E_CAT_IMPORTED_COMPONENTS_NOT_ALLOWED() { return (int)-2146368421L; }

    public static int COMADMIN_E_AMBIGUOUS_APPLICATION_NAME() { return (int)-2146368420L; }

    public static int COMADMIN_E_AMBIGUOUS_PARTITION_NAME() { return (int)-2146368419L; }

    public static int COMADMIN_E_REGDB_NOTINITIALIZED() { return (int)-2146368398L; }

    public static int COMADMIN_E_REGDB_NOTOPEN() { return (int)-2146368397L; }

    public static int COMADMIN_E_REGDB_SYSTEMERR() { return (int)-2146368396L; }

    public static int COMADMIN_E_REGDB_ALREADYRUNNING() { return (int)-2146368395L; }

    public static int COMADMIN_E_MIG_VERSIONNOTSUPPORTED() { return (int)-2146368384L; }

    public static int COMADMIN_E_MIG_SCHEMANOTFOUND() { return (int)-2146368383L; }

    public static int COMADMIN_E_CAT_BITNESSMISMATCH() { return (int)-2146368382L; }

    public static int COMADMIN_E_CAT_UNACCEPTABLEBITNESS() { return (int)-2146368381L; }

    public static int COMADMIN_E_CAT_WRONGAPPBITNESS() { return (int)-2146368380L; }

    public static int COMADMIN_E_CAT_PAUSE_RESUME_NOT_SUPPORTED() { return (int)-2146368379L; }

    public static int COMADMIN_E_CAT_SERVERFAULT() { return (int)-2146368378L; }

    public static int COMQC_E_APPLICATION_NOT_QUEUED() { return (int)-2146368000L; }

    public static int COMQC_E_NO_QUEUEABLE_INTERFACES() { return (int)-2146367999L; }

    public static int COMQC_E_QUEUING_SERVICE_NOT_AVAILABLE() { return (int)-2146367998L; }

    public static int COMQC_E_NO_IPERSISTSTREAM() { return (int)-2146367997L; }

    public static int COMQC_E_BAD_MESSAGE() { return (int)-2146367996L; }

    public static int COMQC_E_UNAUTHENTICATED() { return (int)-2146367995L; }

    public static int COMQC_E_UNTRUSTED_ENQUEUER() { return (int)-2146367994L; }

    public static int MSDTC_E_DUPLICATE_RESOURCE() { return (int)-2146367743L; }

    public static int COMADMIN_E_OBJECT_PARENT_MISSING() { return (int)-2146367480L; }

    public static int COMADMIN_E_OBJECT_DOES_NOT_EXIST() { return (int)-2146367479L; }

    public static int COMADMIN_E_APP_NOT_RUNNING() { return (int)-2146367478L; }

    public static int COMADMIN_E_INVALID_PARTITION() { return (int)-2146367477L; }

    public static int COMADMIN_E_SVCAPP_NOT_POOLABLE_OR_RECYCLABLE() { return (int)-2146367475L; }

    public static int COMADMIN_E_USER_IN_SET() { return (int)-2146367474L; }

    public static int COMADMIN_E_CANTRECYCLELIBRARYAPPS() { return (int)-2146367473L; }

    public static int COMADMIN_E_CANTRECYCLESERVICEAPPS() { return (int)-2146367471L; }

    public static int COMADMIN_E_PROCESSALREADYRECYCLED() { return (int)-2146367470L; }

    public static int COMADMIN_E_PAUSEDPROCESSMAYNOTBERECYCLED() { return (int)-2146367469L; }

    public static int COMADMIN_E_CANTMAKEINPROCSERVICE() { return (int)-2146367468L; }

    public static int COMADMIN_E_PROGIDINUSEBYCLSID() { return (int)-2146367467L; }

    public static int COMADMIN_E_DEFAULT_PARTITION_NOT_IN_SET() { return (int)-2146367466L; }

    public static int COMADMIN_E_RECYCLEDPROCESSMAYNOTBEPAUSED() { return (int)-2146367465L; }

    public static int COMADMIN_E_PARTITION_ACCESSDENIED() { return (int)-2146367464L; }

    public static int COMADMIN_E_PARTITION_MSI_ONLY() { return (int)-2146367463L; }

    public static int COMADMIN_E_LEGACYCOMPS_NOT_ALLOWED_IN_1_0_FORMAT() { return (int)-2146367462L; }

    public static int COMADMIN_E_LEGACYCOMPS_NOT_ALLOWED_IN_NONBASE_PARTITIONS() { return (int)-2146367461L; }

    public static int COMADMIN_E_COMP_MOVE_SOURCE() { return (int)-2146367460L; }

    public static int COMADMIN_E_COMP_MOVE_DEST() { return (int)-2146367459L; }

    public static int COMADMIN_E_COMP_MOVE_PRIVATE() { return (int)-2146367458L; }

    public static int COMADMIN_E_BASEPARTITION_REQUIRED_IN_SET() { return (int)-2146367457L; }

    public static int COMADMIN_E_CANNOT_ALIAS_EVENTCLASS() { return (int)-2146367456L; }

    public static int COMADMIN_E_PRIVATE_ACCESSDENIED() { return (int)-2146367455L; }

    public static int COMADMIN_E_SAFERINVALID() { return (int)-2146367454L; }

    public static int COMADMIN_E_REGISTRY_ACCESSDENIED() { return (int)-2146367453L; }

    public static int COMADMIN_E_PARTITIONS_DISABLED() { return (int)-2146367452L; }

    public static int WER_S_REPORT_DEBUG() { return (int)1769472L; }

    public static int WER_S_REPORT_UPLOADED() { return (int)1769473L; }

    public static int WER_S_REPORT_QUEUED() { return (int)1769474L; }

    public static int WER_S_DISABLED() { return (int)1769475L; }

    public static int WER_S_SUSPENDED_UPLOAD() { return (int)1769476L; }

    public static int WER_S_DISABLED_QUEUE() { return (int)1769477L; }

    public static int WER_S_DISABLED_ARCHIVE() { return (int)1769478L; }

    public static int WER_S_REPORT_ASYNC() { return (int)1769479L; }

    public static int WER_S_IGNORE_ASSERT_INSTANCE() { return (int)1769480L; }

    public static int WER_S_IGNORE_ALL_ASSERTS() { return (int)1769481L; }

    public static int WER_S_ASSERT_CONTINUE() { return (int)1769482L; }

    public static int WER_S_THROTTLED() { return (int)1769483L; }

    public static int WER_S_REPORT_UPLOADED_CAB() { return (int)1769484L; }

    public static int WER_E_CRASH_FAILURE() { return (int)-2145681408L; }

    public static int WER_E_CANCELED() { return (int)-2145681407L; }

    public static int WER_E_NETWORK_FAILURE() { return (int)-2145681406L; }

    public static int WER_E_NOT_INITIALIZED() { return (int)-2145681405L; }

    public static int WER_E_ALREADY_REPORTING() { return (int)-2145681404L; }

    public static int WER_E_DUMP_THROTTLED() { return (int)-2145681403L; }

    public static int WER_E_INSUFFICIENT_CONSENT() { return (int)-2145681402L; }

    public static int WER_E_TOO_HEAVY() { return (int)-2145681401L; }

    public static int ERROR_FLT_IO_COMPLETE() { return (int)2031617L; }

    public static int ERROR_FLT_NO_HANDLER_DEFINED() { return (int)-2145452031L; }

    public static int ERROR_FLT_CONTEXT_ALREADY_DEFINED() { return (int)-2145452030L; }

    public static int ERROR_FLT_INVALID_ASYNCHRONOUS_REQUEST() { return (int)-2145452029L; }

    public static int ERROR_FLT_DISALLOW_FAST_IO() { return (int)-2145452028L; }

    public static int ERROR_FLT_INVALID_NAME_REQUEST() { return (int)-2145452027L; }

    public static int ERROR_FLT_NOT_SAFE_TO_POST_OPERATION() { return (int)-2145452026L; }

    public static int ERROR_FLT_NOT_INITIALIZED() { return (int)-2145452025L; }

    public static int ERROR_FLT_FILTER_NOT_READY() { return (int)-2145452024L; }

    public static int ERROR_FLT_POST_OPERATION_CLEANUP() { return (int)-2145452023L; }

    public static int ERROR_FLT_INTERNAL_ERROR() { return (int)-2145452022L; }

    public static int ERROR_FLT_DELETING_OBJECT() { return (int)-2145452021L; }

    public static int ERROR_FLT_MUST_BE_NONPAGED_POOL() { return (int)-2145452020L; }

    public static int ERROR_FLT_DUPLICATE_ENTRY() { return (int)-2145452019L; }

    public static int ERROR_FLT_CBDQ_DISABLED() { return (int)-2145452018L; }

    public static int ERROR_FLT_DO_NOT_ATTACH() { return (int)-2145452017L; }

    public static int ERROR_FLT_DO_NOT_DETACH() { return (int)-2145452016L; }

    public static int ERROR_FLT_INSTANCE_ALTITUDE_COLLISION() { return (int)-2145452015L; }

    public static int ERROR_FLT_INSTANCE_NAME_COLLISION() { return (int)-2145452014L; }

    public static int ERROR_FLT_FILTER_NOT_FOUND() { return (int)-2145452013L; }

    public static int ERROR_FLT_VOLUME_NOT_FOUND() { return (int)-2145452012L; }

    public static int ERROR_FLT_INSTANCE_NOT_FOUND() { return (int)-2145452011L; }

    public static int ERROR_FLT_CONTEXT_ALLOCATION_NOT_FOUND() { return (int)-2145452010L; }

    public static int ERROR_FLT_INVALID_CONTEXT_REGISTRATION() { return (int)-2145452009L; }

    public static int ERROR_FLT_NAME_CACHE_MISS() { return (int)-2145452008L; }

    public static int ERROR_FLT_NO_DEVICE_OBJECT() { return (int)-2145452007L; }

    public static int ERROR_FLT_VOLUME_ALREADY_MOUNTED() { return (int)-2145452006L; }

    public static int ERROR_FLT_ALREADY_ENLISTED() { return (int)-2145452005L; }

    public static int ERROR_FLT_CONTEXT_ALREADY_LINKED() { return (int)-2145452004L; }

    public static int ERROR_FLT_NO_WAITER_FOR_REPLY() { return (int)-2145452000L; }

    public static int ERROR_FLT_REGISTRATION_BUSY() { return (int)-2145451997L; }

    public static int ERROR_HUNG_DISPLAY_DRIVER_THREAD() { return (int)-2144993279L; }

    public static int DWM_E_COMPOSITIONDISABLED() { return (int)-2144980991L; }

    public static int DWM_E_REMOTING_NOT_SUPPORTED() { return (int)-2144980990L; }

    public static int DWM_E_NO_REDIRECTION_SURFACE_AVAILABLE() { return (int)-2144980989L; }

    public static int DWM_E_NOT_QUEUING_PRESENTS() { return (int)-2144980988L; }

    public static int DWM_E_ADAPTER_NOT_FOUND() { return (int)-2144980987L; }

    public static int DWM_S_GDI_REDIRECTION_SURFACE() { return (int)2502661L; }

    public static int DWM_E_TEXTURE_TOO_LARGE() { return (int)-2144980985L; }

    public static int DWM_S_GDI_REDIRECTION_SURFACE_BLT_VIA_GDI() { return (int)2502664L; }

    public static int ERROR_MONITOR_NO_DESCRIPTOR() { return (int)2494465L; }

    public static int ERROR_MONITOR_UNKNOWN_DESCRIPTOR_FORMAT() { return (int)2494466L; }

    public static int ERROR_MONITOR_INVALID_DESCRIPTOR_CHECKSUM() { return (int)-1071247357L; }

    public static int ERROR_MONITOR_INVALID_STANDARD_TIMING_BLOCK() { return (int)-1071247356L; }

    public static int ERROR_MONITOR_WMI_DATABLOCK_REGISTRATION_FAILED() { return (int)-1071247355L; }

    public static int ERROR_MONITOR_INVALID_SERIAL_NUMBER_MONDSC_BLOCK() { return (int)-1071247354L; }

    public static int ERROR_MONITOR_INVALID_USER_FRIENDLY_MONDSC_BLOCK() { return (int)-1071247353L; }

    public static int ERROR_MONITOR_NO_MORE_DESCRIPTOR_DATA() { return (int)-1071247352L; }

    public static int ERROR_MONITOR_INVALID_DETAILED_TIMING_BLOCK() { return (int)-1071247351L; }

    public static int ERROR_MONITOR_INVALID_MANUFACTURE_DATE() { return (int)-1071247350L; }

    public static int ERROR_GRAPHICS_NOT_EXCLUSIVE_MODE_OWNER() { return (int)-1071243264L; }

    public static int ERROR_GRAPHICS_INSUFFICIENT_DMA_BUFFER() { return (int)-1071243263L; }

    public static int ERROR_GRAPHICS_INVALID_DISPLAY_ADAPTER() { return (int)-1071243262L; }

    public static int ERROR_GRAPHICS_ADAPTER_WAS_RESET() { return (int)-1071243261L; }

    public static int ERROR_GRAPHICS_INVALID_DRIVER_MODEL() { return (int)-1071243260L; }

    public static int ERROR_GRAPHICS_PRESENT_MODE_CHANGED() { return (int)-1071243259L; }

    public static int ERROR_GRAPHICS_PRESENT_OCCLUDED() { return (int)-1071243258L; }

    public static int ERROR_GRAPHICS_PRESENT_DENIED() { return (int)-1071243257L; }

    public static int ERROR_GRAPHICS_CANNOTCOLORCONVERT() { return (int)-1071243256L; }

    public static int ERROR_GRAPHICS_DRIVER_MISMATCH() { return (int)-1071243255L; }

    public static int ERROR_GRAPHICS_PARTIAL_DATA_POPULATED() { return (int)1076240394L; }

    public static int ERROR_GRAPHICS_PRESENT_REDIRECTION_DISABLED() { return (int)-1071243253L; }

    public static int ERROR_GRAPHICS_PRESENT_UNOCCLUDED() { return (int)-1071243252L; }

    public static int ERROR_GRAPHICS_WINDOWDC_NOT_AVAILABLE() { return (int)-1071243251L; }

    public static int ERROR_GRAPHICS_WINDOWLESS_PRESENT_DISABLED() { return (int)-1071243250L; }

    public static int ERROR_GRAPHICS_PRESENT_INVALID_WINDOW() { return (int)-1071243249L; }

    public static int ERROR_GRAPHICS_PRESENT_BUFFER_NOT_BOUND() { return (int)-1071243248L; }

    public static int ERROR_GRAPHICS_VAIL_STATE_CHANGED() { return (int)-1071243247L; }

    public static int ERROR_GRAPHICS_INDIRECT_DISPLAY_ABANDON_SWAPCHAIN() { return (int)-1071243246L; }

    public static int ERROR_GRAPHICS_INDIRECT_DISPLAY_DEVICE_STOPPED() { return (int)-1071243245L; }

    public static int ERROR_GRAPHICS_VAIL_FAILED_TO_SEND_CREATE_SUPERWETINK_MESSAGE() { return (int)-1071243244L; }

    public static int ERROR_GRAPHICS_VAIL_FAILED_TO_SEND_DESTROY_SUPERWETINK_MESSAGE() { return (int)-1071243243L; }

    public static int ERROR_GRAPHICS_NO_VIDEO_MEMORY() { return (int)-1071243008L; }

    public static int ERROR_GRAPHICS_CANT_LOCK_MEMORY() { return (int)-1071243007L; }

    public static int ERROR_GRAPHICS_ALLOCATION_BUSY() { return (int)-1071243006L; }

    public static int ERROR_GRAPHICS_TOO_MANY_REFERENCES() { return (int)-1071243005L; }

    public static int ERROR_GRAPHICS_TRY_AGAIN_LATER() { return (int)-1071243004L; }

    public static int ERROR_GRAPHICS_TRY_AGAIN_NOW() { return (int)-1071243003L; }

    public static int ERROR_GRAPHICS_ALLOCATION_INVALID() { return (int)-1071243002L; }

    public static int ERROR_GRAPHICS_UNSWIZZLING_APERTURE_UNAVAILABLE() { return (int)-1071243001L; }

    public static int ERROR_GRAPHICS_UNSWIZZLING_APERTURE_UNSUPPORTED() { return (int)-1071243000L; }

    public static int ERROR_GRAPHICS_CANT_EVICT_PINNED_ALLOCATION() { return (int)-1071242999L; }

    public static int ERROR_GRAPHICS_INVALID_ALLOCATION_USAGE() { return (int)-1071242992L; }

    public static int ERROR_GRAPHICS_CANT_RENDER_LOCKED_ALLOCATION() { return (int)-1071242991L; }

    public static int ERROR_GRAPHICS_ALLOCATION_CLOSED() { return (int)-1071242990L; }

    public static int ERROR_GRAPHICS_INVALID_ALLOCATION_INSTANCE() { return (int)-1071242989L; }

    public static int ERROR_GRAPHICS_INVALID_ALLOCATION_HANDLE() { return (int)-1071242988L; }

    public static int ERROR_GRAPHICS_WRONG_ALLOCATION_DEVICE() { return (int)-1071242987L; }

    public static int ERROR_GRAPHICS_ALLOCATION_CONTENT_LOST() { return (int)-1071242986L; }

    public static int ERROR_GRAPHICS_GPU_EXCEPTION_ON_DEVICE() { return (int)-1071242752L; }

    public static int ERROR_GRAPHICS_SKIP_ALLOCATION_PREPARATION() { return (int)1076240897L; }

    public static int ERROR_GRAPHICS_INVALID_VIDPN_TOPOLOGY() { return (int)-1071242496L; }

    public static int ERROR_GRAPHICS_VIDPN_TOPOLOGY_NOT_SUPPORTED() { return (int)-1071242495L; }

    public static int ERROR_GRAPHICS_VIDPN_TOPOLOGY_CURRENTLY_NOT_SUPPORTED() { return (int)-1071242494L; }

    public static int ERROR_GRAPHICS_INVALID_VIDPN() { return (int)-1071242493L; }

    public static int ERROR_GRAPHICS_INVALID_VIDEO_PRESENT_SOURCE() { return (int)-1071242492L; }

    public static int ERROR_GRAPHICS_INVALID_VIDEO_PRESENT_TARGET() { return (int)-1071242491L; }

    public static int ERROR_GRAPHICS_VIDPN_MODALITY_NOT_SUPPORTED() { return (int)-1071242490L; }

    public static int ERROR_GRAPHICS_MODE_NOT_PINNED() { return (int)2499335L; }

    public static int ERROR_GRAPHICS_INVALID_VIDPN_SOURCEMODESET() { return (int)-1071242488L; }

    public static int ERROR_GRAPHICS_INVALID_VIDPN_TARGETMODESET() { return (int)-1071242487L; }

    public static int ERROR_GRAPHICS_INVALID_FREQUENCY() { return (int)-1071242486L; }

    public static int ERROR_GRAPHICS_INVALID_ACTIVE_REGION() { return (int)-1071242485L; }

    public static int ERROR_GRAPHICS_INVALID_TOTAL_REGION() { return (int)-1071242484L; }

    public static int ERROR_GRAPHICS_INVALID_VIDEO_PRESENT_SOURCE_MODE() { return (int)-1071242480L; }

    public static int ERROR_GRAPHICS_INVALID_VIDEO_PRESENT_TARGET_MODE() { return (int)-1071242479L; }

    public static int ERROR_GRAPHICS_PINNED_MODE_MUST_REMAIN_IN_SET() { return (int)-1071242478L; }

    public static int ERROR_GRAPHICS_PATH_ALREADY_IN_TOPOLOGY() { return (int)-1071242477L; }

    public static int ERROR_GRAPHICS_MODE_ALREADY_IN_MODESET() { return (int)-1071242476L; }

    public static int ERROR_GRAPHICS_INVALID_VIDEOPRESENTSOURCESET() { return (int)-1071242475L; }

    public static int ERROR_GRAPHICS_INVALID_VIDEOPRESENTTARGETSET() { return (int)-1071242474L; }

    public static int ERROR_GRAPHICS_SOURCE_ALREADY_IN_SET() { return (int)-1071242473L; }

    public static int ERROR_GRAPHICS_TARGET_ALREADY_IN_SET() { return (int)-1071242472L; }

    public static int ERROR_GRAPHICS_INVALID_VIDPN_PRESENT_PATH() { return (int)-1071242471L; }

    public static int ERROR_GRAPHICS_NO_RECOMMENDED_VIDPN_TOPOLOGY() { return (int)-1071242470L; }

    public static int ERROR_GRAPHICS_INVALID_MONITOR_FREQUENCYRANGESET() { return (int)-1071242469L; }

    public static int ERROR_GRAPHICS_INVALID_MONITOR_FREQUENCYRANGE() { return (int)-1071242468L; }

    public static int ERROR_GRAPHICS_FREQUENCYRANGE_NOT_IN_SET() { return (int)-1071242467L; }

    public static int ERROR_GRAPHICS_NO_PREFERRED_MODE() { return (int)2499358L; }

    public static int ERROR_GRAPHICS_FREQUENCYRANGE_ALREADY_IN_SET() { return (int)-1071242465L; }

    public static int ERROR_GRAPHICS_STALE_MODESET() { return (int)-1071242464L; }

    public static int ERROR_GRAPHICS_INVALID_MONITOR_SOURCEMODESET() { return (int)-1071242463L; }

    public static int ERROR_GRAPHICS_INVALID_MONITOR_SOURCE_MODE() { return (int)-1071242462L; }

    public static int ERROR_GRAPHICS_NO_RECOMMENDED_FUNCTIONAL_VIDPN() { return (int)-1071242461L; }

    public static int ERROR_GRAPHICS_MODE_ID_MUST_BE_UNIQUE() { return (int)-1071242460L; }

    public static int ERROR_GRAPHICS_EMPTY_ADAPTER_MONITOR_MODE_SUPPORT_INTERSECTION() { return (int)-1071242459L; }

    public static int ERROR_GRAPHICS_VIDEO_PRESENT_TARGETS_LESS_THAN_SOURCES() { return (int)-1071242458L; }

    public static int ERROR_GRAPHICS_PATH_NOT_IN_TOPOLOGY() { return (int)-1071242457L; }

    public static int ERROR_GRAPHICS_ADAPTER_MUST_HAVE_AT_LEAST_ONE_SOURCE() { return (int)-1071242456L; }

    public static int ERROR_GRAPHICS_ADAPTER_MUST_HAVE_AT_LEAST_ONE_TARGET() { return (int)-1071242455L; }

    public static int ERROR_GRAPHICS_INVALID_MONITORDESCRIPTORSET() { return (int)-1071242454L; }

    public static int ERROR_GRAPHICS_INVALID_MONITORDESCRIPTOR() { return (int)-1071242453L; }

    public static int ERROR_GRAPHICS_MONITORDESCRIPTOR_NOT_IN_SET() { return (int)-1071242452L; }

    public static int ERROR_GRAPHICS_MONITORDESCRIPTOR_ALREADY_IN_SET() { return (int)-1071242451L; }

    public static int ERROR_GRAPHICS_MONITORDESCRIPTOR_ID_MUST_BE_UNIQUE() { return (int)-1071242450L; }

    public static int ERROR_GRAPHICS_INVALID_VIDPN_TARGET_SUBSET_TYPE() { return (int)-1071242449L; }

    public static int ERROR_GRAPHICS_RESOURCES_NOT_RELATED() { return (int)-1071242448L; }

    public static int ERROR_GRAPHICS_SOURCE_ID_MUST_BE_UNIQUE() { return (int)-1071242447L; }

    public static int ERROR_GRAPHICS_TARGET_ID_MUST_BE_UNIQUE() { return (int)-1071242446L; }

    public static int ERROR_GRAPHICS_NO_AVAILABLE_VIDPN_TARGET() { return (int)-1071242445L; }

    public static int ERROR_GRAPHICS_MONITOR_COULD_NOT_BE_ASSOCIATED_WITH_ADAPTER() { return (int)-1071242444L; }

    public static int ERROR_GRAPHICS_NO_VIDPNMGR() { return (int)-1071242443L; }

    public static int ERROR_GRAPHICS_NO_ACTIVE_VIDPN() { return (int)-1071242442L; }

    public static int ERROR_GRAPHICS_STALE_VIDPN_TOPOLOGY() { return (int)-1071242441L; }

    public static int ERROR_GRAPHICS_MONITOR_NOT_CONNECTED() { return (int)-1071242440L; }

    public static int ERROR_GRAPHICS_SOURCE_NOT_IN_TOPOLOGY() { return (int)-1071242439L; }

    public static int ERROR_GRAPHICS_INVALID_PRIMARYSURFACE_SIZE() { return (int)-1071242438L; }

    public static int ERROR_GRAPHICS_INVALID_VISIBLEREGION_SIZE() { return (int)-1071242437L; }

    public static int ERROR_GRAPHICS_INVALID_STRIDE() { return (int)-1071242436L; }

    public static int ERROR_GRAPHICS_INVALID_PIXELFORMAT() { return (int)-1071242435L; }

    public static int ERROR_GRAPHICS_INVALID_COLORBASIS() { return (int)-1071242434L; }

    public static int ERROR_GRAPHICS_INVALID_PIXELVALUEACCESSMODE() { return (int)-1071242433L; }

    public static int ERROR_GRAPHICS_TARGET_NOT_IN_TOPOLOGY() { return (int)-1071242432L; }

    public static int ERROR_GRAPHICS_NO_DISPLAY_MODE_MANAGEMENT_SUPPORT() { return (int)-1071242431L; }

    public static int ERROR_GRAPHICS_VIDPN_SOURCE_IN_USE() { return (int)-1071242430L; }

    public static int ERROR_GRAPHICS_CANT_ACCESS_ACTIVE_VIDPN() { return (int)-1071242429L; }

    public static int ERROR_GRAPHICS_INVALID_PATH_IMPORTANCE_ORDINAL() { return (int)-1071242428L; }

    public static int ERROR_GRAPHICS_INVALID_PATH_CONTENT_GEOMETRY_TRANSFORMATION() { return (int)-1071242427L; }

    public static int ERROR_GRAPHICS_PATH_CONTENT_GEOMETRY_TRANSFORMATION_NOT_SUPPORTED() { return (int)-1071242426L; }

    public static int ERROR_GRAPHICS_INVALID_GAMMA_RAMP() { return (int)-1071242425L; }

    public static int ERROR_GRAPHICS_GAMMA_RAMP_NOT_SUPPORTED() { return (int)-1071242424L; }

    public static int ERROR_GRAPHICS_MULTISAMPLING_NOT_SUPPORTED() { return (int)-1071242423L; }

    public static int ERROR_GRAPHICS_MODE_NOT_IN_MODESET() { return (int)-1071242422L; }

    public static int ERROR_GRAPHICS_DATASET_IS_EMPTY() { return (int)2499403L; }

    public static int ERROR_GRAPHICS_NO_MORE_ELEMENTS_IN_DATASET() { return (int)2499404L; }

    public static int ERROR_GRAPHICS_INVALID_VIDPN_TOPOLOGY_RECOMMENDATION_REASON() { return (int)-1071242419L; }

    public static int ERROR_GRAPHICS_INVALID_PATH_CONTENT_TYPE() { return (int)-1071242418L; }

    public static int ERROR_GRAPHICS_INVALID_COPYPROTECTION_TYPE() { return (int)-1071242417L; }

    public static int ERROR_GRAPHICS_UNASSIGNED_MODESET_ALREADY_EXISTS() { return (int)-1071242416L; }

    public static int ERROR_GRAPHICS_PATH_CONTENT_GEOMETRY_TRANSFORMATION_NOT_PINNED() { return (int)2499409L; }

    public static int ERROR_GRAPHICS_INVALID_SCANLINE_ORDERING() { return (int)-1071242414L; }

    public static int ERROR_GRAPHICS_TOPOLOGY_CHANGES_NOT_ALLOWED() { return (int)-1071242413L; }

    public static int ERROR_GRAPHICS_NO_AVAILABLE_IMPORTANCE_ORDINALS() { return (int)-1071242412L; }

    public static int ERROR_GRAPHICS_INCOMPATIBLE_PRIVATE_FORMAT() { return (int)-1071242411L; }

    public static int ERROR_GRAPHICS_INVALID_MODE_PRUNING_ALGORITHM() { return (int)-1071242410L; }

    public static int ERROR_GRAPHICS_INVALID_MONITOR_CAPABILITY_ORIGIN() { return (int)-1071242409L; }

    public static int ERROR_GRAPHICS_INVALID_MONITOR_FREQUENCYRANGE_CONSTRAINT() { return (int)-1071242408L; }

    public static int ERROR_GRAPHICS_MAX_NUM_PATHS_REACHED() { return (int)-1071242407L; }

    public static int ERROR_GRAPHICS_CANCEL_VIDPN_TOPOLOGY_AUGMENTATION() { return (int)-1071242406L; }

    public static int ERROR_GRAPHICS_INVALID_CLIENT_TYPE() { return (int)-1071242405L; }

    public static int ERROR_GRAPHICS_CLIENTVIDPN_NOT_SET() { return (int)-1071242404L; }

    public static int ERROR_GRAPHICS_SPECIFIED_CHILD_ALREADY_CONNECTED() { return (int)-1071242240L; }

    public static int ERROR_GRAPHICS_CHILD_DESCRIPTOR_NOT_SUPPORTED() { return (int)-1071242239L; }

    public static int ERROR_GRAPHICS_UNKNOWN_CHILD_STATUS() { return (int)1076241455L; }

    public static int ERROR_GRAPHICS_NOT_A_LINKED_ADAPTER() { return (int)-1071242192L; }

    public static int ERROR_GRAPHICS_LEADLINK_NOT_ENUMERATED() { return (int)-1071242191L; }

    public static int ERROR_GRAPHICS_CHAINLINKS_NOT_ENUMERATED() { return (int)-1071242190L; }

    public static int ERROR_GRAPHICS_ADAPTER_CHAIN_NOT_READY() { return (int)-1071242189L; }

    public static int ERROR_GRAPHICS_CHAINLINKS_NOT_STARTED() { return (int)-1071242188L; }

    public static int ERROR_GRAPHICS_CHAINLINKS_NOT_POWERED_ON() { return (int)-1071242187L; }

    public static int ERROR_GRAPHICS_INCONSISTENT_DEVICE_LINK_STATE() { return (int)-1071242186L; }

    public static int ERROR_GRAPHICS_LEADLINK_START_DEFERRED() { return (int)1076241463L; }

    public static int ERROR_GRAPHICS_NOT_POST_DEVICE_DRIVER() { return (int)-1071242184L; }

    public static int ERROR_GRAPHICS_POLLING_TOO_FREQUENTLY() { return (int)1076241465L; }

    public static int ERROR_GRAPHICS_START_DEFERRED() { return (int)1076241466L; }

    public static int ERROR_GRAPHICS_ADAPTER_ACCESS_NOT_EXCLUDED() { return (int)-1071242181L; }

    public static int ERROR_GRAPHICS_DEPENDABLE_CHILD_STATUS() { return (int)1076241468L; }

    public static int ERROR_GRAPHICS_OPM_NOT_SUPPORTED() { return (int)-1071241984L; }

    public static int ERROR_GRAPHICS_COPP_NOT_SUPPORTED() { return (int)-1071241983L; }

    public static int ERROR_GRAPHICS_UAB_NOT_SUPPORTED() { return (int)-1071241982L; }

    public static int ERROR_GRAPHICS_OPM_INVALID_ENCRYPTED_PARAMETERS() { return (int)-1071241981L; }

    public static int ERROR_GRAPHICS_OPM_NO_VIDEO_OUTPUTS_EXIST() { return (int)-1071241979L; }

    public static int ERROR_GRAPHICS_OPM_INTERNAL_ERROR() { return (int)-1071241973L; }

    public static int ERROR_GRAPHICS_OPM_INVALID_HANDLE() { return (int)-1071241972L; }

    public static int ERROR_GRAPHICS_PVP_INVALID_CERTIFICATE_LENGTH() { return (int)-1071241970L; }

    public static int ERROR_GRAPHICS_OPM_SPANNING_MODE_ENABLED() { return (int)-1071241969L; }

    public static int ERROR_GRAPHICS_OPM_THEATER_MODE_ENABLED() { return (int)-1071241968L; }

    public static int ERROR_GRAPHICS_PVP_HFS_FAILED() { return (int)-1071241967L; }

    public static int ERROR_GRAPHICS_OPM_INVALID_SRM() { return (int)-1071241966L; }

    public static int ERROR_GRAPHICS_OPM_OUTPUT_DOES_NOT_SUPPORT_HDCP() { return (int)-1071241965L; }

    public static int ERROR_GRAPHICS_OPM_OUTPUT_DOES_NOT_SUPPORT_ACP() { return (int)-1071241964L; }

    public static int ERROR_GRAPHICS_OPM_OUTPUT_DOES_NOT_SUPPORT_CGMSA() { return (int)-1071241963L; }

    public static int ERROR_GRAPHICS_OPM_HDCP_SRM_NEVER_SET() { return (int)-1071241962L; }

    public static int ERROR_GRAPHICS_OPM_RESOLUTION_TOO_HIGH() { return (int)-1071241961L; }

    public static int ERROR_GRAPHICS_OPM_ALL_HDCP_HARDWARE_ALREADY_IN_USE() { return (int)-1071241960L; }

    public static int ERROR_GRAPHICS_OPM_VIDEO_OUTPUT_NO_LONGER_EXISTS() { return (int)-1071241958L; }

    public static int ERROR_GRAPHICS_OPM_SESSION_TYPE_CHANGE_IN_PROGRESS() { return (int)-1071241957L; }

    public static int ERROR_GRAPHICS_OPM_VIDEO_OUTPUT_DOES_NOT_HAVE_COPP_SEMANTICS() { return (int)-1071241956L; }

    public static int ERROR_GRAPHICS_OPM_INVALID_INFORMATION_REQUEST() { return (int)-1071241955L; }

    public static int ERROR_GRAPHICS_OPM_DRIVER_INTERNAL_ERROR() { return (int)-1071241954L; }

    public static int ERROR_GRAPHICS_OPM_VIDEO_OUTPUT_DOES_NOT_HAVE_OPM_SEMANTICS() { return (int)-1071241953L; }

    public static int ERROR_GRAPHICS_OPM_SIGNALING_NOT_SUPPORTED() { return (int)-1071241952L; }

    public static int ERROR_GRAPHICS_OPM_INVALID_CONFIGURATION_REQUEST() { return (int)-1071241951L; }

    public static int ERROR_GRAPHICS_I2C_NOT_SUPPORTED() { return (int)-1071241856L; }

    public static int ERROR_GRAPHICS_I2C_DEVICE_DOES_NOT_EXIST() { return (int)-1071241855L; }

    public static int ERROR_GRAPHICS_I2C_ERROR_TRANSMITTING_DATA() { return (int)-1071241854L; }

    public static int ERROR_GRAPHICS_I2C_ERROR_RECEIVING_DATA() { return (int)-1071241853L; }

    public static int ERROR_GRAPHICS_DDCCI_VCP_NOT_SUPPORTED() { return (int)-1071241852L; }

    public static int ERROR_GRAPHICS_DDCCI_INVALID_DATA() { return (int)-1071241851L; }

    public static int ERROR_GRAPHICS_DDCCI_MONITOR_RETURNED_INVALID_TIMING_STATUS_BYTE() { return (int)-1071241850L; }

    public static int ERROR_GRAPHICS_MCA_INVALID_CAPABILITIES_STRING() { return (int)-1071241849L; }

    public static int ERROR_GRAPHICS_MCA_INTERNAL_ERROR() { return (int)-1071241848L; }

    public static int ERROR_GRAPHICS_DDCCI_INVALID_MESSAGE_COMMAND() { return (int)-1071241847L; }

    public static int ERROR_GRAPHICS_DDCCI_INVALID_MESSAGE_LENGTH() { return (int)-1071241846L; }

    public static int ERROR_GRAPHICS_DDCCI_INVALID_MESSAGE_CHECKSUM() { return (int)-1071241845L; }

    public static int ERROR_GRAPHICS_INVALID_PHYSICAL_MONITOR_HANDLE() { return (int)-1071241844L; }

    public static int ERROR_GRAPHICS_MONITOR_NO_LONGER_EXISTS() { return (int)-1071241843L; }

    public static int ERROR_GRAPHICS_DDCCI_CURRENT_CURRENT_VALUE_GREATER_THAN_MAXIMUM_VALUE() { return (int)-1071241768L; }

    public static int ERROR_GRAPHICS_MCA_INVALID_VCP_VERSION() { return (int)-1071241767L; }

    public static int ERROR_GRAPHICS_MCA_MONITOR_VIOLATES_MCCS_SPECIFICATION() { return (int)-1071241766L; }

    public static int ERROR_GRAPHICS_MCA_MCCS_VERSION_MISMATCH() { return (int)-1071241765L; }

    public static int ERROR_GRAPHICS_MCA_UNSUPPORTED_MCCS_VERSION() { return (int)-1071241764L; }

    public static int ERROR_GRAPHICS_MCA_INVALID_TECHNOLOGY_TYPE_RETURNED() { return (int)-1071241762L; }

    public static int ERROR_GRAPHICS_MCA_UNSUPPORTED_COLOR_TEMPERATURE() { return (int)-1071241761L; }

    public static int ERROR_GRAPHICS_ONLY_CONSOLE_SESSION_SUPPORTED() { return (int)-1071241760L; }

    public static int ERROR_GRAPHICS_NO_DISPLAY_DEVICE_CORRESPONDS_TO_NAME() { return (int)-1071241759L; }

    public static int ERROR_GRAPHICS_DISPLAY_DEVICE_NOT_ATTACHED_TO_DESKTOP() { return (int)-1071241758L; }

    public static int ERROR_GRAPHICS_MIRRORING_DEVICES_NOT_SUPPORTED() { return (int)-1071241757L; }

    public static int ERROR_GRAPHICS_INVALID_POINTER() { return (int)-1071241756L; }

    public static int ERROR_GRAPHICS_NO_MONITORS_CORRESPOND_TO_DISPLAY_DEVICE() { return (int)-1071241755L; }

    public static int ERROR_GRAPHICS_PARAMETER_ARRAY_TOO_SMALL() { return (int)-1071241754L; }

    public static int ERROR_GRAPHICS_INTERNAL_ERROR() { return (int)-1071241753L; }

    public static int ERROR_GRAPHICS_SESSION_TYPE_CHANGE_IN_PROGRESS() { return (int)-1071249944L; }

    public static int NAP_E_INVALID_PACKET() { return (int)-2144927743L; }

    public static int NAP_E_MISSING_SOH() { return (int)-2144927742L; }

    public static int NAP_E_CONFLICTING_ID() { return (int)-2144927741L; }

    public static int NAP_E_NO_CACHED_SOH() { return (int)-2144927740L; }

    public static int NAP_E_STILL_BOUND() { return (int)-2144927739L; }

    public static int NAP_E_NOT_REGISTERED() { return (int)-2144927738L; }

    public static int NAP_E_NOT_INITIALIZED() { return (int)-2144927737L; }

    public static int NAP_E_MISMATCHED_ID() { return (int)-2144927736L; }

    public static int NAP_E_NOT_PENDING() { return (int)-2144927735L; }

    public static int NAP_E_ID_NOT_FOUND() { return (int)-2144927734L; }

    public static int NAP_E_MAXSIZE_TOO_SMALL() { return (int)-2144927733L; }

    public static int NAP_E_SERVICE_NOT_RUNNING() { return (int)-2144927732L; }

    public static int NAP_S_CERT_ALREADY_PRESENT() { return (int)2555917L; }

    public static int NAP_E_ENTITY_DISABLED() { return (int)-2144927730L; }

    public static int NAP_E_NETSH_GROUPPOLICY_ERROR() { return (int)-2144927729L; }

    public static int NAP_E_TOO_MANY_CALLS() { return (int)-2144927728L; }

    public static int NAP_E_SHV_CONFIG_EXISTED() { return (int)-2144927727L; }

    public static int NAP_E_SHV_CONFIG_NOT_FOUND() { return (int)-2144927726L; }

    public static int NAP_E_SHV_TIMEOUT() { return (int)-2144927725L; }

    public static int TPM_E_ERROR_MASK() { return (int)-2144862208L; }

    public static int TPM_E_AUTHFAIL() { return (int)-2144862207L; }

    public static int TPM_E_BADINDEX() { return (int)-2144862206L; }

    public static int TPM_E_BAD_PARAMETER() { return (int)-2144862205L; }

    public static int TPM_E_AUDITFAILURE() { return (int)-2144862204L; }

    public static int TPM_E_CLEAR_DISABLED() { return (int)-2144862203L; }

    public static int TPM_E_DEACTIVATED() { return (int)-2144862202L; }

    public static int TPM_E_DISABLED() { return (int)-2144862201L; }

    public static int TPM_E_DISABLED_CMD() { return (int)-2144862200L; }

    public static int TPM_E_FAIL() { return (int)-2144862199L; }

    public static int TPM_E_BAD_ORDINAL() { return (int)-2144862198L; }

    public static int TPM_E_INSTALL_DISABLED() { return (int)-2144862197L; }

    public static int TPM_E_INVALID_KEYHANDLE() { return (int)-2144862196L; }

    public static int TPM_E_KEYNOTFOUND() { return (int)-2144862195L; }

    public static int TPM_E_INAPPROPRIATE_ENC() { return (int)-2144862194L; }

    public static int TPM_E_MIGRATEFAIL() { return (int)-2144862193L; }

    public static int TPM_E_INVALID_PCR_INFO() { return (int)-2144862192L; }

    public static int TPM_E_NOSPACE() { return (int)-2144862191L; }

    public static int TPM_E_NOSRK() { return (int)-2144862190L; }

    public static int TPM_E_NOTSEALED_BLOB() { return (int)-2144862189L; }

    public static int TPM_E_OWNER_SET() { return (int)-2144862188L; }

    public static int TPM_E_RESOURCES() { return (int)-2144862187L; }

    public static int TPM_E_SHORTRANDOM() { return (int)-2144862186L; }

    public static int TPM_E_SIZE() { return (int)-2144862185L; }

    public static int TPM_E_WRONGPCRVAL() { return (int)-2144862184L; }

    public static int TPM_E_BAD_PARAM_SIZE() { return (int)-2144862183L; }

    public static int TPM_E_SHA_THREAD() { return (int)-2144862182L; }

    public static int TPM_E_SHA_ERROR() { return (int)-2144862181L; }

    public static int TPM_E_FAILEDSELFTEST() { return (int)-2144862180L; }

    public static int TPM_E_AUTH2FAIL() { return (int)-2144862179L; }

    public static int TPM_E_BADTAG() { return (int)-2144862178L; }

    public static int TPM_E_IOERROR() { return (int)-2144862177L; }

    public static int TPM_E_ENCRYPT_ERROR() { return (int)-2144862176L; }

    public static int TPM_E_DECRYPT_ERROR() { return (int)-2144862175L; }

    public static int TPM_E_INVALID_AUTHHANDLE() { return (int)-2144862174L; }

    public static int TPM_E_NO_ENDORSEMENT() { return (int)-2144862173L; }

    public static int TPM_E_INVALID_KEYUSAGE() { return (int)-2144862172L; }

    public static int TPM_E_WRONG_ENTITYTYPE() { return (int)-2144862171L; }

    public static int TPM_E_INVALID_POSTINIT() { return (int)-2144862170L; }

    public static int TPM_E_INAPPROPRIATE_SIG() { return (int)-2144862169L; }

    public static int TPM_E_BAD_KEY_PROPERTY() { return (int)-2144862168L; }

    public static int TPM_E_BAD_MIGRATION() { return (int)-2144862167L; }

    public static int TPM_E_BAD_SCHEME() { return (int)-2144862166L; }

    public static int TPM_E_BAD_DATASIZE() { return (int)-2144862165L; }

    public static int TPM_E_BAD_MODE() { return (int)-2144862164L; }

    public static int TPM_E_BAD_PRESENCE() { return (int)-2144862163L; }

    public static int TPM_E_BAD_VERSION() { return (int)-2144862162L; }

    public static int TPM_E_NO_WRAP_TRANSPORT() { return (int)-2144862161L; }

    public static int TPM_E_AUDITFAIL_UNSUCCESSFUL() { return (int)-2144862160L; }

    public static int TPM_E_AUDITFAIL_SUCCESSFUL() { return (int)-2144862159L; }

    public static int TPM_E_NOTRESETABLE() { return (int)-2144862158L; }

    public static int TPM_E_NOTLOCAL() { return (int)-2144862157L; }

    public static int TPM_E_BAD_TYPE() { return (int)-2144862156L; }

    public static int TPM_E_INVALID_RESOURCE() { return (int)-2144862155L; }

    public static int TPM_E_NOTFIPS() { return (int)-2144862154L; }

    public static int TPM_E_INVALID_FAMILY() { return (int)-2144862153L; }

    public static int TPM_E_NO_NV_PERMISSION() { return (int)-2144862152L; }

    public static int TPM_E_REQUIRES_SIGN() { return (int)-2144862151L; }

    public static int TPM_E_KEY_NOTSUPPORTED() { return (int)-2144862150L; }

    public static int TPM_E_AUTH_CONFLICT() { return (int)-2144862149L; }

    public static int TPM_E_AREA_LOCKED() { return (int)-2144862148L; }

    public static int TPM_E_BAD_LOCALITY() { return (int)-2144862147L; }

    public static int TPM_E_READ_ONLY() { return (int)-2144862146L; }

    public static int TPM_E_PER_NOWRITE() { return (int)-2144862145L; }

    public static int TPM_E_FAMILYCOUNT() { return (int)-2144862144L; }

    public static int TPM_E_WRITE_LOCKED() { return (int)-2144862143L; }

    public static int TPM_E_BAD_ATTRIBUTES() { return (int)-2144862142L; }

    public static int TPM_E_INVALID_STRUCTURE() { return (int)-2144862141L; }

    public static int TPM_E_KEY_OWNER_CONTROL() { return (int)-2144862140L; }

    public static int TPM_E_BAD_COUNTER() { return (int)-2144862139L; }

    public static int TPM_E_NOT_FULLWRITE() { return (int)-2144862138L; }

    public static int TPM_E_CONTEXT_GAP() { return (int)-2144862137L; }

    public static int TPM_E_MAXNVWRITES() { return (int)-2144862136L; }

    public static int TPM_E_NOOPERATOR() { return (int)-2144862135L; }

    public static int TPM_E_RESOURCEMISSING() { return (int)-2144862134L; }

    public static int TPM_E_DELEGATE_LOCK() { return (int)-2144862133L; }

    public static int TPM_E_DELEGATE_FAMILY() { return (int)-2144862132L; }

    public static int TPM_E_DELEGATE_ADMIN() { return (int)-2144862131L; }

    public static int TPM_E_TRANSPORT_NOTEXCLUSIVE() { return (int)-2144862130L; }

    public static int TPM_E_OWNER_CONTROL() { return (int)-2144862129L; }

    public static int TPM_E_DAA_RESOURCES() { return (int)-2144862128L; }

    public static int TPM_E_DAA_INPUT_DATA0() { return (int)-2144862127L; }

    public static int TPM_E_DAA_INPUT_DATA1() { return (int)-2144862126L; }

    public static int TPM_E_DAA_ISSUER_SETTINGS() { return (int)-2144862125L; }

    public static int TPM_E_DAA_TPM_SETTINGS() { return (int)-2144862124L; }

    public static int TPM_E_DAA_STAGE() { return (int)-2144862123L; }

    public static int TPM_E_DAA_ISSUER_VALIDITY() { return (int)-2144862122L; }

    public static int TPM_E_DAA_WRONG_W() { return (int)-2144862121L; }

    public static int TPM_E_BAD_HANDLE() { return (int)-2144862120L; }

    public static int TPM_E_BAD_DELEGATE() { return (int)-2144862119L; }

    public static int TPM_E_BADCONTEXT() { return (int)-2144862118L; }

    public static int TPM_E_TOOMANYCONTEXTS() { return (int)-2144862117L; }

    public static int TPM_E_MA_TICKET_SIGNATURE() { return (int)-2144862116L; }

    public static int TPM_E_MA_DESTINATION() { return (int)-2144862115L; }

    public static int TPM_E_MA_SOURCE() { return (int)-2144862114L; }

    public static int TPM_E_MA_AUTHORITY() { return (int)-2144862113L; }

    public static int TPM_E_PERMANENTEK() { return (int)-2144862111L; }

    public static int TPM_E_BAD_SIGNATURE() { return (int)-2144862110L; }

    public static int TPM_E_NOCONTEXTSPACE() { return (int)-2144862109L; }

    public static int TPM_20_E_ASYMMETRIC() { return (int)-2144862079L; }

    public static int TPM_20_E_ATTRIBUTES() { return (int)-2144862078L; }

    public static int TPM_20_E_HASH() { return (int)-2144862077L; }

    public static int TPM_20_E_VALUE() { return (int)-2144862076L; }

    public static int TPM_20_E_HIERARCHY() { return (int)-2144862075L; }

    public static int TPM_20_E_KEY_SIZE() { return (int)-2144862073L; }

    public static int TPM_20_E_MGF() { return (int)-2144862072L; }

    public static int TPM_20_E_MODE() { return (int)-2144862071L; }

    public static int TPM_20_E_TYPE() { return (int)-2144862070L; }

    public static int TPM_20_E_HANDLE() { return (int)-2144862069L; }

    public static int TPM_20_E_KDF() { return (int)-2144862068L; }

    public static int TPM_20_E_RANGE() { return (int)-2144862067L; }

    public static int TPM_20_E_AUTH_FAIL() { return (int)-2144862066L; }

    public static int TPM_20_E_NONCE() { return (int)-2144862065L; }

    public static int TPM_20_E_PP() { return (int)-2144862064L; }

    public static int TPM_20_E_SCHEME() { return (int)-2144862062L; }

    public static int TPM_20_E_SIZE() { return (int)-2144862059L; }

    public static int TPM_20_E_SYMMETRIC() { return (int)-2144862058L; }

    public static int TPM_20_E_TAG() { return (int)-2144862057L; }

    public static int TPM_20_E_SELECTOR() { return (int)-2144862056L; }

    public static int TPM_20_E_INSUFFICIENT() { return (int)-2144862054L; }

    public static int TPM_20_E_SIGNATURE() { return (int)-2144862053L; }

    public static int TPM_20_E_KEY() { return (int)-2144862052L; }

    public static int TPM_20_E_POLICY_FAIL() { return (int)-2144862051L; }

    public static int TPM_20_E_INTEGRITY() { return (int)-2144862049L; }

    public static int TPM_20_E_TICKET() { return (int)-2144862048L; }

    public static int TPM_20_E_RESERVED_BITS() { return (int)-2144862047L; }

    public static int TPM_20_E_BAD_AUTH() { return (int)-2144862046L; }

    public static int TPM_20_E_EXPIRED() { return (int)-2144862045L; }

    public static int TPM_20_E_POLICY_CC() { return (int)-2144862044L; }

    public static int TPM_20_E_BINDING() { return (int)-2144862043L; }

    public static int TPM_20_E_CURVE() { return (int)-2144862042L; }

    public static int TPM_20_E_ECC_POINT() { return (int)-2144862041L; }

    public static int TPM_20_E_INITIALIZE() { return (int)-2144861952L; }

    public static int TPM_20_E_FAILURE() { return (int)-2144861951L; }

    public static int TPM_20_E_SEQUENCE() { return (int)-2144861949L; }

    public static int TPM_20_E_PRIVATE() { return (int)-2144861941L; }

    public static int TPM_20_E_HMAC() { return (int)-2144861927L; }

    public static int TPM_20_E_DISABLED() { return (int)-2144861920L; }

    public static int TPM_20_E_EXCLUSIVE() { return (int)-2144861919L; }

    public static int TPM_20_E_ECC_CURVE() { return (int)-2144861917L; }

    public static int TPM_20_E_AUTH_TYPE() { return (int)-2144861916L; }

    public static int TPM_20_E_AUTH_MISSING() { return (int)-2144861915L; }

    public static int TPM_20_E_POLICY() { return (int)-2144861914L; }

    public static int TPM_20_E_PCR() { return (int)-2144861913L; }

    public static int TPM_20_E_PCR_CHANGED() { return (int)-2144861912L; }

    public static int TPM_20_E_UPGRADE() { return (int)-2144861907L; }

    public static int TPM_20_E_TOO_MANY_CONTEXTS() { return (int)-2144861906L; }

    public static int TPM_20_E_AUTH_UNAVAILABLE() { return (int)-2144861905L; }

    public static int TPM_20_E_REBOOT() { return (int)-2144861904L; }

    public static int TPM_20_E_UNBALANCED() { return (int)-2144861903L; }

    public static int TPM_20_E_COMMAND_SIZE() { return (int)-2144861886L; }

    public static int TPM_20_E_COMMAND_CODE() { return (int)-2144861885L; }

    public static int TPM_20_E_AUTHSIZE() { return (int)-2144861884L; }

    public static int TPM_20_E_AUTH_CONTEXT() { return (int)-2144861883L; }

    public static int TPM_20_E_NV_RANGE() { return (int)-2144861882L; }

    public static int TPM_20_E_NV_SIZE() { return (int)-2144861881L; }

    public static int TPM_20_E_NV_LOCKED() { return (int)-2144861880L; }

    public static int TPM_20_E_NV_AUTHORIZATION() { return (int)-2144861879L; }

    public static int TPM_20_E_NV_UNINITIALIZED() { return (int)-2144861878L; }

    public static int TPM_20_E_NV_SPACE() { return (int)-2144861877L; }

    public static int TPM_20_E_NV_DEFINED() { return (int)-2144861876L; }

    public static int TPM_20_E_BAD_CONTEXT() { return (int)-2144861872L; }

    public static int TPM_20_E_CPHASH() { return (int)-2144861871L; }

    public static int TPM_20_E_PARENT() { return (int)-2144861870L; }

    public static int TPM_20_E_NEEDS_TEST() { return (int)-2144861869L; }

    public static int TPM_20_E_NO_RESULT() { return (int)-2144861868L; }

    public static int TPM_20_E_SENSITIVE() { return (int)-2144861867L; }

    public static int TPM_E_COMMAND_BLOCKED() { return (int)-2144861184L; }

    public static int TPM_E_INVALID_HANDLE() { return (int)-2144861183L; }

    public static int TPM_E_DUPLICATE_VHANDLE() { return (int)-2144861182L; }

    public static int TPM_E_EMBEDDED_COMMAND_BLOCKED() { return (int)-2144861181L; }

    public static int TPM_E_EMBEDDED_COMMAND_UNSUPPORTED() { return (int)-2144861180L; }

    public static int TPM_E_RETRY() { return (int)-2144860160L; }

    public static int TPM_E_NEEDS_SELFTEST() { return (int)-2144860159L; }

    public static int TPM_E_DOING_SELFTEST() { return (int)-2144860158L; }

    public static int TPM_E_DEFEND_LOCK_RUNNING() { return (int)-2144860157L; }

    public static int TPM_20_E_CONTEXT_GAP() { return (int)-2144859903L; }

    public static int TPM_20_E_OBJECT_MEMORY() { return (int)-2144859902L; }

    public static int TPM_20_E_SESSION_MEMORY() { return (int)-2144859901L; }

    public static int TPM_20_E_MEMORY() { return (int)-2144859900L; }

    public static int TPM_20_E_SESSION_HANDLES() { return (int)-2144859899L; }

    public static int TPM_20_E_OBJECT_HANDLES() { return (int)-2144859898L; }

    public static int TPM_20_E_LOCALITY() { return (int)-2144859897L; }

    public static int TPM_20_E_YIELDED() { return (int)-2144859896L; }

    public static int TPM_20_E_CANCELED() { return (int)-2144859895L; }

    public static int TPM_20_E_TESTING() { return (int)-2144859894L; }

    public static int TPM_20_E_NV_RATE() { return (int)-2144859872L; }

    public static int TPM_20_E_LOCKOUT() { return (int)-2144859871L; }

    public static int TPM_20_E_RETRY() { return (int)-2144859870L; }

    public static int TPM_20_E_NV_UNAVAILABLE() { return (int)-2144859869L; }

    public static int TBS_E_INTERNAL_ERROR() { return (int)-2144845823L; }

    public static int TBS_E_BAD_PARAMETER() { return (int)-2144845822L; }

    public static int TBS_E_INVALID_OUTPUT_POINTER() { return (int)-2144845821L; }

    public static int TBS_E_INVALID_CONTEXT() { return (int)-2144845820L; }

    public static int TBS_E_INSUFFICIENT_BUFFER() { return (int)-2144845819L; }

    public static int TBS_E_IOERROR() { return (int)-2144845818L; }

    public static int TBS_E_INVALID_CONTEXT_PARAM() { return (int)-2144845817L; }

    public static int TBS_E_SERVICE_NOT_RUNNING() { return (int)-2144845816L; }

    public static int TBS_E_TOO_MANY_TBS_CONTEXTS() { return (int)-2144845815L; }

    public static int TBS_E_TOO_MANY_RESOURCES() { return (int)-2144845814L; }

    public static int TBS_E_SERVICE_START_PENDING() { return (int)-2144845813L; }

    public static int TBS_E_PPI_NOT_SUPPORTED() { return (int)-2144845812L; }

    public static int TBS_E_COMMAND_CANCELED() { return (int)-2144845811L; }

    public static int TBS_E_BUFFER_TOO_LARGE() { return (int)-2144845810L; }

    public static int TBS_E_TPM_NOT_FOUND() { return (int)-2144845809L; }

    public static int TBS_E_SERVICE_DISABLED() { return (int)-2144845808L; }

    public static int TBS_E_NO_EVENT_LOG() { return (int)-2144845807L; }

    public static int TBS_E_ACCESS_DENIED() { return (int)-2144845806L; }

    public static int TBS_E_PROVISIONING_NOT_ALLOWED() { return (int)-2144845805L; }

    public static int TBS_E_PPI_FUNCTION_UNSUPPORTED() { return (int)-2144845804L; }

    public static int TBS_E_OWNERAUTH_NOT_FOUND() { return (int)-2144845803L; }

    public static int TBS_E_PROVISIONING_INCOMPLETE() { return (int)-2144845802L; }

    public static int TPMAPI_E_INVALID_STATE() { return (int)-2144796416L; }

    public static int TPMAPI_E_NOT_ENOUGH_DATA() { return (int)-2144796415L; }

    public static int TPMAPI_E_TOO_MUCH_DATA() { return (int)-2144796414L; }

    public static int TPMAPI_E_INVALID_OUTPUT_POINTER() { return (int)-2144796413L; }

    public static int TPMAPI_E_INVALID_PARAMETER() { return (int)-2144796412L; }

    public static int TPMAPI_E_OUT_OF_MEMORY() { return (int)-2144796411L; }

    public static int TPMAPI_E_BUFFER_TOO_SMALL() { return (int)-2144796410L; }

    public static int TPMAPI_E_INTERNAL_ERROR() { return (int)-2144796409L; }

    public static int TPMAPI_E_ACCESS_DENIED() { return (int)-2144796408L; }

    public static int TPMAPI_E_AUTHORIZATION_FAILED() { return (int)-2144796407L; }

    public static int TPMAPI_E_INVALID_CONTEXT_HANDLE() { return (int)-2144796406L; }

    public static int TPMAPI_E_TBS_COMMUNICATION_ERROR() { return (int)-2144796405L; }

    public static int TPMAPI_E_TPM_COMMAND_ERROR() { return (int)-2144796404L; }

    public static int TPMAPI_E_MESSAGE_TOO_LARGE() { return (int)-2144796403L; }

    public static int TPMAPI_E_INVALID_ENCODING() { return (int)-2144796402L; }

    public static int TPMAPI_E_INVALID_KEY_SIZE() { return (int)-2144796401L; }

    public static int TPMAPI_E_ENCRYPTION_FAILED() { return (int)-2144796400L; }

    public static int TPMAPI_E_INVALID_KEY_PARAMS() { return (int)-2144796399L; }

    public static int TPMAPI_E_INVALID_MIGRATION_AUTHORIZATION_BLOB() { return (int)-2144796398L; }

    public static int TPMAPI_E_INVALID_PCR_INDEX() { return (int)-2144796397L; }

    public static int TPMAPI_E_INVALID_DELEGATE_BLOB() { return (int)-2144796396L; }

    public static int TPMAPI_E_INVALID_CONTEXT_PARAMS() { return (int)-2144796395L; }

    public static int TPMAPI_E_INVALID_KEY_BLOB() { return (int)-2144796394L; }

    public static int TPMAPI_E_INVALID_PCR_DATA() { return (int)-2144796393L; }

    public static int TPMAPI_E_INVALID_OWNER_AUTH() { return (int)-2144796392L; }

    public static int TPMAPI_E_FIPS_RNG_CHECK_FAILED() { return (int)-2144796391L; }

    public static int TPMAPI_E_EMPTY_TCG_LOG() { return (int)-2144796390L; }

    public static int TPMAPI_E_INVALID_TCG_LOG_ENTRY() { return (int)-2144796389L; }

    public static int TPMAPI_E_TCG_SEPARATOR_ABSENT() { return (int)-2144796388L; }

    public static int TPMAPI_E_TCG_INVALID_DIGEST_ENTRY() { return (int)-2144796387L; }

    public static int TPMAPI_E_POLICY_DENIES_OPERATION() { return (int)-2144796386L; }

    public static int TPMAPI_E_NV_BITS_NOT_DEFINED() { return (int)-2144796385L; }

    public static int TPMAPI_E_NV_BITS_NOT_READY() { return (int)-2144796384L; }

    public static int TPMAPI_E_SEALING_KEY_NOT_AVAILABLE() { return (int)-2144796383L; }

    public static int TPMAPI_E_NO_AUTHORIZATION_CHAIN_FOUND() { return (int)-2144796382L; }

    public static int TPMAPI_E_SVN_COUNTER_NOT_AVAILABLE() { return (int)-2144796381L; }

    public static int TPMAPI_E_OWNER_AUTH_NOT_NULL() { return (int)-2144796380L; }

    public static int TPMAPI_E_ENDORSEMENT_AUTH_NOT_NULL() { return (int)-2144796379L; }

    public static int TPMAPI_E_AUTHORIZATION_REVOKED() { return (int)-2144796378L; }

    public static int TPMAPI_E_MALFORMED_AUTHORIZATION_KEY() { return (int)-2144796377L; }

    public static int TPMAPI_E_AUTHORIZING_KEY_NOT_SUPPORTED() { return (int)-2144796376L; }

    public static int TPMAPI_E_INVALID_AUTHORIZATION_SIGNATURE() { return (int)-2144796375L; }

    public static int TPMAPI_E_MALFORMED_AUTHORIZATION_POLICY() { return (int)-2144796374L; }

    public static int TPMAPI_E_MALFORMED_AUTHORIZATION_OTHER() { return (int)-2144796373L; }

    public static int TPMAPI_E_SEALING_KEY_CHANGED() { return (int)-2144796372L; }

    public static int TPMAPI_E_INVALID_TPM_VERSION() { return (int)-2144796371L; }

    public static int TPMAPI_E_INVALID_POLICYAUTH_BLOB_TYPE() { return (int)-2144796370L; }

    public static int TBSIMP_E_BUFFER_TOO_SMALL() { return (int)-2144796160L; }

    public static int TBSIMP_E_CLEANUP_FAILED() { return (int)-2144796159L; }

    public static int TBSIMP_E_INVALID_CONTEXT_HANDLE() { return (int)-2144796158L; }

    public static int TBSIMP_E_INVALID_CONTEXT_PARAM() { return (int)-2144796157L; }

    public static int TBSIMP_E_TPM_ERROR() { return (int)-2144796156L; }

    public static int TBSIMP_E_HASH_BAD_KEY() { return (int)-2144796155L; }

    public static int TBSIMP_E_DUPLICATE_VHANDLE() { return (int)-2144796154L; }

    public static int TBSIMP_E_INVALID_OUTPUT_POINTER() { return (int)-2144796153L; }

    public static int TBSIMP_E_INVALID_PARAMETER() { return (int)-2144796152L; }

    public static int TBSIMP_E_RPC_INIT_FAILED() { return (int)-2144796151L; }

    public static int TBSIMP_E_SCHEDULER_NOT_RUNNING() { return (int)-2144796150L; }

    public static int TBSIMP_E_COMMAND_CANCELED() { return (int)-2144796149L; }

    public static int TBSIMP_E_OUT_OF_MEMORY() { return (int)-2144796148L; }

    public static int TBSIMP_E_LIST_NO_MORE_ITEMS() { return (int)-2144796147L; }

    public static int TBSIMP_E_LIST_NOT_FOUND() { return (int)-2144796146L; }

    public static int TBSIMP_E_NOT_ENOUGH_SPACE() { return (int)-2144796145L; }

    public static int TBSIMP_E_NOT_ENOUGH_TPM_CONTEXTS() { return (int)-2144796144L; }

    public static int TBSIMP_E_COMMAND_FAILED() { return (int)-2144796143L; }

    public static int TBSIMP_E_UNKNOWN_ORDINAL() { return (int)-2144796142L; }

    public static int TBSIMP_E_RESOURCE_EXPIRED() { return (int)-2144796141L; }

    public static int TBSIMP_E_INVALID_RESOURCE() { return (int)-2144796140L; }

    public static int TBSIMP_E_NOTHING_TO_UNLOAD() { return (int)-2144796139L; }

    public static int TBSIMP_E_HASH_TABLE_FULL() { return (int)-2144796138L; }

    public static int TBSIMP_E_TOO_MANY_TBS_CONTEXTS() { return (int)-2144796137L; }

    public static int TBSIMP_E_TOO_MANY_RESOURCES() { return (int)-2144796136L; }

    public static int TBSIMP_E_PPI_NOT_SUPPORTED() { return (int)-2144796135L; }

    public static int TBSIMP_E_TPM_INCOMPATIBLE() { return (int)-2144796134L; }

    public static int TBSIMP_E_NO_EVENT_LOG() { return (int)-2144796133L; }

    public static int TPM_E_PPI_ACPI_FAILURE() { return (int)-2144795904L; }

    public static int TPM_E_PPI_USER_ABORT() { return (int)-2144795903L; }

    public static int TPM_E_PPI_BIOS_FAILURE() { return (int)-2144795902L; }

    public static int TPM_E_PPI_NOT_SUPPORTED() { return (int)-2144795901L; }

    public static int TPM_E_PPI_BLOCKED_IN_BIOS() { return (int)-2144795900L; }

    public static int TPM_E_PCP_ERROR_MASK() { return (int)-2144795648L; }

    public static int TPM_E_PCP_DEVICE_NOT_READY() { return (int)-2144795647L; }

    public static int TPM_E_PCP_INVALID_HANDLE() { return (int)-2144795646L; }

    public static int TPM_E_PCP_INVALID_PARAMETER() { return (int)-2144795645L; }

    public static int TPM_E_PCP_FLAG_NOT_SUPPORTED() { return (int)-2144795644L; }

    public static int TPM_E_PCP_NOT_SUPPORTED() { return (int)-2144795643L; }

    public static int TPM_E_PCP_BUFFER_TOO_SMALL() { return (int)-2144795642L; }

    public static int TPM_E_PCP_INTERNAL_ERROR() { return (int)-2144795641L; }

    public static int TPM_E_PCP_AUTHENTICATION_FAILED() { return (int)-2144795640L; }

    public static int TPM_E_PCP_AUTHENTICATION_IGNORED() { return (int)-2144795639L; }

    public static int TPM_E_PCP_POLICY_NOT_FOUND() { return (int)-2144795638L; }

    public static int TPM_E_PCP_PROFILE_NOT_FOUND() { return (int)-2144795637L; }

    public static int TPM_E_PCP_VALIDATION_FAILED() { return (int)-2144795636L; }

    public static int TPM_E_PCP_WRONG_PARENT() { return (int)-2144795634L; }

    public static int TPM_E_KEY_NOT_LOADED() { return (int)-2144795633L; }

    public static int TPM_E_NO_KEY_CERTIFICATION() { return (int)-2144795632L; }

    public static int TPM_E_KEY_NOT_FINALIZED() { return (int)-2144795631L; }

    public static int TPM_E_ATTESTATION_CHALLENGE_NOT_SET() { return (int)-2144795630L; }

    public static int TPM_E_NOT_PCR_BOUND() { return (int)-2144795629L; }

    public static int TPM_E_KEY_ALREADY_FINALIZED() { return (int)-2144795628L; }

    public static int TPM_E_KEY_USAGE_POLICY_NOT_SUPPORTED() { return (int)-2144795627L; }

    public static int TPM_E_KEY_USAGE_POLICY_INVALID() { return (int)-2144795626L; }

    public static int TPM_E_SOFT_KEY_ERROR() { return (int)-2144795625L; }

    public static int TPM_E_KEY_NOT_AUTHENTICATED() { return (int)-2144795624L; }

    public static int TPM_E_PCP_KEY_NOT_AIK() { return (int)-2144795623L; }

    public static int TPM_E_KEY_NOT_SIGNING_KEY() { return (int)-2144795622L; }

    public static int TPM_E_LOCKED_OUT() { return (int)-2144795621L; }

    public static int TPM_E_CLAIM_TYPE_NOT_SUPPORTED() { return (int)-2144795620L; }

    public static int TPM_E_VERSION_NOT_SUPPORTED() { return (int)-2144795619L; }

    public static int TPM_E_BUFFER_LENGTH_MISMATCH() { return (int)-2144795618L; }

    public static int TPM_E_PCP_IFX_RSA_KEY_CREATION_BLOCKED() { return (int)-2144795617L; }

    public static int TPM_E_PCP_TICKET_MISSING() { return (int)-2144795616L; }

    public static int TPM_E_PCP_RAW_POLICY_NOT_SUPPORTED() { return (int)-2144795615L; }

    public static int TPM_E_PCP_KEY_HANDLE_INVALIDATED() { return (int)-2144795614L; }

    public static int TPM_E_PCP_UNSUPPORTED_PSS_SALT() { return (int)1076429859L; }

    public static int TPM_E_PCP_PLATFORM_CLAIM_MAY_BE_OUTDATED() { return (int)1076429860L; }

    public static int TPM_E_PCP_PLATFORM_CLAIM_OUTDATED() { return (int)1076429861L; }

    public static int TPM_E_PCP_PLATFORM_CLAIM_REBOOT() { return (int)1076429862L; }

    public static int TPM_E_ZERO_EXHAUST_ENABLED() { return (int)-2144795392L; }

    public static int TPM_E_PROVISIONING_INCOMPLETE() { return (int)-2144795136L; }

    public static int TPM_E_INVALID_OWNER_AUTH() { return (int)-2144795135L; }

    public static int TPM_E_TOO_MUCH_DATA() { return (int)-2144795134L; }

    public static int PLA_E_DCS_NOT_FOUND() { return (int)-2144337918L; }

    public static int PLA_E_DCS_IN_USE() { return (int)-2144337750L; }

    public static int PLA_E_TOO_MANY_FOLDERS() { return (int)-2144337851L; }

    public static int PLA_E_NO_MIN_DISK() { return (int)-2144337808L; }

    public static int PLA_E_DCS_ALREADY_EXISTS() { return (int)-2144337737L; }

    public static int PLA_S_PROPERTY_IGNORED() { return (int)3145984L; }

    public static int PLA_E_PROPERTY_CONFLICT() { return (int)-2144337663L; }

    public static int PLA_E_DCS_SINGLETON_REQUIRED() { return (int)-2144337662L; }

    public static int PLA_E_CREDENTIALS_REQUIRED() { return (int)-2144337661L; }

    public static int PLA_E_DCS_NOT_RUNNING() { return (int)-2144337660L; }

    public static int PLA_E_CONFLICT_INCL_EXCL_API() { return (int)-2144337659L; }

    public static int PLA_E_NETWORK_EXE_NOT_VALID() { return (int)-2144337658L; }

    public static int PLA_E_EXE_ALREADY_CONFIGURED() { return (int)-2144337657L; }

    public static int PLA_E_EXE_PATH_NOT_VALID() { return (int)-2144337656L; }

    public static int PLA_E_DC_ALREADY_EXISTS() { return (int)-2144337655L; }

    public static int PLA_E_DCS_START_WAIT_TIMEOUT() { return (int)-2144337654L; }

    public static int PLA_E_DC_START_WAIT_TIMEOUT() { return (int)-2144337653L; }

    public static int PLA_E_REPORT_WAIT_TIMEOUT() { return (int)-2144337652L; }

    public static int PLA_E_NO_DUPLICATES() { return (int)-2144337651L; }

    public static int PLA_E_EXE_FULL_PATH_REQUIRED() { return (int)-2144337650L; }

    public static int PLA_E_INVALID_SESSION_NAME() { return (int)-2144337649L; }

    public static int PLA_E_PLA_CHANNEL_NOT_ENABLED() { return (int)-2144337648L; }

    public static int PLA_E_TASKSCHED_CHANNEL_NOT_ENABLED() { return (int)-2144337647L; }

    public static int PLA_E_RULES_MANAGER_FAILED() { return (int)-2144337646L; }

    public static int PLA_E_CABAPI_FAILURE() { return (int)-2144337645L; }

    public static int FVE_E_LOCKED_VOLUME() { return (int)-2144272384L; }

    public static int FVE_E_NOT_ENCRYPTED() { return (int)-2144272383L; }

    public static int FVE_E_NO_TPM_BIOS() { return (int)-2144272382L; }

    public static int FVE_E_NO_MBR_METRIC() { return (int)-2144272381L; }

    public static int FVE_E_NO_BOOTSECTOR_METRIC() { return (int)-2144272380L; }

    public static int FVE_E_NO_BOOTMGR_METRIC() { return (int)-2144272379L; }

    public static int FVE_E_WRONG_BOOTMGR() { return (int)-2144272378L; }

    public static int FVE_E_SECURE_KEY_REQUIRED() { return (int)-2144272377L; }

    public static int FVE_E_NOT_ACTIVATED() { return (int)-2144272376L; }

    public static int FVE_E_ACTION_NOT_ALLOWED() { return (int)-2144272375L; }

    public static int FVE_E_AD_SCHEMA_NOT_INSTALLED() { return (int)-2144272374L; }

    public static int FVE_E_AD_INVALID_DATATYPE() { return (int)-2144272373L; }

    public static int FVE_E_AD_INVALID_DATASIZE() { return (int)-2144272372L; }

    public static int FVE_E_AD_NO_VALUES() { return (int)-2144272371L; }

    public static int FVE_E_AD_ATTR_NOT_SET() { return (int)-2144272370L; }

    public static int FVE_E_AD_GUID_NOT_FOUND() { return (int)-2144272369L; }

    public static int FVE_E_BAD_INFORMATION() { return (int)-2144272368L; }

    public static int FVE_E_TOO_SMALL() { return (int)-2144272367L; }

    public static int FVE_E_SYSTEM_VOLUME() { return (int)-2144272366L; }

    public static int FVE_E_FAILED_WRONG_FS() { return (int)-2144272365L; }

    public static int FVE_E_BAD_PARTITION_SIZE() { return (int)-2144272364L; }

    public static int FVE_E_NOT_SUPPORTED() { return (int)-2144272363L; }

    public static int FVE_E_BAD_DATA() { return (int)-2144272362L; }

    public static int FVE_E_VOLUME_NOT_BOUND() { return (int)-2144272361L; }

    public static int FVE_E_TPM_NOT_OWNED() { return (int)-2144272360L; }

    public static int FVE_E_NOT_DATA_VOLUME() { return (int)-2144272359L; }

    public static int FVE_E_AD_INSUFFICIENT_BUFFER() { return (int)-2144272358L; }

    public static int FVE_E_CONV_READ() { return (int)-2144272357L; }

    public static int FVE_E_CONV_WRITE() { return (int)-2144272356L; }

    public static int FVE_E_KEY_REQUIRED() { return (int)-2144272355L; }

    public static int FVE_E_CLUSTERING_NOT_SUPPORTED() { return (int)-2144272354L; }

    public static int FVE_E_VOLUME_BOUND_ALREADY() { return (int)-2144272353L; }

    public static int FVE_E_OS_NOT_PROTECTED() { return (int)-2144272352L; }

    public static int FVE_E_PROTECTION_DISABLED() { return (int)-2144272351L; }

    public static int FVE_E_RECOVERY_KEY_REQUIRED() { return (int)-2144272350L; }

    public static int FVE_E_FOREIGN_VOLUME() { return (int)-2144272349L; }

    public static int FVE_E_OVERLAPPED_UPDATE() { return (int)-2144272348L; }

    public static int FVE_E_TPM_SRK_AUTH_NOT_ZERO() { return (int)-2144272347L; }

    public static int FVE_E_FAILED_SECTOR_SIZE() { return (int)-2144272346L; }

    public static int FVE_E_FAILED_AUTHENTICATION() { return (int)-2144272345L; }

    public static int FVE_E_NOT_OS_VOLUME() { return (int)-2144272344L; }

    public static int FVE_E_AUTOUNLOCK_ENABLED() { return (int)-2144272343L; }

    public static int FVE_E_WRONG_BOOTSECTOR() { return (int)-2144272342L; }

    public static int FVE_E_WRONG_SYSTEM_FS() { return (int)-2144272341L; }

    public static int FVE_E_POLICY_PASSWORD_REQUIRED() { return (int)-2144272340L; }

    public static int FVE_E_CANNOT_SET_FVEK_ENCRYPTED() { return (int)-2144272339L; }

    public static int FVE_E_CANNOT_ENCRYPT_NO_KEY() { return (int)-2144272338L; }

    public static int FVE_E_BOOTABLE_CDDVD() { return (int)-2144272336L; }

    public static int FVE_E_PROTECTOR_EXISTS() { return (int)-2144272335L; }

    public static int FVE_E_RELATIVE_PATH() { return (int)-2144272334L; }

    public static int FVE_E_PROTECTOR_NOT_FOUND() { return (int)-2144272333L; }

    public static int FVE_E_INVALID_KEY_FORMAT() { return (int)-2144272332L; }

    public static int FVE_E_INVALID_PASSWORD_FORMAT() { return (int)-2144272331L; }

    public static int FVE_E_FIPS_RNG_CHECK_FAILED() { return (int)-2144272330L; }

    public static int FVE_E_FIPS_PREVENTS_RECOVERY_PASSWORD() { return (int)-2144272329L; }

    public static int FVE_E_FIPS_PREVENTS_EXTERNAL_KEY_EXPORT() { return (int)-2144272328L; }

    public static int FVE_E_NOT_DECRYPTED() { return (int)-2144272327L; }

    public static int FVE_E_INVALID_PROTECTOR_TYPE() { return (int)-2144272326L; }

    public static int FVE_E_NO_PROTECTORS_TO_TEST() { return (int)-2144272325L; }

    public static int FVE_E_KEYFILE_NOT_FOUND() { return (int)-2144272324L; }

    public static int FVE_E_KEYFILE_INVALID() { return (int)-2144272323L; }

    public static int FVE_E_KEYFILE_NO_VMK() { return (int)-2144272322L; }

    public static int FVE_E_TPM_DISABLED() { return (int)-2144272321L; }

    public static int FVE_E_NOT_ALLOWED_IN_SAFE_MODE() { return (int)-2144272320L; }

    public static int FVE_E_TPM_INVALID_PCR() { return (int)-2144272319L; }

    public static int FVE_E_TPM_NO_VMK() { return (int)-2144272318L; }

    public static int FVE_E_PIN_INVALID() { return (int)-2144272317L; }

    public static int FVE_E_AUTH_INVALID_APPLICATION() { return (int)-2144272316L; }

    public static int FVE_E_AUTH_INVALID_CONFIG() { return (int)-2144272315L; }

    public static int FVE_E_FIPS_DISABLE_PROTECTION_NOT_ALLOWED() { return (int)-2144272314L; }

    public static int FVE_E_FS_NOT_EXTENDED() { return (int)-2144272313L; }

    public static int FVE_E_FIRMWARE_TYPE_NOT_SUPPORTED() { return (int)-2144272312L; }

    public static int FVE_E_NO_LICENSE() { return (int)-2144272311L; }

    public static int FVE_E_NOT_ON_STACK() { return (int)-2144272310L; }

    public static int FVE_E_FS_MOUNTED() { return (int)-2144272309L; }

    public static int FVE_E_TOKEN_NOT_IMPERSONATED() { return (int)-2144272308L; }

    public static int FVE_E_DRY_RUN_FAILED() { return (int)-2144272307L; }

    public static int FVE_E_REBOOT_REQUIRED() { return (int)-2144272306L; }

    public static int FVE_E_DEBUGGER_ENABLED() { return (int)-2144272305L; }

    public static int FVE_E_RAW_ACCESS() { return (int)-2144272304L; }

    public static int FVE_E_RAW_BLOCKED() { return (int)-2144272303L; }

    public static int FVE_E_BCD_APPLICATIONS_PATH_INCORRECT() { return (int)-2144272302L; }

    public static int FVE_E_NOT_ALLOWED_IN_VERSION() { return (int)-2144272301L; }

    public static int FVE_E_NO_AUTOUNLOCK_MASTER_KEY() { return (int)-2144272300L; }

    public static int FVE_E_MOR_FAILED() { return (int)-2144272299L; }

    public static int FVE_E_HIDDEN_VOLUME() { return (int)-2144272298L; }

    public static int FVE_E_TRANSIENT_STATE() { return (int)-2144272297L; }

    public static int FVE_E_PUBKEY_NOT_ALLOWED() { return (int)-2144272296L; }

    public static int FVE_E_VOLUME_HANDLE_OPEN() { return (int)-2144272295L; }

    public static int FVE_E_NO_FEATURE_LICENSE() { return (int)-2144272294L; }

    public static int FVE_E_INVALID_STARTUP_OPTIONS() { return (int)-2144272293L; }

    public static int FVE_E_POLICY_RECOVERY_PASSWORD_NOT_ALLOWED() { return (int)-2144272292L; }

    public static int FVE_E_POLICY_RECOVERY_PASSWORD_REQUIRED() { return (int)-2144272291L; }

    public static int FVE_E_POLICY_RECOVERY_KEY_NOT_ALLOWED() { return (int)-2144272290L; }

    public static int FVE_E_POLICY_RECOVERY_KEY_REQUIRED() { return (int)-2144272289L; }

    public static int FVE_E_POLICY_STARTUP_PIN_NOT_ALLOWED() { return (int)-2144272288L; }

    public static int FVE_E_POLICY_STARTUP_PIN_REQUIRED() { return (int)-2144272287L; }

    public static int FVE_E_POLICY_STARTUP_KEY_NOT_ALLOWED() { return (int)-2144272286L; }

    public static int FVE_E_POLICY_STARTUP_KEY_REQUIRED() { return (int)-2144272285L; }

    public static int FVE_E_POLICY_STARTUP_PIN_KEY_NOT_ALLOWED() { return (int)-2144272284L; }

    public static int FVE_E_POLICY_STARTUP_PIN_KEY_REQUIRED() { return (int)-2144272283L; }

    public static int FVE_E_POLICY_STARTUP_TPM_NOT_ALLOWED() { return (int)-2144272282L; }

    public static int FVE_E_POLICY_STARTUP_TPM_REQUIRED() { return (int)-2144272281L; }

    public static int FVE_E_POLICY_INVALID_PIN_LENGTH() { return (int)-2144272280L; }

    public static int FVE_E_KEY_PROTECTOR_NOT_SUPPORTED() { return (int)-2144272279L; }

    public static int FVE_E_POLICY_PASSPHRASE_NOT_ALLOWED() { return (int)-2144272278L; }

    public static int FVE_E_POLICY_PASSPHRASE_REQUIRED() { return (int)-2144272277L; }

    public static int FVE_E_FIPS_PREVENTS_PASSPHRASE() { return (int)-2144272276L; }

    public static int FVE_E_OS_VOLUME_PASSPHRASE_NOT_ALLOWED() { return (int)-2144272275L; }

    public static int FVE_E_INVALID_BITLOCKER_OID() { return (int)-2144272274L; }

    public static int FVE_E_VOLUME_TOO_SMALL() { return (int)-2144272273L; }

    public static int FVE_E_DV_NOT_SUPPORTED_ON_FS() { return (int)-2144272272L; }

    public static int FVE_E_DV_NOT_ALLOWED_BY_GP() { return (int)-2144272271L; }

    public static int FVE_E_POLICY_USER_CERTIFICATE_NOT_ALLOWED() { return (int)-2144272270L; }

    public static int FVE_E_POLICY_USER_CERTIFICATE_REQUIRED() { return (int)-2144272269L; }

    public static int FVE_E_POLICY_USER_CERT_MUST_BE_HW() { return (int)-2144272268L; }

    public static int FVE_E_POLICY_USER_CONFIGURE_FDV_AUTOUNLOCK_NOT_ALLOWED() { return (int)-2144272267L; }

    public static int FVE_E_POLICY_USER_CONFIGURE_RDV_AUTOUNLOCK_NOT_ALLOWED() { return (int)-2144272266L; }

    public static int FVE_E_POLICY_USER_CONFIGURE_RDV_NOT_ALLOWED() { return (int)-2144272265L; }

    public static int FVE_E_POLICY_USER_ENABLE_RDV_NOT_ALLOWED() { return (int)-2144272264L; }

    public static int FVE_E_POLICY_USER_DISABLE_RDV_NOT_ALLOWED() { return (int)-2144272263L; }

    public static int FVE_E_POLICY_INVALID_PASSPHRASE_LENGTH() { return (int)-2144272256L; }

    public static int FVE_E_POLICY_PASSPHRASE_TOO_SIMPLE() { return (int)-2144272255L; }

    public static int FVE_E_RECOVERY_PARTITION() { return (int)-2144272254L; }

    public static int FVE_E_POLICY_CONFLICT_FDV_RK_OFF_AUK_ON() { return (int)-2144272253L; }

    public static int FVE_E_POLICY_CONFLICT_RDV_RK_OFF_AUK_ON() { return (int)-2144272252L; }

    public static int FVE_E_NON_BITLOCKER_OID() { return (int)-2144272251L; }

    public static int FVE_E_POLICY_PROHIBITS_SELFSIGNED() { return (int)-2144272250L; }

    public static int FVE_E_POLICY_CONFLICT_RO_AND_STARTUP_KEY_REQUIRED() { return (int)-2144272249L; }

    public static int FVE_E_CONV_RECOVERY_FAILED() { return (int)-2144272248L; }

    public static int FVE_E_VIRTUALIZED_SPACE_TOO_BIG() { return (int)-2144272247L; }

    public static int FVE_E_POLICY_CONFLICT_OSV_RP_OFF_ADB_ON() { return (int)-2144272240L; }

    public static int FVE_E_POLICY_CONFLICT_FDV_RP_OFF_ADB_ON() { return (int)-2144272239L; }

    public static int FVE_E_POLICY_CONFLICT_RDV_RP_OFF_ADB_ON() { return (int)-2144272238L; }

    public static int FVE_E_NON_BITLOCKER_KU() { return (int)-2144272237L; }

    public static int FVE_E_PRIVATEKEY_AUTH_FAILED() { return (int)-2144272236L; }

    public static int FVE_E_REMOVAL_OF_DRA_FAILED() { return (int)-2144272235L; }

    public static int FVE_E_OPERATION_NOT_SUPPORTED_ON_VISTA_VOLUME() { return (int)-2144272234L; }

    public static int FVE_E_CANT_LOCK_AUTOUNLOCK_ENABLED_VOLUME() { return (int)-2144272233L; }

    public static int FVE_E_FIPS_HASH_KDF_NOT_ALLOWED() { return (int)-2144272232L; }

    public static int FVE_E_ENH_PIN_INVALID() { return (int)-2144272231L; }

    public static int FVE_E_INVALID_PIN_CHARS() { return (int)-2144272230L; }

    public static int FVE_E_INVALID_DATUM_TYPE() { return (int)-2144272229L; }

    public static int FVE_E_EFI_ONLY() { return (int)-2144272228L; }

    public static int FVE_E_MULTIPLE_NKP_CERTS() { return (int)-2144272227L; }

    public static int FVE_E_REMOVAL_OF_NKP_FAILED() { return (int)-2144272226L; }

    public static int FVE_E_INVALID_NKP_CERT() { return (int)-2144272225L; }

    public static int FVE_E_NO_EXISTING_PIN() { return (int)-2144272224L; }

    public static int FVE_E_PROTECTOR_CHANGE_PIN_MISMATCH() { return (int)-2144272223L; }

    public static int FVE_E_PIN_PROTECTOR_CHANGE_BY_STD_USER_DISALLOWED() { return (int)-2144272222L; }

    public static int FVE_E_PROTECTOR_CHANGE_MAX_PIN_CHANGE_ATTEMPTS_REACHED() { return (int)-2144272221L; }

    public static int FVE_E_POLICY_PASSPHRASE_REQUIRES_ASCII() { return (int)-2144272220L; }

    public static int FVE_E_FULL_ENCRYPTION_NOT_ALLOWED_ON_TP_STORAGE() { return (int)-2144272219L; }

    public static int FVE_E_WIPE_NOT_ALLOWED_ON_TP_STORAGE() { return (int)-2144272218L; }

    public static int FVE_E_KEY_LENGTH_NOT_SUPPORTED_BY_EDRIVE() { return (int)-2144272217L; }

    public static int FVE_E_NO_EXISTING_PASSPHRASE() { return (int)-2144272216L; }

    public static int FVE_E_PROTECTOR_CHANGE_PASSPHRASE_MISMATCH() { return (int)-2144272215L; }

    public static int FVE_E_PASSPHRASE_TOO_LONG() { return (int)-2144272214L; }

    public static int FVE_E_NO_PASSPHRASE_WITH_TPM() { return (int)-2144272213L; }

    public static int FVE_E_NO_TPM_WITH_PASSPHRASE() { return (int)-2144272212L; }

    public static int FVE_E_NOT_ALLOWED_ON_CSV_STACK() { return (int)-2144272211L; }

    public static int FVE_E_NOT_ALLOWED_ON_CLUSTER() { return (int)-2144272210L; }

    public static int FVE_E_EDRIVE_NO_FAILOVER_TO_SW() { return (int)-2144272209L; }

    public static int FVE_E_EDRIVE_BAND_IN_USE() { return (int)-2144272208L; }

    public static int FVE_E_EDRIVE_DISALLOWED_BY_GP() { return (int)-2144272207L; }

    public static int FVE_E_EDRIVE_INCOMPATIBLE_VOLUME() { return (int)-2144272206L; }

    public static int FVE_E_NOT_ALLOWED_TO_UPGRADE_WHILE_CONVERTING() { return (int)-2144272205L; }

    public static int FVE_E_EDRIVE_DV_NOT_SUPPORTED() { return (int)-2144272204L; }

    public static int FVE_E_NO_PREBOOT_KEYBOARD_DETECTED() { return (int)-2144272203L; }

    public static int FVE_E_NO_PREBOOT_KEYBOARD_OR_WINRE_DETECTED() { return (int)-2144272202L; }

    public static int FVE_E_POLICY_REQUIRES_STARTUP_PIN_ON_TOUCH_DEVICE() { return (int)-2144272201L; }

    public static int FVE_E_POLICY_REQUIRES_RECOVERY_PASSWORD_ON_TOUCH_DEVICE() { return (int)-2144272200L; }

    public static int FVE_E_WIPE_CANCEL_NOT_APPLICABLE() { return (int)-2144272199L; }

    public static int FVE_E_SECUREBOOT_DISABLED() { return (int)-2144272198L; }

    public static int FVE_E_SECUREBOOT_CONFIGURATION_INVALID() { return (int)-2144272197L; }

    public static int FVE_E_EDRIVE_DRY_RUN_FAILED() { return (int)-2144272196L; }

    public static int FVE_E_SHADOW_COPY_PRESENT() { return (int)-2144272195L; }

    public static int FVE_E_POLICY_INVALID_ENHANCED_BCD_SETTINGS() { return (int)-2144272194L; }

    public static int FVE_E_EDRIVE_INCOMPATIBLE_FIRMWARE() { return (int)-2144272193L; }

    public static int FVE_E_PROTECTOR_CHANGE_MAX_PASSPHRASE_CHANGE_ATTEMPTS_REACHED() { return (int)-2144272192L; }

    public static int FVE_E_PASSPHRASE_PROTECTOR_CHANGE_BY_STD_USER_DISALLOWED() { return (int)-2144272191L; }

    public static int FVE_E_LIVEID_ACCOUNT_SUSPENDED() { return (int)-2144272190L; }

}

