// Generated by jextract

package com.dx12;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import jdk.incubator.foreign.*;
import jdk.incubator.foreign.MemoryLayout.PathElement;
import static jdk.incubator.foreign.CSupport.Win64.*;

public class Windows_h$constants$6 extends Windows_h$constants$5 {
    Windows_h$constants$6() {}
    public static int MAX_LOGICALDPIOVERRIDE() { return (int)2L; }

    public static int SPI_GETLOGICALDPIOVERRIDE() { return (int)158L; }

    public static int SPI_SETLOGICALDPIOVERRIDE() { return (int)159L; }

    public static int SPI_GETMENURECT() { return (int)162L; }

    public static int SPI_SETMENURECT() { return (int)163L; }

    public static int SPI_GETACTIVEWINDOWTRACKING() { return (int)4096L; }

    public static int SPI_SETACTIVEWINDOWTRACKING() { return (int)4097L; }

    public static int SPI_GETMENUANIMATION() { return (int)4098L; }

    public static int SPI_SETMENUANIMATION() { return (int)4099L; }

    public static int SPI_GETCOMBOBOXANIMATION() { return (int)4100L; }

    public static int SPI_SETCOMBOBOXANIMATION() { return (int)4101L; }

    public static int SPI_GETLISTBOXSMOOTHSCROLLING() { return (int)4102L; }

    public static int SPI_SETLISTBOXSMOOTHSCROLLING() { return (int)4103L; }

    public static int SPI_GETGRADIENTCAPTIONS() { return (int)4104L; }

    public static int SPI_SETGRADIENTCAPTIONS() { return (int)4105L; }

    public static int SPI_GETKEYBOARDCUES() { return (int)4106L; }

    public static int SPI_SETKEYBOARDCUES() { return (int)4107L; }

    public static int SPI_GETACTIVEWNDTRKZORDER() { return (int)4108L; }

    public static int SPI_SETACTIVEWNDTRKZORDER() { return (int)4109L; }

    public static int SPI_GETHOTTRACKING() { return (int)4110L; }

    public static int SPI_SETHOTTRACKING() { return (int)4111L; }

    public static int SPI_GETMENUFADE() { return (int)4114L; }

    public static int SPI_SETMENUFADE() { return (int)4115L; }

    public static int SPI_GETSELECTIONFADE() { return (int)4116L; }

    public static int SPI_SETSELECTIONFADE() { return (int)4117L; }

    public static int SPI_GETTOOLTIPANIMATION() { return (int)4118L; }

    public static int SPI_SETTOOLTIPANIMATION() { return (int)4119L; }

    public static int SPI_GETTOOLTIPFADE() { return (int)4120L; }

    public static int SPI_SETTOOLTIPFADE() { return (int)4121L; }

    public static int SPI_GETCURSORSHADOW() { return (int)4122L; }

    public static int SPI_SETCURSORSHADOW() { return (int)4123L; }

    public static int SPI_GETMOUSESONAR() { return (int)4124L; }

    public static int SPI_SETMOUSESONAR() { return (int)4125L; }

    public static int SPI_GETMOUSECLICKLOCK() { return (int)4126L; }

    public static int SPI_SETMOUSECLICKLOCK() { return (int)4127L; }

    public static int SPI_GETMOUSEVANISH() { return (int)4128L; }

    public static int SPI_SETMOUSEVANISH() { return (int)4129L; }

    public static int SPI_GETFLATMENU() { return (int)4130L; }

    public static int SPI_SETFLATMENU() { return (int)4131L; }

    public static int SPI_GETDROPSHADOW() { return (int)4132L; }

    public static int SPI_SETDROPSHADOW() { return (int)4133L; }

    public static int SPI_GETBLOCKSENDINPUTRESETS() { return (int)4134L; }

    public static int SPI_SETBLOCKSENDINPUTRESETS() { return (int)4135L; }

    public static int SPI_GETUIEFFECTS() { return (int)4158L; }

    public static int SPI_SETUIEFFECTS() { return (int)4159L; }

    public static int SPI_GETDISABLEOVERLAPPEDCONTENT() { return (int)4160L; }

    public static int SPI_SETDISABLEOVERLAPPEDCONTENT() { return (int)4161L; }

    public static int SPI_GETCLIENTAREAANIMATION() { return (int)4162L; }

    public static int SPI_SETCLIENTAREAANIMATION() { return (int)4163L; }

    public static int SPI_GETCLEARTYPE() { return (int)4168L; }

    public static int SPI_SETCLEARTYPE() { return (int)4169L; }

    public static int SPI_GETSPEECHRECOGNITION() { return (int)4170L; }

    public static int SPI_SETSPEECHRECOGNITION() { return (int)4171L; }

    public static int SPI_GETCARETBROWSING() { return (int)4172L; }

    public static int SPI_SETCARETBROWSING() { return (int)4173L; }

    public static int SPI_GETTHREADLOCALINPUTSETTINGS() { return (int)4174L; }

    public static int SPI_SETTHREADLOCALINPUTSETTINGS() { return (int)4175L; }

    public static int SPI_GETSYSTEMLANGUAGEBAR() { return (int)4176L; }

    public static int SPI_SETSYSTEMLANGUAGEBAR() { return (int)4177L; }

    public static int SPI_GETFOREGROUNDLOCKTIMEOUT() { return (int)8192L; }

    public static int SPI_SETFOREGROUNDLOCKTIMEOUT() { return (int)8193L; }

    public static int SPI_GETACTIVEWNDTRKTIMEOUT() { return (int)8194L; }

    public static int SPI_SETACTIVEWNDTRKTIMEOUT() { return (int)8195L; }

    public static int SPI_GETFOREGROUNDFLASHCOUNT() { return (int)8196L; }

    public static int SPI_SETFOREGROUNDFLASHCOUNT() { return (int)8197L; }

    public static int SPI_GETCARETWIDTH() { return (int)8198L; }

    public static int SPI_SETCARETWIDTH() { return (int)8199L; }

    public static int SPI_GETMOUSECLICKLOCKTIME() { return (int)8200L; }

    public static int SPI_SETMOUSECLICKLOCKTIME() { return (int)8201L; }

    public static int SPI_GETFONTSMOOTHINGTYPE() { return (int)8202L; }

    public static int SPI_SETFONTSMOOTHINGTYPE() { return (int)8203L; }

    public static int FE_FONTSMOOTHINGSTANDARD() { return (int)1L; }

    public static int FE_FONTSMOOTHINGCLEARTYPE() { return (int)2L; }

    public static int SPI_GETFONTSMOOTHINGCONTRAST() { return (int)8204L; }

    public static int SPI_SETFONTSMOOTHINGCONTRAST() { return (int)8205L; }

    public static int SPI_GETFOCUSBORDERWIDTH() { return (int)8206L; }

    public static int SPI_SETFOCUSBORDERWIDTH() { return (int)8207L; }

    public static int SPI_GETFOCUSBORDERHEIGHT() { return (int)8208L; }

    public static int SPI_SETFOCUSBORDERHEIGHT() { return (int)8209L; }

    public static int SPI_GETFONTSMOOTHINGORIENTATION() { return (int)8210L; }

    public static int SPI_SETFONTSMOOTHINGORIENTATION() { return (int)8211L; }

    public static int FE_FONTSMOOTHINGORIENTATIONBGR() { return (int)0L; }

    public static int FE_FONTSMOOTHINGORIENTATIONRGB() { return (int)1L; }

    public static int SPI_GETMINIMUMHITRADIUS() { return (int)8212L; }

    public static int SPI_SETMINIMUMHITRADIUS() { return (int)8213L; }

    public static int SPI_GETMESSAGEDURATION() { return (int)8214L; }

    public static int SPI_SETMESSAGEDURATION() { return (int)8215L; }

    public static int SPI_GETCONTACTVISUALIZATION() { return (int)8216L; }

    public static int SPI_SETCONTACTVISUALIZATION() { return (int)8217L; }

    public static int CONTACTVISUALIZATION_OFF() { return (int)0L; }

    public static int CONTACTVISUALIZATION_ON() { return (int)1L; }

    public static int CONTACTVISUALIZATION_PRESENTATIONMODE() { return (int)2L; }

    public static int SPI_GETGESTUREVISUALIZATION() { return (int)8218L; }

    public static int SPI_SETGESTUREVISUALIZATION() { return (int)8219L; }

    public static int GESTUREVISUALIZATION_OFF() { return (int)0L; }

    public static int GESTUREVISUALIZATION_ON() { return (int)31L; }

    public static int GESTUREVISUALIZATION_TAP() { return (int)1L; }

    public static int GESTUREVISUALIZATION_DOUBLETAP() { return (int)2L; }

    public static int GESTUREVISUALIZATION_PRESSANDTAP() { return (int)4L; }

    public static int GESTUREVISUALIZATION_PRESSANDHOLD() { return (int)8L; }

    public static int GESTUREVISUALIZATION_RIGHTTAP() { return (int)16L; }

    public static int SPI_GETMOUSEWHEELROUTING() { return (int)8220L; }

    public static int SPI_SETMOUSEWHEELROUTING() { return (int)8221L; }

    public static int MOUSEWHEEL_ROUTING_FOCUS() { return (int)0L; }

    public static int MOUSEWHEEL_ROUTING_HYBRID() { return (int)1L; }

    public static int MOUSEWHEEL_ROUTING_MOUSE_POS() { return (int)2L; }

    public static int SPI_GETPENVISUALIZATION() { return (int)8222L; }

    public static int SPI_SETPENVISUALIZATION() { return (int)8223L; }

    public static int PENVISUALIZATION_ON() { return (int)35L; }

    public static int PENVISUALIZATION_OFF() { return (int)0L; }

    public static int PENVISUALIZATION_TAP() { return (int)1L; }

    public static int PENVISUALIZATION_DOUBLETAP() { return (int)2L; }

    public static int PENVISUALIZATION_CURSOR() { return (int)32L; }

    public static int SPI_GETPENARBITRATIONTYPE() { return (int)8224L; }

    public static int SPI_SETPENARBITRATIONTYPE() { return (int)8225L; }

    public static int PENARBITRATIONTYPE_NONE() { return (int)0L; }

    public static int PENARBITRATIONTYPE_WIN8() { return (int)1L; }

    public static int PENARBITRATIONTYPE_FIS() { return (int)2L; }

    public static int PENARBITRATIONTYPE_SPT() { return (int)3L; }

    public static int PENARBITRATIONTYPE_MAX() { return (int)4L; }

    public static int SPI_GETCARETTIMEOUT() { return (int)8226L; }

    public static int SPI_SETCARETTIMEOUT() { return (int)8227L; }

    public static int SPI_GETHANDEDNESS() { return (int)8228L; }

    public static int SPI_SETHANDEDNESS() { return (int)8229L; }

    public static int SPIF_UPDATEINIFILE() { return (int)1L; }

    public static int SPIF_SENDWININICHANGE() { return (int)2L; }

    public static int SERKF_SERIALKEYSON() { return (int)1L; }

    public static int SERKF_AVAILABLE() { return (int)2L; }

    public static int SERKF_INDICATOR() { return (int)4L; }

    public static int HCF_HIGHCONTRASTON() { return (int)1L; }

    public static int HCF_AVAILABLE() { return (int)2L; }

    public static int HCF_HOTKEYACTIVE() { return (int)4L; }

    public static int HCF_CONFIRMHOTKEY() { return (int)8L; }

    public static int HCF_HOTKEYSOUND() { return (int)16L; }

    public static int HCF_INDICATOR() { return (int)32L; }

    public static int HCF_HOTKEYAVAILABLE() { return (int)64L; }

    public static int HCF_LOGONDESKTOP() { return (int)256L; }

    public static int HCF_DEFAULTDESKTOP() { return (int)512L; }

    public static int HCF_OPTION_NOTHEMECHANGE() { return (int)4096L; }

    public static int CDS_UPDATEREGISTRY() { return (int)1L; }

    public static int CDS_TEST() { return (int)2L; }

    public static int CDS_FULLSCREEN() { return (int)4L; }

    public static int CDS_GLOBAL() { return (int)8L; }

    public static int CDS_SET_PRIMARY() { return (int)16L; }

    public static int CDS_VIDEOPARAMETERS() { return (int)32L; }

    public static int CDS_ENABLE_UNSAFE_MODES() { return (int)256L; }

    public static int CDS_DISABLE_UNSAFE_MODES() { return (int)512L; }

    public static int CDS_RESET() { return (int)1073741824L; }

    public static int CDS_RESET_EX() { return (int)536870912L; }

    public static int CDS_NORESET() { return (int)268435456L; }

    public static int VP_COMMAND_GET() { return (int)1L; }

    public static int VP_COMMAND_SET() { return (int)2L; }

    public static int VP_FLAGS_TV_MODE() { return (int)1L; }

    public static int VP_FLAGS_TV_STANDARD() { return (int)2L; }

    public static int VP_FLAGS_FLICKER() { return (int)4L; }

    public static int VP_FLAGS_OVERSCAN() { return (int)8L; }

    public static int VP_FLAGS_MAX_UNSCALED() { return (int)16L; }

    public static int VP_FLAGS_POSITION() { return (int)32L; }

    public static int VP_FLAGS_BRIGHTNESS() { return (int)64L; }

    public static int VP_FLAGS_CONTRAST() { return (int)128L; }

    public static int VP_FLAGS_COPYPROTECT() { return (int)256L; }

    public static int VP_MODE_WIN_GRAPHICS() { return (int)1L; }

    public static int VP_MODE_TV_PLAYBACK() { return (int)2L; }

    public static int VP_TV_STANDARD_NTSC_M() { return (int)1L; }

    public static int VP_TV_STANDARD_NTSC_M_J() { return (int)2L; }

    public static int VP_TV_STANDARD_PAL_B() { return (int)4L; }

    public static int VP_TV_STANDARD_PAL_D() { return (int)8L; }

    public static int VP_TV_STANDARD_PAL_H() { return (int)16L; }

    public static int VP_TV_STANDARD_PAL_I() { return (int)32L; }

    public static int VP_TV_STANDARD_PAL_M() { return (int)64L; }

    public static int VP_TV_STANDARD_PAL_N() { return (int)128L; }

    public static int VP_TV_STANDARD_SECAM_B() { return (int)256L; }

    public static int VP_TV_STANDARD_SECAM_D() { return (int)512L; }

    public static int VP_TV_STANDARD_SECAM_G() { return (int)1024L; }

    public static int VP_TV_STANDARD_SECAM_H() { return (int)2048L; }

    public static int VP_TV_STANDARD_SECAM_K() { return (int)4096L; }

    public static int VP_TV_STANDARD_SECAM_K1() { return (int)8192L; }

    public static int VP_TV_STANDARD_SECAM_L() { return (int)16384L; }

    public static int VP_TV_STANDARD_WIN_VGA() { return (int)32768L; }

    public static int VP_TV_STANDARD_NTSC_433() { return (int)65536L; }

    public static int VP_TV_STANDARD_PAL_G() { return (int)131072L; }

    public static int VP_TV_STANDARD_PAL_60() { return (int)262144L; }

    public static int VP_TV_STANDARD_SECAM_L1() { return (int)524288L; }

    public static int VP_CP_TYPE_APS_TRIGGER() { return (int)1L; }

    public static int VP_CP_TYPE_MACROVISION() { return (int)2L; }

    public static int VP_CP_CMD_ACTIVATE() { return (int)1L; }

    public static int VP_CP_CMD_DEACTIVATE() { return (int)2L; }

    public static int VP_CP_CMD_CHANGE() { return (int)4L; }

    public static int DISP_CHANGE_SUCCESSFUL() { return (int)0L; }

    public static int DISP_CHANGE_RESTART() { return (int)1L; }

    public static int EDS_RAWMODE() { return (int)2L; }

    public static int EDS_ROTATEDMODE() { return (int)4L; }

    public static int EDD_GET_DEVICE_INTERFACE_NAME() { return (int)1L; }

    public static int FKF_FILTERKEYSON() { return (int)1L; }

    public static int FKF_AVAILABLE() { return (int)2L; }

    public static int FKF_HOTKEYACTIVE() { return (int)4L; }

    public static int FKF_CONFIRMHOTKEY() { return (int)8L; }

    public static int FKF_HOTKEYSOUND() { return (int)16L; }

    public static int FKF_INDICATOR() { return (int)32L; }

    public static int FKF_CLICKON() { return (int)64L; }

    public static int SKF_STICKYKEYSON() { return (int)1L; }

    public static int SKF_AVAILABLE() { return (int)2L; }

    public static int SKF_HOTKEYACTIVE() { return (int)4L; }

    public static int SKF_CONFIRMHOTKEY() { return (int)8L; }

    public static int SKF_HOTKEYSOUND() { return (int)16L; }

    public static int SKF_INDICATOR() { return (int)32L; }

    public static int SKF_AUDIBLEFEEDBACK() { return (int)64L; }

    public static int SKF_TRISTATE() { return (int)128L; }

    public static int SKF_TWOKEYSOFF() { return (int)256L; }

    public static int SKF_LALTLATCHED() { return (int)268435456L; }

    public static int SKF_LCTLLATCHED() { return (int)67108864L; }

    public static int SKF_LSHIFTLATCHED() { return (int)16777216L; }

    public static int SKF_RALTLATCHED() { return (int)536870912L; }

    public static int SKF_RCTLLATCHED() { return (int)134217728L; }

    public static int SKF_RSHIFTLATCHED() { return (int)33554432L; }

    public static int SKF_LWINLATCHED() { return (int)1073741824L; }

    public static int SKF_LALTLOCKED() { return (int)1048576L; }

    public static int SKF_LCTLLOCKED() { return (int)262144L; }

    public static int SKF_LSHIFTLOCKED() { return (int)65536L; }

    public static int SKF_RALTLOCKED() { return (int)2097152L; }

    public static int SKF_RCTLLOCKED() { return (int)524288L; }

    public static int SKF_RSHIFTLOCKED() { return (int)131072L; }

    public static int SKF_LWINLOCKED() { return (int)4194304L; }

    public static int SKF_RWINLOCKED() { return (int)8388608L; }

    public static int MKF_MOUSEKEYSON() { return (int)1L; }

    public static int MKF_AVAILABLE() { return (int)2L; }

    public static int MKF_HOTKEYACTIVE() { return (int)4L; }

    public static int MKF_CONFIRMHOTKEY() { return (int)8L; }

    public static int MKF_HOTKEYSOUND() { return (int)16L; }

    public static int MKF_INDICATOR() { return (int)32L; }

    public static int MKF_MODIFIERS() { return (int)64L; }

    public static int MKF_REPLACENUMBERS() { return (int)128L; }

    public static int MKF_LEFTBUTTONSEL() { return (int)268435456L; }

    public static int MKF_RIGHTBUTTONSEL() { return (int)536870912L; }

    public static int MKF_LEFTBUTTONDOWN() { return (int)16777216L; }

    public static int MKF_RIGHTBUTTONDOWN() { return (int)33554432L; }

    public static int ATF_TIMEOUTON() { return (int)1L; }

    public static int ATF_ONOFFFEEDBACK() { return (int)2L; }

    public static int SSGF_NONE() { return (int)0L; }

    public static int SSGF_DISPLAY() { return (int)3L; }

    public static int SSTF_NONE() { return (int)0L; }

    public static int SSTF_CHARS() { return (int)1L; }

    public static int SSTF_BORDER() { return (int)2L; }

    public static int SSTF_DISPLAY() { return (int)3L; }

    public static int SSWF_NONE() { return (int)0L; }

    public static int SSWF_TITLE() { return (int)1L; }

    public static int SSWF_WINDOW() { return (int)2L; }

    public static int SSWF_DISPLAY() { return (int)3L; }

    public static int SSWF_CUSTOM() { return (int)4L; }

    public static int SSF_SOUNDSENTRYON() { return (int)1L; }

    public static int SSF_AVAILABLE() { return (int)2L; }

    public static int SSF_INDICATOR() { return (int)4L; }

    public static int TKF_TOGGLEKEYSON() { return (int)1L; }

    public static int TKF_AVAILABLE() { return (int)2L; }

    public static int TKF_HOTKEYACTIVE() { return (int)4L; }

    public static int TKF_CONFIRMHOTKEY() { return (int)8L; }

    public static int TKF_HOTKEYSOUND() { return (int)16L; }

    public static int TKF_INDICATOR() { return (int)32L; }

    public static int SLE_ERROR() { return (int)1L; }

    public static int SLE_MINORERROR() { return (int)2L; }

    public static int SLE_WARNING() { return (int)3L; }

    public static int MONITOR_DEFAULTTONULL() { return (int)0L; }

    public static int MONITOR_DEFAULTTOPRIMARY() { return (int)1L; }

    public static int MONITOR_DEFAULTTONEAREST() { return (int)2L; }

    public static int MONITORINFOF_PRIMARY() { return (int)1L; }

    public static int WINEVENT_OUTOFCONTEXT() { return (int)0L; }

    public static int WINEVENT_SKIPOWNTHREAD() { return (int)1L; }

    public static int WINEVENT_SKIPOWNPROCESS() { return (int)2L; }

    public static int WINEVENT_INCONTEXT() { return (int)4L; }

    public static int CHILDID_SELF() { return (int)0L; }

    public static int INDEXID_OBJECT() { return (int)0L; }

    public static int INDEXID_CONTAINER() { return (int)0L; }

    public static int EVENT_MIN() { return (int)1L; }

    public static int EVENT_MAX() { return (int)2147483647L; }

    public static int EVENT_SYSTEM_SOUND() { return (int)1L; }

    public static int EVENT_SYSTEM_ALERT() { return (int)2L; }

    public static int EVENT_SYSTEM_FOREGROUND() { return (int)3L; }

    public static int EVENT_SYSTEM_MENUSTART() { return (int)4L; }

    public static int EVENT_SYSTEM_MENUEND() { return (int)5L; }

    public static int EVENT_SYSTEM_MENUPOPUPSTART() { return (int)6L; }

    public static int EVENT_SYSTEM_MENUPOPUPEND() { return (int)7L; }

    public static int EVENT_SYSTEM_CAPTURESTART() { return (int)8L; }

    public static int EVENT_SYSTEM_CAPTUREEND() { return (int)9L; }

    public static int EVENT_SYSTEM_MOVESIZESTART() { return (int)10L; }

    public static int EVENT_SYSTEM_MOVESIZEEND() { return (int)11L; }

    public static int EVENT_SYSTEM_CONTEXTHELPSTART() { return (int)12L; }

    public static int EVENT_SYSTEM_CONTEXTHELPEND() { return (int)13L; }

    public static int EVENT_SYSTEM_DRAGDROPSTART() { return (int)14L; }

    public static int EVENT_SYSTEM_DRAGDROPEND() { return (int)15L; }

    public static int EVENT_SYSTEM_DIALOGSTART() { return (int)16L; }

    public static int EVENT_SYSTEM_DIALOGEND() { return (int)17L; }

    public static int EVENT_SYSTEM_SCROLLINGSTART() { return (int)18L; }

    public static int EVENT_SYSTEM_SCROLLINGEND() { return (int)19L; }

    public static int EVENT_SYSTEM_SWITCHSTART() { return (int)20L; }

    public static int EVENT_SYSTEM_SWITCHEND() { return (int)21L; }

    public static int EVENT_SYSTEM_MINIMIZESTART() { return (int)22L; }

    public static int EVENT_SYSTEM_MINIMIZEEND() { return (int)23L; }

    public static int EVENT_SYSTEM_DESKTOPSWITCH() { return (int)32L; }

    public static int EVENT_SYSTEM_SWITCHER_APPGRABBED() { return (int)36L; }

    public static int EVENT_SYSTEM_SWITCHER_APPOVERTARGET() { return (int)37L; }

    public static int EVENT_SYSTEM_SWITCHER_APPDROPPED() { return (int)38L; }

    public static int EVENT_SYSTEM_SWITCHER_CANCELLED() { return (int)39L; }

    public static int EVENT_SYSTEM_IME_KEY_NOTIFICATION() { return (int)41L; }

    public static int EVENT_SYSTEM_END() { return (int)255L; }

    public static int EVENT_OEM_DEFINED_START() { return (int)257L; }

    public static int EVENT_OEM_DEFINED_END() { return (int)511L; }

    public static int EVENT_UIA_EVENTID_START() { return (int)19968L; }

    public static int EVENT_UIA_EVENTID_END() { return (int)20223L; }

    public static int EVENT_UIA_PROPID_START() { return (int)29952L; }

    public static int EVENT_UIA_PROPID_END() { return (int)30207L; }

    public static int EVENT_CONSOLE_CARET() { return (int)16385L; }

    public static int EVENT_CONSOLE_UPDATE_REGION() { return (int)16386L; }

    public static int EVENT_CONSOLE_UPDATE_SIMPLE() { return (int)16387L; }

    public static int EVENT_CONSOLE_UPDATE_SCROLL() { return (int)16388L; }

    public static int EVENT_CONSOLE_LAYOUT() { return (int)16389L; }

    public static int EVENT_CONSOLE_START_APPLICATION() { return (int)16390L; }

    public static int EVENT_CONSOLE_END_APPLICATION() { return (int)16391L; }

    public static int CONSOLE_APPLICATION_16BIT() { return (int)0L; }

    public static int CONSOLE_CARET_SELECTION() { return (int)1L; }

    public static int CONSOLE_CARET_VISIBLE() { return (int)2L; }

    public static int EVENT_CONSOLE_END() { return (int)16639L; }

    public static int EVENT_OBJECT_CREATE() { return (int)32768L; }

    public static int EVENT_OBJECT_DESTROY() { return (int)32769L; }

    public static int EVENT_OBJECT_SHOW() { return (int)32770L; }

    public static int EVENT_OBJECT_HIDE() { return (int)32771L; }

    public static int EVENT_OBJECT_REORDER() { return (int)32772L; }

    public static int EVENT_OBJECT_FOCUS() { return (int)32773L; }

    public static int EVENT_OBJECT_SELECTION() { return (int)32774L; }

    public static int EVENT_OBJECT_SELECTIONADD() { return (int)32775L; }

    public static int EVENT_OBJECT_SELECTIONREMOVE() { return (int)32776L; }

    public static int EVENT_OBJECT_SELECTIONWITHIN() { return (int)32777L; }

    public static int EVENT_OBJECT_STATECHANGE() { return (int)32778L; }

    public static int EVENT_OBJECT_LOCATIONCHANGE() { return (int)32779L; }

    public static int EVENT_OBJECT_NAMECHANGE() { return (int)32780L; }

    public static int EVENT_OBJECT_DESCRIPTIONCHANGE() { return (int)32781L; }

    public static int EVENT_OBJECT_VALUECHANGE() { return (int)32782L; }

    public static int EVENT_OBJECT_PARENTCHANGE() { return (int)32783L; }

    public static int EVENT_OBJECT_HELPCHANGE() { return (int)32784L; }

    public static int EVENT_OBJECT_DEFACTIONCHANGE() { return (int)32785L; }

    public static int EVENT_OBJECT_ACCELERATORCHANGE() { return (int)32786L; }

    public static int EVENT_OBJECT_INVOKED() { return (int)32787L; }

    public static int EVENT_OBJECT_TEXTSELECTIONCHANGED() { return (int)32788L; }

    public static int EVENT_OBJECT_CONTENTSCROLLED() { return (int)32789L; }

    public static int EVENT_SYSTEM_ARRANGMENTPREVIEW() { return (int)32790L; }

    public static int EVENT_OBJECT_CLOAKED() { return (int)32791L; }

    public static int EVENT_OBJECT_UNCLOAKED() { return (int)32792L; }

    public static int EVENT_OBJECT_LIVEREGIONCHANGED() { return (int)32793L; }

    public static int EVENT_OBJECT_HOSTEDOBJECTSINVALIDATED() { return (int)32800L; }

    public static int EVENT_OBJECT_DRAGSTART() { return (int)32801L; }

    public static int EVENT_OBJECT_DRAGCANCEL() { return (int)32802L; }

    public static int EVENT_OBJECT_DRAGCOMPLETE() { return (int)32803L; }

    public static int EVENT_OBJECT_DRAGENTER() { return (int)32804L; }

    public static int EVENT_OBJECT_DRAGLEAVE() { return (int)32805L; }

    public static int EVENT_OBJECT_DRAGDROPPED() { return (int)32806L; }

    public static int EVENT_OBJECT_IME_SHOW() { return (int)32807L; }

    public static int EVENT_OBJECT_IME_HIDE() { return (int)32808L; }

    public static int EVENT_OBJECT_IME_CHANGE() { return (int)32809L; }

    public static int EVENT_OBJECT_TEXTEDIT_CONVERSIONTARGETCHANGED() { return (int)32816L; }

    public static int EVENT_OBJECT_END() { return (int)33023L; }

    public static int EVENT_AIA_START() { return (int)40960L; }

    public static int EVENT_AIA_END() { return (int)45055L; }

    public static int SOUND_SYSTEM_STARTUP() { return (int)1L; }

    public static int SOUND_SYSTEM_SHUTDOWN() { return (int)2L; }

    public static int SOUND_SYSTEM_BEEP() { return (int)3L; }

    public static int SOUND_SYSTEM_ERROR() { return (int)4L; }

    public static int SOUND_SYSTEM_QUESTION() { return (int)5L; }

    public static int SOUND_SYSTEM_WARNING() { return (int)6L; }

    public static int SOUND_SYSTEM_INFORMATION() { return (int)7L; }

    public static int SOUND_SYSTEM_MAXIMIZE() { return (int)8L; }

    public static int SOUND_SYSTEM_MINIMIZE() { return (int)9L; }

    public static int SOUND_SYSTEM_RESTOREUP() { return (int)10L; }

    public static int SOUND_SYSTEM_RESTOREDOWN() { return (int)11L; }

    public static int SOUND_SYSTEM_APPSTART() { return (int)12L; }

    public static int SOUND_SYSTEM_FAULT() { return (int)13L; }

    public static int SOUND_SYSTEM_APPEND() { return (int)14L; }

    public static int SOUND_SYSTEM_MENUCOMMAND() { return (int)15L; }

    public static int SOUND_SYSTEM_MENUPOPUP() { return (int)16L; }

    public static int CSOUND_SYSTEM() { return (int)16L; }

    public static int ALERT_SYSTEM_INFORMATIONAL() { return (int)1L; }

    public static int ALERT_SYSTEM_WARNING() { return (int)2L; }

    public static int ALERT_SYSTEM_ERROR() { return (int)3L; }

    public static int ALERT_SYSTEM_QUERY() { return (int)4L; }

    public static int ALERT_SYSTEM_CRITICAL() { return (int)5L; }

    public static int CALERT_SYSTEM() { return (int)6L; }

    public static int GUI_CARETBLINKING() { return (int)1L; }

    public static int GUI_INMOVESIZE() { return (int)2L; }

    public static int GUI_INMENUMODE() { return (int)4L; }

    public static int GUI_SYSTEMMENUMODE() { return (int)8L; }

    public static int GUI_POPUPMENUMODE() { return (int)16L; }

    public static int GUI_16BITTASK() { return (int)0L; }

    public static int USER_DEFAULT_SCREEN_DPI() { return (int)96L; }

    public static int STATE_SYSTEM_UNAVAILABLE() { return (int)1L; }

    public static int STATE_SYSTEM_SELECTED() { return (int)2L; }

    public static int STATE_SYSTEM_FOCUSED() { return (int)4L; }

    public static int STATE_SYSTEM_PRESSED() { return (int)8L; }

    public static int STATE_SYSTEM_CHECKED() { return (int)16L; }

    public static int STATE_SYSTEM_MIXED() { return (int)32L; }

    public static int STATE_SYSTEM_READONLY() { return (int)64L; }

    public static int STATE_SYSTEM_HOTTRACKED() { return (int)128L; }

    public static int STATE_SYSTEM_DEFAULT() { return (int)256L; }

    public static int STATE_SYSTEM_EXPANDED() { return (int)512L; }

    public static int STATE_SYSTEM_COLLAPSED() { return (int)1024L; }

    public static int STATE_SYSTEM_BUSY() { return (int)2048L; }

    public static int STATE_SYSTEM_FLOATING() { return (int)4096L; }

    public static int STATE_SYSTEM_MARQUEED() { return (int)8192L; }

    public static int STATE_SYSTEM_ANIMATED() { return (int)16384L; }

    public static int STATE_SYSTEM_INVISIBLE() { return (int)32768L; }

    public static int STATE_SYSTEM_OFFSCREEN() { return (int)65536L; }

    public static int STATE_SYSTEM_SIZEABLE() { return (int)131072L; }

    public static int STATE_SYSTEM_MOVEABLE() { return (int)262144L; }

    public static int STATE_SYSTEM_SELFVOICING() { return (int)524288L; }

    public static int STATE_SYSTEM_FOCUSABLE() { return (int)1048576L; }

    public static int STATE_SYSTEM_SELECTABLE() { return (int)2097152L; }

    public static int STATE_SYSTEM_LINKED() { return (int)4194304L; }

    public static int STATE_SYSTEM_TRAVERSED() { return (int)8388608L; }

    public static int STATE_SYSTEM_MULTISELECTABLE() { return (int)16777216L; }

    public static int STATE_SYSTEM_EXTSELECTABLE() { return (int)33554432L; }

    public static int STATE_SYSTEM_ALERT_LOW() { return (int)67108864L; }

    public static int STATE_SYSTEM_ALERT_MEDIUM() { return (int)134217728L; }

    public static int STATE_SYSTEM_ALERT_HIGH() { return (int)268435456L; }

    public static int STATE_SYSTEM_PROTECTED() { return (int)536870912L; }

    public static int STATE_SYSTEM_VALID() { return (int)1073741823L; }

    public static int CCHILDREN_TITLEBAR() { return (int)5L; }

    public static int CCHILDREN_SCROLLBAR() { return (int)5L; }

    public static int CURSOR_SHOWING() { return (int)1L; }

    public static int CURSOR_SUPPRESSED() { return (int)2L; }

    public static int WS_ACTIVECAPTION() { return (int)1L; }

    public static int GA_PARENT() { return (int)1L; }

    public static int GA_ROOT() { return (int)2L; }

    public static int GA_ROOTOWNER() { return (int)3L; }

    public static int RIM_INPUT() { return (int)0L; }

    public static int RIM_INPUTSINK() { return (int)1L; }

    public static int RIM_TYPEMOUSE() { return (int)0L; }

    public static int RIM_TYPEKEYBOARD() { return (int)1L; }

    public static int RIM_TYPEHID() { return (int)2L; }

    public static int RIM_TYPEMAX() { return (int)2L; }

    public static int RI_MOUSE_LEFT_BUTTON_DOWN() { return (int)1L; }

    public static int RI_MOUSE_LEFT_BUTTON_UP() { return (int)2L; }

    public static int RI_MOUSE_RIGHT_BUTTON_DOWN() { return (int)4L; }

    public static int RI_MOUSE_RIGHT_BUTTON_UP() { return (int)8L; }

    public static int RI_MOUSE_MIDDLE_BUTTON_DOWN() { return (int)16L; }

    public static int RI_MOUSE_MIDDLE_BUTTON_UP() { return (int)32L; }

    public static int RI_MOUSE_BUTTON_4_DOWN() { return (int)64L; }

    public static int RI_MOUSE_BUTTON_4_UP() { return (int)128L; }

    public static int RI_MOUSE_BUTTON_5_DOWN() { return (int)256L; }

    public static int RI_MOUSE_BUTTON_5_UP() { return (int)512L; }

    public static int RI_MOUSE_WHEEL() { return (int)1024L; }

    public static int RI_MOUSE_HWHEEL() { return (int)2048L; }

    public static int MOUSE_MOVE_RELATIVE() { return (int)0L; }

    public static int MOUSE_MOVE_ABSOLUTE() { return (int)1L; }

    public static int MOUSE_VIRTUAL_DESKTOP() { return (int)2L; }

    public static int MOUSE_ATTRIBUTES_CHANGED() { return (int)4L; }

    public static int MOUSE_MOVE_NOCOALESCE() { return (int)8L; }

    public static int KEYBOARD_OVERRUN_MAKE_CODE() { return (int)255L; }

    public static int RI_KEY_MAKE() { return (int)0L; }

    public static int RI_KEY_BREAK() { return (int)1L; }

    public static int RI_KEY_E0() { return (int)2L; }

    public static int RI_KEY_E1() { return (int)4L; }

    public static int RI_KEY_TERMSRV_SET_LED() { return (int)8L; }

    public static int RI_KEY_TERMSRV_SHADOW() { return (int)16L; }

    public static int RID_INPUT() { return (int)268435459L; }

    public static int RID_HEADER() { return (int)268435461L; }

    public static int RIDI_PREPARSEDDATA() { return (int)536870917L; }

    public static int RIDI_DEVICENAME() { return (int)536870919L; }

    public static int RIDI_DEVICEINFO() { return (int)536870923L; }

    public static int RIDEV_REMOVE() { return (int)1L; }

    public static int RIDEV_EXCLUDE() { return (int)16L; }

    public static int RIDEV_PAGEONLY() { return (int)32L; }

    public static int RIDEV_NOLEGACY() { return (int)48L; }

    public static int RIDEV_INPUTSINK() { return (int)256L; }

    public static int RIDEV_CAPTUREMOUSE() { return (int)512L; }

    public static int RIDEV_NOHOTKEYS() { return (int)512L; }

    public static int RIDEV_APPKEYS() { return (int)1024L; }

    public static int RIDEV_EXINPUTSINK() { return (int)4096L; }

    public static int RIDEV_DEVNOTIFY() { return (int)8192L; }

    public static int RIDEV_EXMODEMASK() { return (int)240L; }

    public static int GIDC_ARRIVAL() { return (int)1L; }

    public static int GIDC_REMOVAL() { return (int)2L; }

    public static int POINTER_DEVICE_PRODUCT_STRING_MAX() { return (int)520L; }

    public static int PDC_ARRIVAL() { return (int)1L; }

    public static int PDC_REMOVAL() { return (int)2L; }

    public static int PDC_ORIENTATION_0() { return (int)4L; }

    public static int PDC_ORIENTATION_90() { return (int)8L; }

    public static int PDC_ORIENTATION_180() { return (int)16L; }

    public static int PDC_ORIENTATION_270() { return (int)32L; }

    public static int PDC_MODE_DEFAULT() { return (int)64L; }

    public static int PDC_MODE_CENTERED() { return (int)128L; }

    public static int PDC_MAPPING_CHANGE() { return (int)256L; }

    public static int PDC_RESOLUTION() { return (int)512L; }

    public static int PDC_ORIGIN() { return (int)1024L; }

    public static int PDC_MODE_ASPECTRATIOPRESERVED() { return (int)2048L; }

    public static int MSGFLT_ADD() { return (int)1L; }

    public static int MSGFLT_REMOVE() { return (int)2L; }

    public static int GF_BEGIN() { return (int)1L; }

    public static int GF_INERTIA() { return (int)2L; }

    public static int GF_END() { return (int)4L; }

    public static int GID_BEGIN() { return (int)1L; }

    public static int GID_END() { return (int)2L; }

    public static int GID_ZOOM() { return (int)3L; }

    public static int GID_PAN() { return (int)4L; }

    public static int GID_ROTATE() { return (int)5L; }

    public static int GID_TWOFINGERTAP() { return (int)6L; }

    public static int GID_PRESSANDTAP() { return (int)7L; }

    public static int GC_ALLGESTURES() { return (int)1L; }

    public static int GC_ZOOM() { return (int)1L; }

    public static int GC_PAN() { return (int)1L; }

    public static int GC_PAN_WITH_SINGLE_FINGER_VERTICALLY() { return (int)2L; }

    public static int GC_PAN_WITH_SINGLE_FINGER_HORIZONTALLY() { return (int)4L; }

    public static int GC_PAN_WITH_GUTTER() { return (int)8L; }

    public static int GC_PAN_WITH_INERTIA() { return (int)16L; }

    public static int GC_ROTATE() { return (int)1L; }

    public static int GC_TWOFINGERTAP() { return (int)1L; }

    public static int GC_PRESSANDTAP() { return (int)1L; }

    public static int GESTURECONFIGMAXCOUNT() { return (int)256L; }

    public static int GCF_INCLUDE_ANCESTORS() { return (int)1L; }

    public static int NID_INTEGRATED_TOUCH() { return (int)1L; }

    public static int NID_EXTERNAL_TOUCH() { return (int)2L; }

    public static int NID_INTEGRATED_PEN() { return (int)4L; }

    public static int NID_EXTERNAL_PEN() { return (int)8L; }

    public static int NID_MULTI_INPUT() { return (int)64L; }

    public static int NID_READY() { return (int)128L; }

    public static int MAX_STR_BLOCKREASON() { return (int)256L; }

    public static int MAX_LEADBYTES() { return (int)12L; }

    public static int MAX_DEFAULTCHAR() { return (int)2L; }

    public static int HIGH_SURROGATE_START() { return (int)55296L; }

    public static int HIGH_SURROGATE_END() { return (int)56319L; }

    public static int LOW_SURROGATE_START() { return (int)56320L; }

    public static int LOW_SURROGATE_END() { return (int)57343L; }

    public static int MB_PRECOMPOSED() { return (int)1L; }

    public static int MB_COMPOSITE() { return (int)2L; }

    public static int MB_USEGLYPHCHARS() { return (int)4L; }

    public static int MB_ERR_INVALID_CHARS() { return (int)8L; }

    public static int WC_COMPOSITECHECK() { return (int)512L; }

    public static int WC_DISCARDNS() { return (int)16L; }

    public static int WC_SEPCHARS() { return (int)32L; }

    public static int WC_DEFAULTCHAR() { return (int)64L; }

    public static int WC_ERR_INVALID_CHARS() { return (int)128L; }

    public static int WC_NO_BEST_FIT_CHARS() { return (int)1024L; }

    public static int CT_CTYPE1() { return (int)1L; }

    public static int CT_CTYPE2() { return (int)2L; }

    public static int CT_CTYPE3() { return (int)4L; }

    public static int C1_UPPER() { return (int)1L; }

    public static int C1_LOWER() { return (int)2L; }

    public static int C1_DIGIT() { return (int)4L; }

    public static int C1_SPACE() { return (int)8L; }

    public static int C1_PUNCT() { return (int)16L; }

    public static int C1_CNTRL() { return (int)32L; }

    public static int C1_BLANK() { return (int)64L; }

    public static int C1_XDIGIT() { return (int)128L; }

    public static int C1_ALPHA() { return (int)256L; }

    public static int C1_DEFINED() { return (int)512L; }

    public static int C2_LEFTTORIGHT() { return (int)1L; }

    public static int C2_RIGHTTOLEFT() { return (int)2L; }

    public static int C2_EUROPENUMBER() { return (int)3L; }

    public static int C2_EUROPESEPARATOR() { return (int)4L; }

    public static int C2_EUROPETERMINATOR() { return (int)5L; }

    public static int C2_ARABICNUMBER() { return (int)6L; }

    public static int C2_COMMONSEPARATOR() { return (int)7L; }

    public static int C2_BLOCKSEPARATOR() { return (int)8L; }

    public static int C2_SEGMENTSEPARATOR() { return (int)9L; }

    public static int C2_WHITESPACE() { return (int)10L; }

    public static int C2_OTHERNEUTRAL() { return (int)11L; }

    public static int C2_NOTAPPLICABLE() { return (int)0L; }

    public static int C3_NONSPACING() { return (int)1L; }

    public static int C3_DIACRITIC() { return (int)2L; }

    public static int C3_VOWELMARK() { return (int)4L; }

    public static int C3_SYMBOL() { return (int)8L; }

    public static int C3_KATAKANA() { return (int)16L; }

    public static int C3_HIRAGANA() { return (int)32L; }

    public static int C3_HALFWIDTH() { return (int)64L; }

    public static int C3_FULLWIDTH() { return (int)128L; }

    public static int C3_IDEOGRAPH() { return (int)256L; }

    public static int C3_KASHIDA() { return (int)512L; }

    public static int C3_LEXICAL() { return (int)1024L; }

    public static int C3_HIGHSURROGATE() { return (int)2048L; }

    public static int C3_LOWSURROGATE() { return (int)4096L; }

    public static int C3_ALPHA() { return (int)32768L; }

    public static int C3_NOTAPPLICABLE() { return (int)0L; }

    public static int NORM_IGNORECASE() { return (int)1L; }

    public static int NORM_IGNORENONSPACE() { return (int)2L; }

    public static int NORM_IGNORESYMBOLS() { return (int)4L; }

    public static int LINGUISTIC_IGNORECASE() { return (int)16L; }

    public static int LINGUISTIC_IGNOREDIACRITIC() { return (int)32L; }

    public static int NORM_IGNOREKANATYPE() { return (int)65536L; }

    public static int NORM_IGNOREWIDTH() { return (int)131072L; }

    public static int NORM_LINGUISTIC_CASING() { return (int)134217728L; }

    public static int MAP_FOLDCZONE() { return (int)16L; }

    public static int MAP_PRECOMPOSED() { return (int)32L; }

    public static int MAP_COMPOSITE() { return (int)64L; }

    public static int MAP_FOLDDIGITS() { return (int)128L; }

    public static int MAP_EXPAND_LIGATURES() { return (int)8192L; }

    public static int LCMAP_LOWERCASE() { return (int)256L; }

    public static int LCMAP_UPPERCASE() { return (int)512L; }

    public static int LCMAP_TITLECASE() { return (int)768L; }

    public static int LCMAP_SORTKEY() { return (int)1024L; }

    public static int LCMAP_BYTEREV() { return (int)2048L; }

    public static int LCMAP_HIRAGANA() { return (int)1048576L; }

    public static int LCMAP_KATAKANA() { return (int)2097152L; }

    public static int LCMAP_HALFWIDTH() { return (int)4194304L; }

    public static int LCMAP_FULLWIDTH() { return (int)8388608L; }

    public static int LCMAP_LINGUISTIC_CASING() { return (int)16777216L; }

    public static int LCMAP_SIMPLIFIED_CHINESE() { return (int)33554432L; }

    public static int LCMAP_TRADITIONAL_CHINESE() { return (int)67108864L; }

    public static int LCMAP_SORTHANDLE() { return (int)536870912L; }

    public static int LCMAP_HASH() { return (int)262144L; }

    public static int FIND_STARTSWITH() { return (int)1048576L; }

    public static int FIND_ENDSWITH() { return (int)2097152L; }

    public static int FIND_FROMSTART() { return (int)4194304L; }

    public static int FIND_FROMEND() { return (int)8388608L; }

    public static int LGRPID_INSTALLED() { return (int)1L; }

    public static int LGRPID_SUPPORTED() { return (int)2L; }

    public static int LCID_INSTALLED() { return (int)1L; }

    public static int LCID_SUPPORTED() { return (int)2L; }

    public static int LCID_ALTERNATE_SORTS() { return (int)4L; }

    public static int LOCALE_ALL() { return (int)0L; }

    public static int LOCALE_WINDOWS() { return (int)1L; }

    public static int LOCALE_SUPPLEMENTAL() { return (int)2L; }

    public static int LOCALE_ALTERNATE_SORTS() { return (int)4L; }

    public static int LOCALE_REPLACEMENT() { return (int)8L; }

    public static int LOCALE_NEUTRALDATA() { return (int)16L; }

    public static int LOCALE_SPECIFICDATA() { return (int)32L; }

    public static int CP_INSTALLED() { return (int)1L; }

    public static int CP_SUPPORTED() { return (int)2L; }

    public static int SORT_STRINGSORT() { return (int)4096L; }

    public static int SORT_DIGITSASNUMBERS() { return (int)8L; }

    public static int CSTR_LESS_THAN() { return (int)1L; }

    public static int CSTR_EQUAL() { return (int)2L; }

    public static int CSTR_GREATER_THAN() { return (int)3L; }

    public static int CP_ACP() { return (int)0L; }

    public static int CP_OEMCP() { return (int)1L; }

    public static int CP_MACCP() { return (int)2L; }

    public static int CP_THREAD_ACP() { return (int)3L; }

    public static int CP_SYMBOL() { return (int)42L; }

    public static int CP_UTF7() { return (int)65000L; }

    public static int CP_UTF8() { return (int)65001L; }

    public static int CTRY_DEFAULT() { return (int)0L; }

    public static int CTRY_ALBANIA() { return (int)355L; }

    public static int CTRY_ALGERIA() { return (int)213L; }

    public static int CTRY_ARGENTINA() { return (int)54L; }

    public static int CTRY_ARMENIA() { return (int)374L; }

    public static int CTRY_AUSTRALIA() { return (int)61L; }

    public static int CTRY_AUSTRIA() { return (int)43L; }

    public static int CTRY_AZERBAIJAN() { return (int)994L; }

    public static int CTRY_BAHRAIN() { return (int)973L; }

    public static int CTRY_BELARUS() { return (int)375L; }

    public static int CTRY_BELGIUM() { return (int)32L; }

    public static int CTRY_BELIZE() { return (int)501L; }

    public static int CTRY_BOLIVIA() { return (int)591L; }

    public static int CTRY_BRAZIL() { return (int)55L; }

    public static int CTRY_BRUNEI_DARUSSALAM() { return (int)673L; }

    public static int CTRY_BULGARIA() { return (int)359L; }

    public static int CTRY_CANADA() { return (int)2L; }

    public static int CTRY_CARIBBEAN() { return (int)1L; }

    public static int CTRY_CHILE() { return (int)56L; }

    public static int CTRY_COLOMBIA() { return (int)57L; }

    public static int CTRY_COSTA_RICA() { return (int)506L; }

    public static int CTRY_CROATIA() { return (int)385L; }

    public static int CTRY_CZECH() { return (int)420L; }

    public static int CTRY_DENMARK() { return (int)45L; }

    public static int CTRY_DOMINICAN_REPUBLIC() { return (int)1L; }

    public static int CTRY_ECUADOR() { return (int)593L; }

    public static int CTRY_EGYPT() { return (int)20L; }

    public static int CTRY_EL_SALVADOR() { return (int)503L; }

    public static int CTRY_ESTONIA() { return (int)372L; }

    public static int CTRY_FAEROE_ISLANDS() { return (int)298L; }

    public static int CTRY_FINLAND() { return (int)358L; }

    public static int CTRY_FRANCE() { return (int)33L; }

    public static int CTRY_GEORGIA() { return (int)995L; }

    public static int CTRY_GERMANY() { return (int)49L; }

    public static int CTRY_GREECE() { return (int)30L; }

    public static int CTRY_GUATEMALA() { return (int)502L; }

    public static int CTRY_HONDURAS() { return (int)504L; }

    public static int CTRY_HONG_KONG() { return (int)852L; }

    public static int CTRY_HUNGARY() { return (int)36L; }

    public static int CTRY_ICELAND() { return (int)354L; }

    public static int CTRY_INDIA() { return (int)91L; }

    public static int CTRY_INDONESIA() { return (int)62L; }

    public static int CTRY_IRAN() { return (int)981L; }

    public static int CTRY_IRAQ() { return (int)964L; }

    public static int CTRY_IRELAND() { return (int)353L; }

    public static int CTRY_ISRAEL() { return (int)972L; }

    public static int CTRY_ITALY() { return (int)39L; }

    public static int CTRY_JAMAICA() { return (int)1L; }

    public static int CTRY_JAPAN() { return (int)81L; }

    public static int CTRY_JORDAN() { return (int)962L; }

    public static int CTRY_KAZAKSTAN() { return (int)7L; }

    public static int CTRY_KENYA() { return (int)254L; }

    public static int CTRY_KUWAIT() { return (int)965L; }

    public static int CTRY_KYRGYZSTAN() { return (int)996L; }

    public static int CTRY_LATVIA() { return (int)371L; }

    public static int CTRY_LEBANON() { return (int)961L; }

    public static int CTRY_LIBYA() { return (int)218L; }

    public static int CTRY_LIECHTENSTEIN() { return (int)41L; }

    public static int CTRY_LITHUANIA() { return (int)370L; }

    public static int CTRY_LUXEMBOURG() { return (int)352L; }

    public static int CTRY_MACAU() { return (int)853L; }

    public static int CTRY_MACEDONIA() { return (int)389L; }

    public static int CTRY_MALAYSIA() { return (int)60L; }

    public static int CTRY_MALDIVES() { return (int)960L; }

    public static int CTRY_MEXICO() { return (int)52L; }

    public static int CTRY_MONACO() { return (int)33L; }

    public static int CTRY_MONGOLIA() { return (int)976L; }

    public static int CTRY_MOROCCO() { return (int)212L; }

    public static int CTRY_NETHERLANDS() { return (int)31L; }

    public static int CTRY_NEW_ZEALAND() { return (int)64L; }

    public static int CTRY_NICARAGUA() { return (int)505L; }

    public static int CTRY_NORWAY() { return (int)47L; }

    public static int CTRY_OMAN() { return (int)968L; }

    public static int CTRY_PAKISTAN() { return (int)92L; }

    public static int CTRY_PANAMA() { return (int)507L; }

    public static int CTRY_PARAGUAY() { return (int)595L; }

    public static int CTRY_PERU() { return (int)51L; }

    public static int CTRY_PHILIPPINES() { return (int)63L; }

    public static int CTRY_POLAND() { return (int)48L; }

    public static int CTRY_PORTUGAL() { return (int)351L; }

    public static int CTRY_PRCHINA() { return (int)86L; }

    public static int CTRY_PUERTO_RICO() { return (int)1L; }

    public static int CTRY_QATAR() { return (int)974L; }

    public static int CTRY_ROMANIA() { return (int)40L; }

    public static int CTRY_RUSSIA() { return (int)7L; }

    public static int CTRY_SAUDI_ARABIA() { return (int)966L; }

    public static int CTRY_SERBIA() { return (int)381L; }

    public static int CTRY_SINGAPORE() { return (int)65L; }

    public static int CTRY_SLOVAK() { return (int)421L; }

    public static int CTRY_SLOVENIA() { return (int)386L; }

    public static int CTRY_SOUTH_AFRICA() { return (int)27L; }

    public static int CTRY_SOUTH_KOREA() { return (int)82L; }

    public static int CTRY_SPAIN() { return (int)34L; }

    public static int CTRY_SWEDEN() { return (int)46L; }

    public static int CTRY_SWITZERLAND() { return (int)41L; }

    public static int CTRY_SYRIA() { return (int)963L; }

    public static int CTRY_TAIWAN() { return (int)886L; }

    public static int CTRY_TATARSTAN() { return (int)7L; }

    public static int CTRY_THAILAND() { return (int)66L; }

    public static int CTRY_TRINIDAD_Y_TOBAGO() { return (int)1L; }

    public static int CTRY_TUNISIA() { return (int)216L; }

    public static int CTRY_TURKEY() { return (int)90L; }

    public static int CTRY_UAE() { return (int)971L; }

    public static int CTRY_UKRAINE() { return (int)380L; }

    public static int CTRY_UNITED_KINGDOM() { return (int)44L; }

    public static int CTRY_UNITED_STATES() { return (int)1L; }

    public static int CTRY_URUGUAY() { return (int)598L; }

    public static int CTRY_UZBEKISTAN() { return (int)7L; }

    public static int CTRY_VENEZUELA() { return (int)58L; }

    public static int CTRY_VIET_NAM() { return (int)84L; }

    public static int CTRY_YEMEN() { return (int)967L; }

    public static int CTRY_ZIMBABWE() { return (int)263L; }

    public static int LOCALE_USE_CP_ACP() { return (int)1073741824L; }

    public static int LOCALE_RETURN_NUMBER() { return (int)536870912L; }

    public static int LOCALE_RETURN_GENITIVE_NAMES() { return (int)268435456L; }

    public static int LOCALE_ALLOW_NEUTRAL_NAMES() { return (int)134217728L; }

    public static int LOCALE_SLOCALIZEDDISPLAYNAME() { return (int)2L; }

    public static int LOCALE_SENGLISHDISPLAYNAME() { return (int)114L; }

    public static int LOCALE_SNATIVEDISPLAYNAME() { return (int)115L; }

    public static int LOCALE_SLOCALIZEDLANGUAGENAME() { return (int)111L; }

    public static int LOCALE_SENGLISHLANGUAGENAME() { return (int)4097L; }

    public static int LOCALE_SNATIVELANGUAGENAME() { return (int)4L; }

    public static int LOCALE_SLOCALIZEDCOUNTRYNAME() { return (int)6L; }

    public static int LOCALE_SENGLISHCOUNTRYNAME() { return (int)4098L; }

    public static int LOCALE_SNATIVECOUNTRYNAME() { return (int)8L; }

    public static int LOCALE_IDIALINGCODE() { return (int)5L; }

    public static int LOCALE_SLIST() { return (int)12L; }

    public static int LOCALE_IMEASURE() { return (int)13L; }

    public static int LOCALE_SDECIMAL() { return (int)14L; }

    public static int LOCALE_STHOUSAND() { return (int)15L; }

    public static int LOCALE_SGROUPING() { return (int)16L; }

    public static int LOCALE_IDIGITS() { return (int)17L; }

    public static int LOCALE_ILZERO() { return (int)18L; }

    public static int LOCALE_INEGNUMBER() { return (int)4112L; }

    public static int LOCALE_SNATIVEDIGITS() { return (int)19L; }

    public static int LOCALE_SCURRENCY() { return (int)20L; }

    public static int LOCALE_SINTLSYMBOL() { return (int)21L; }

    public static int LOCALE_SMONDECIMALSEP() { return (int)22L; }

    public static int LOCALE_SMONTHOUSANDSEP() { return (int)23L; }

    public static int LOCALE_SMONGROUPING() { return (int)24L; }

    public static int LOCALE_ICURRDIGITS() { return (int)25L; }

    public static int LOCALE_ICURRENCY() { return (int)27L; }

    public static int LOCALE_INEGCURR() { return (int)28L; }

    public static int LOCALE_SSHORTDATE() { return (int)31L; }

    public static int LOCALE_SLONGDATE() { return (int)32L; }

    public static int LOCALE_STIMEFORMAT() { return (int)4099L; }

    public static int LOCALE_SAM() { return (int)40L; }

    public static int LOCALE_SPM() { return (int)41L; }

    public static int LOCALE_ICALENDARTYPE() { return (int)4105L; }

    public static int LOCALE_IOPTIONALCALENDAR() { return (int)4107L; }

    public static int LOCALE_IFIRSTDAYOFWEEK() { return (int)4108L; }

    public static int LOCALE_IFIRSTWEEKOFYEAR() { return (int)4109L; }

    public static int LOCALE_SDAYNAME1() { return (int)42L; }

    public static int LOCALE_SDAYNAME2() { return (int)43L; }

    public static int LOCALE_SDAYNAME3() { return (int)44L; }

    public static int LOCALE_SDAYNAME4() { return (int)45L; }

    public static int LOCALE_SDAYNAME5() { return (int)46L; }

    public static int LOCALE_SDAYNAME6() { return (int)47L; }

    public static int LOCALE_SDAYNAME7() { return (int)48L; }

    public static int LOCALE_SABBREVDAYNAME1() { return (int)49L; }

    public static int LOCALE_SABBREVDAYNAME2() { return (int)50L; }

    public static int LOCALE_SABBREVDAYNAME3() { return (int)51L; }

    public static int LOCALE_SABBREVDAYNAME4() { return (int)52L; }

    public static int LOCALE_SABBREVDAYNAME5() { return (int)53L; }

    public static int LOCALE_SABBREVDAYNAME6() { return (int)54L; }

    public static int LOCALE_SABBREVDAYNAME7() { return (int)55L; }

    public static int LOCALE_SMONTHNAME1() { return (int)56L; }

    public static int LOCALE_SMONTHNAME2() { return (int)57L; }

    public static int LOCALE_SMONTHNAME3() { return (int)58L; }

    public static int LOCALE_SMONTHNAME4() { return (int)59L; }

    public static int LOCALE_SMONTHNAME5() { return (int)60L; }

    public static int LOCALE_SMONTHNAME6() { return (int)61L; }

    public static int LOCALE_SMONTHNAME7() { return (int)62L; }

    public static int LOCALE_SMONTHNAME8() { return (int)63L; }

    public static int LOCALE_SMONTHNAME9() { return (int)64L; }

    public static int LOCALE_SMONTHNAME10() { return (int)65L; }

    public static int LOCALE_SMONTHNAME11() { return (int)66L; }

    public static int LOCALE_SMONTHNAME12() { return (int)67L; }

    public static int LOCALE_SMONTHNAME13() { return (int)4110L; }

    public static int LOCALE_SABBREVMONTHNAME1() { return (int)68L; }

    public static int LOCALE_SABBREVMONTHNAME2() { return (int)69L; }

    public static int LOCALE_SABBREVMONTHNAME3() { return (int)70L; }

    public static int LOCALE_SABBREVMONTHNAME4() { return (int)71L; }

    public static int LOCALE_SABBREVMONTHNAME5() { return (int)72L; }

    public static int LOCALE_SABBREVMONTHNAME6() { return (int)73L; }

    public static int LOCALE_SABBREVMONTHNAME7() { return (int)74L; }

    public static int LOCALE_SABBREVMONTHNAME8() { return (int)75L; }

    public static int LOCALE_SABBREVMONTHNAME9() { return (int)76L; }

    public static int LOCALE_SABBREVMONTHNAME10() { return (int)77L; }

    public static int LOCALE_SABBREVMONTHNAME11() { return (int)78L; }

    public static int LOCALE_SABBREVMONTHNAME12() { return (int)79L; }

    public static int LOCALE_SABBREVMONTHNAME13() { return (int)4111L; }

    public static int LOCALE_SPOSITIVESIGN() { return (int)80L; }

    public static int LOCALE_SNEGATIVESIGN() { return (int)81L; }

    public static int LOCALE_IPOSSIGNPOSN() { return (int)82L; }

    public static int LOCALE_INEGSIGNPOSN() { return (int)83L; }

    public static int LOCALE_IPOSSYMPRECEDES() { return (int)84L; }

    public static int LOCALE_IPOSSEPBYSPACE() { return (int)85L; }

    public static int LOCALE_INEGSYMPRECEDES() { return (int)86L; }

    public static int LOCALE_INEGSEPBYSPACE() { return (int)87L; }

    public static int LOCALE_FONTSIGNATURE() { return (int)88L; }

    public static int LOCALE_SISO639LANGNAME() { return (int)89L; }

    public static int LOCALE_SISO3166CTRYNAME() { return (int)90L; }

    public static int LOCALE_IPAPERSIZE() { return (int)4106L; }

    public static int LOCALE_SENGCURRNAME() { return (int)4103L; }

    public static int LOCALE_SNATIVECURRNAME() { return (int)4104L; }

    public static int LOCALE_SYEARMONTH() { return (int)4102L; }

    public static int LOCALE_SSORTNAME() { return (int)4115L; }

    public static int LOCALE_IDIGITSUBSTITUTION() { return (int)4116L; }

    public static int LOCALE_SNAME() { return (int)92L; }

    public static int LOCALE_SDURATION() { return (int)93L; }

    public static int LOCALE_SSHORTESTDAYNAME1() { return (int)96L; }

    public static int LOCALE_SSHORTESTDAYNAME2() { return (int)97L; }

    public static int LOCALE_SSHORTESTDAYNAME3() { return (int)98L; }

    public static int LOCALE_SSHORTESTDAYNAME4() { return (int)99L; }

    public static int LOCALE_SSHORTESTDAYNAME5() { return (int)100L; }

    public static int LOCALE_SSHORTESTDAYNAME6() { return (int)101L; }

    public static int LOCALE_SSHORTESTDAYNAME7() { return (int)102L; }

    public static int LOCALE_SISO639LANGNAME2() { return (int)103L; }

    public static int LOCALE_SISO3166CTRYNAME2() { return (int)104L; }

    public static int LOCALE_SNAN() { return (int)105L; }

    public static int LOCALE_SPOSINFINITY() { return (int)106L; }

    public static int LOCALE_SNEGINFINITY() { return (int)107L; }

    public static int LOCALE_SSCRIPTS() { return (int)108L; }

    public static int LOCALE_SPARENT() { return (int)109L; }

    public static int LOCALE_SCONSOLEFALLBACKNAME() { return (int)110L; }

    public static int LOCALE_IREADINGLAYOUT() { return (int)112L; }

    public static int LOCALE_INEUTRAL() { return (int)113L; }

    public static int LOCALE_INEGATIVEPERCENT() { return (int)116L; }

    public static int LOCALE_IPOSITIVEPERCENT() { return (int)117L; }

    public static int LOCALE_SPERCENT() { return (int)118L; }

    public static int LOCALE_SPERMILLE() { return (int)119L; }

    public static int LOCALE_SMONTHDAY() { return (int)120L; }

    public static int LOCALE_SSHORTTIME() { return (int)121L; }

    public static int LOCALE_SOPENTYPELANGUAGETAG() { return (int)122L; }

    public static int LOCALE_SSORTLOCALE() { return (int)123L; }

    public static int LOCALE_SRELATIVELONGDATE() { return (int)124L; }

    public static int LOCALE_SSHORTESTAM() { return (int)126L; }

    public static int LOCALE_SSHORTESTPM() { return (int)127L; }

    public static int LOCALE_IDEFAULTCODEPAGE() { return (int)11L; }

    public static int LOCALE_IDEFAULTANSICODEPAGE() { return (int)4100L; }

    public static int LOCALE_IDEFAULTMACCODEPAGE() { return (int)4113L; }

    public static int LOCALE_IDEFAULTEBCDICCODEPAGE() { return (int)4114L; }

    public static int LOCALE_ILANGUAGE() { return (int)1L; }

    public static int LOCALE_SABBREVLANGNAME() { return (int)3L; }

    public static int LOCALE_SABBREVCTRYNAME() { return (int)7L; }

    public static int LOCALE_IGEOID() { return (int)91L; }

    public static int LOCALE_IDEFAULTLANGUAGE() { return (int)9L; }

    public static int LOCALE_IDEFAULTCOUNTRY() { return (int)10L; }

    public static int LOCALE_IINTLCURRDIGITS() { return (int)26L; }

    public static int LOCALE_SDATE() { return (int)29L; }

    public static int LOCALE_STIME() { return (int)30L; }

    public static int LOCALE_IDATE() { return (int)33L; }

    public static int LOCALE_ILDATE() { return (int)34L; }

    public static int LOCALE_ITIME() { return (int)35L; }

    public static int LOCALE_ITIMEMARKPOSN() { return (int)4101L; }

    public static int LOCALE_ICENTURY() { return (int)36L; }

    public static int LOCALE_ITLZERO() { return (int)37L; }

    public static int LOCALE_IDAYLZERO() { return (int)38L; }

    public static int LOCALE_IMONLZERO() { return (int)39L; }

    public static int LOCALE_SKEYBOARDSTOINSTALL() { return (int)94L; }

    public static int TIME_NOMINUTESORSECONDS() { return (int)1L; }

    public static int TIME_NOSECONDS() { return (int)2L; }

    public static int TIME_NOTIMEMARKER() { return (int)4L; }

    public static int TIME_FORCE24HOURFORMAT() { return (int)8L; }

    public static int DATE_SHORTDATE() { return (int)1L; }

    public static int DATE_LONGDATE() { return (int)2L; }

    public static int DATE_USE_ALT_CALENDAR() { return (int)4L; }

    public static int DATE_YEARMONTH() { return (int)8L; }

    public static int DATE_LTRREADING() { return (int)16L; }

    public static int DATE_RTLREADING() { return (int)32L; }

    public static int DATE_AUTOLAYOUT() { return (int)64L; }

    public static int DATE_MONTHDAY() { return (int)128L; }

    public static int CAL_ICALINTVALUE() { return (int)1L; }

    public static int CAL_SCALNAME() { return (int)2L; }

    public static int CAL_IYEAROFFSETRANGE() { return (int)3L; }

    public static int CAL_SERASTRING() { return (int)4L; }

    public static int CAL_SSHORTDATE() { return (int)5L; }

    public static int CAL_SLONGDATE() { return (int)6L; }

    public static int CAL_SDAYNAME1() { return (int)7L; }

    public static int CAL_SDAYNAME2() { return (int)8L; }

    public static int CAL_SDAYNAME3() { return (int)9L; }

    public static int CAL_SDAYNAME4() { return (int)10L; }

    public static int CAL_SDAYNAME5() { return (int)11L; }

    public static int CAL_SDAYNAME6() { return (int)12L; }

    public static int CAL_SDAYNAME7() { return (int)13L; }

    public static int CAL_SABBREVDAYNAME1() { return (int)14L; }

    public static int CAL_SABBREVDAYNAME2() { return (int)15L; }

    public static int CAL_SABBREVDAYNAME3() { return (int)16L; }

    public static int CAL_SABBREVDAYNAME4() { return (int)17L; }

    public static int CAL_SABBREVDAYNAME5() { return (int)18L; }

    public static int CAL_SABBREVDAYNAME6() { return (int)19L; }

    public static int CAL_SABBREVDAYNAME7() { return (int)20L; }

    public static int CAL_SMONTHNAME1() { return (int)21L; }

    public static int CAL_SMONTHNAME2() { return (int)22L; }

    public static int CAL_SMONTHNAME3() { return (int)23L; }

    public static int CAL_SMONTHNAME4() { return (int)24L; }

    public static int CAL_SMONTHNAME5() { return (int)25L; }

    public static int CAL_SMONTHNAME6() { return (int)26L; }

    public static int CAL_SMONTHNAME7() { return (int)27L; }

    public static int CAL_SMONTHNAME8() { return (int)28L; }

    public static int CAL_SMONTHNAME9() { return (int)29L; }

    public static int CAL_SMONTHNAME10() { return (int)30L; }

    public static int CAL_SMONTHNAME11() { return (int)31L; }

    public static int CAL_SMONTHNAME12() { return (int)32L; }

    public static int CAL_SMONTHNAME13() { return (int)33L; }

    public static int CAL_SABBREVMONTHNAME1() { return (int)34L; }

    public static int CAL_SABBREVMONTHNAME2() { return (int)35L; }

    public static int CAL_SABBREVMONTHNAME3() { return (int)36L; }

    public static int CAL_SABBREVMONTHNAME4() { return (int)37L; }

    public static int CAL_SABBREVMONTHNAME5() { return (int)38L; }

    public static int CAL_SABBREVMONTHNAME6() { return (int)39L; }

    public static int CAL_SABBREVMONTHNAME7() { return (int)40L; }

    public static int CAL_SABBREVMONTHNAME8() { return (int)41L; }

    public static int CAL_SABBREVMONTHNAME9() { return (int)42L; }

    public static int CAL_SABBREVMONTHNAME10() { return (int)43L; }

    public static int CAL_SABBREVMONTHNAME11() { return (int)44L; }

    public static int CAL_SABBREVMONTHNAME12() { return (int)45L; }

    public static int CAL_SABBREVMONTHNAME13() { return (int)46L; }

    public static int CAL_SYEARMONTH() { return (int)47L; }

    public static int CAL_ITWODIGITYEARMAX() { return (int)48L; }

    public static int CAL_SSHORTESTDAYNAME1() { return (int)49L; }

    public static int CAL_SSHORTESTDAYNAME2() { return (int)50L; }

    public static int CAL_SSHORTESTDAYNAME3() { return (int)51L; }

    public static int CAL_SSHORTESTDAYNAME4() { return (int)52L; }

    public static int CAL_SSHORTESTDAYNAME5() { return (int)53L; }

    public static int CAL_SSHORTESTDAYNAME6() { return (int)54L; }

    public static int CAL_SSHORTESTDAYNAME7() { return (int)55L; }

    public static int CAL_SMONTHDAY() { return (int)56L; }

    public static int CAL_SABBREVERASTRING() { return (int)57L; }

    public static int CAL_SRELATIVELONGDATE() { return (int)58L; }

    public static int CAL_SENGLISHERANAME() { return (int)59L; }

    public static int CAL_SENGLISHABBREVERANAME() { return (int)60L; }

    public static int CAL_SJAPANESEERAFIRSTYEAR() { return (int)61L; }

    public static int CAL_GREGORIAN() { return (int)1L; }

    public static int CAL_GREGORIAN_US() { return (int)2L; }

    public static int CAL_JAPAN() { return (int)3L; }

    public static int CAL_TAIWAN() { return (int)4L; }

    public static int CAL_KOREA() { return (int)5L; }

    public static int CAL_HIJRI() { return (int)6L; }

    public static int CAL_THAI() { return (int)7L; }

    public static int CAL_HEBREW() { return (int)8L; }

    public static int CAL_GREGORIAN_ME_FRENCH() { return (int)9L; }

    public static int CAL_GREGORIAN_ARABIC() { return (int)10L; }

    public static int CAL_GREGORIAN_XLIT_ENGLISH() { return (int)11L; }

    public static int CAL_GREGORIAN_XLIT_FRENCH() { return (int)12L; }

    public static int CAL_PERSIAN() { return (int)22L; }

    public static int CAL_UMALQURA() { return (int)23L; }

    public static int LGRPID_WESTERN_EUROPE() { return (int)1L; }

    public static int LGRPID_CENTRAL_EUROPE() { return (int)2L; }

    public static int LGRPID_BALTIC() { return (int)3L; }

    public static int LGRPID_GREEK() { return (int)4L; }

    public static int LGRPID_CYRILLIC() { return (int)5L; }

    public static int LGRPID_TURKIC() { return (int)6L; }

    public static int LGRPID_TURKISH() { return (int)6L; }

    public static int LGRPID_JAPANESE() { return (int)7L; }

    public static int LGRPID_KOREAN() { return (int)8L; }

    public static int LGRPID_TRADITIONAL_CHINESE() { return (int)9L; }

    public static int LGRPID_SIMPLIFIED_CHINESE() { return (int)10L; }

    public static int LGRPID_THAI() { return (int)11L; }

    public static int LGRPID_HEBREW() { return (int)12L; }

    public static int LGRPID_ARABIC() { return (int)13L; }

    public static int LGRPID_VIETNAMESE() { return (int)14L; }

    public static int LGRPID_INDIC() { return (int)15L; }

    public static int LGRPID_GEORGIAN() { return (int)16L; }

    public static int LGRPID_ARMENIAN() { return (int)17L; }

}

